// The generated targets: each file's region roster (markers hand-placed
// once, bodies from the region builders), the whole generated files, and
// the module schema JSON only wholeFiles emits.

import { join, resolve } from "node:path";
import { z } from "zod";
import { type ModuleManifest, manifestSchema } from "../lib/module_manifests.ts";
import type { BaseOwnershipEntry, OwnershipEntry } from "../ownership/enforcement_tables.ts";
import {
  excludeRegion,
  hasToolchainDefault,
  moduleChoices,
  trackingLabelValidator,
  trackingStreams,
} from "./copier_questions.ts";
import {
  dependabotLabelsSpan,
  newRepoModuleRoster,
  readmeModuleRoster,
  skillModuleRosterBullets,
  skillModuleRosterRows,
} from "./doc_rosters.ts";
import { baseOwnershipRegion, knownModules, moduleOwnershipRegion } from "./ownership_regions.ts";
import {
  type PagesManifest,
  pagesBuildCommand,
  pagesBuildRow,
  pagesInstallCommand,
  pagesInstallRow,
  pagesSetup,
  pagesSetupDefault,
  pagesSetupMeaning,
} from "./pages.ts";
import { THEME_TOKENS_CSS, themeTokensCss } from "./theme_tokens.ts";
import {
  bunPinnedActionDirs,
  bunToolchainPin,
  pinFileContent,
  toolchainPinRows,
  toolchainPins,
  toolchainPinsRegion,
} from "./toolchain_pins.ts";

const REPO_ROOT = resolve(import.meta.dir, "..", "..");

/** templates/module.schema.json: the manifest zod schema as JSON Schema
 *  (draft-07 - what yaml-language-server speaks natively). Regex/pattern
 *  and structural constraints translate; the zod refinements (single-line,
 *  quote/metacharacter safety) have no JSON Schema equivalent and are
 *  silently skipped, so the loader stays the enforcement layer and the
 *  schema is editor assistance only. */
export function moduleSchemaJson(): string {
  const { $schema, ...schema } = z.toJSONSchema(manifestSchema, { target: "draft-7" });
  return `${JSON.stringify(
    {
      $schema,
      $comment:
        "Generated by scripts/generate.ts from the zod schema in " +
        "scripts/lib/module_manifests.ts - do not edit. Only structural and " +
        "pattern constraints translate to JSON Schema; the zod refinements " +
        "(single-line, quote/metacharacter safety) do not, so the loader " +
        "remains the enforcement layer.",
      title: "repo-platform module manifest (templates/<module>/module.yml)",
      ...schema,
    },
    null,
    2,
  )}\n`;
}

export interface RegionInputs {
  manifests: ModuleManifest[];
  pages: PagesManifest[];
  reserved: string[];
  moduleOwnership: Record<string, OwnershipEntry[]>;
  baseOwnership: {
    enforced: BaseOwnershipEntry[];
  };
}

type SpanRegion = [name: string, body: (inputs: RegionInputs) => string[], sources?: string];
type InlineRegion = [name: string, body: (inputs: RegionInputs) => string];

// At least one region list is required by construction, and inline regions
// (single-line bodies: table cells and mid-sentence prose spans) exist only
// for markdown targets: line-comment files cannot carry inline markers at
// all.
type MarkdownRegions =
  | { regions: SpanRegion[]; inlineRegions?: InlineRegion[] }
  | { regions?: SpanRegion[]; inlineRegions: InlineRegion[] };

export type Target =
  | { file: string; syntax: "line"; prefix: string; regions: SpanRegion[] }
  | ({ file: string; syntax: "markdown" } & MarkdownRegions);

// The region roster is a function of the manifests and the tree: each
// tracking stream contributes its question's validator region (the markers
// are still hand-placed once, next to the hand-written question), and each
// action manifest fenced for the bun setup contributes its region.
export function targets(manifests: ModuleManifest[]): Target[] {
  const streams = trackingStreams(manifests);
  return [
    {
      file: "copier.yml",
      syntax: "line",
      prefix: "#",
      regions: [
        ["module-choices", ({ manifests }) => moduleChoices(manifests)],
        [
          "conditional-excludes",
          () => excludeRegion(),
          "the module manifests and the base templates' gated filenames",
        ],
        ["has-toolchain-default", ({ manifests }) => hasToolchainDefault(manifests)],
        ["pages-setup", ({ pages }) => pagesSetup(pages)],
        ["pages-install-command", ({ pages }) => pagesInstallCommand(pages)],
        ["pages-build-command", ({ pages }) => pagesBuildCommand(pages)],
        ...streams.map(
          (stream, index): SpanRegion => [
            `${stream.module}-label-validator`,
            ({ reserved }) => trackingLabelValidator(streams, index, reserved),
          ],
        ),
      ],
    },
    {
      file: "actions/validate-template-report/validator/ownership.ts",
      syntax: "line",
      prefix: "//",
      regions: [
        ["known-modules", ({ manifests }) => knownModules(manifests)],
        ["toolchain-pins", ({ manifests }) => toolchainPinsRegion(manifests)],
        [
          "base-ownership",
          ({ baseOwnership }) => baseOwnershipRegion(baseOwnership),
          "templates/base/ownership.yml and the base templates",
        ],
        [
          "module-ownership",
          ({ moduleOwnership }) => moduleOwnershipRegion(moduleOwnership),
          "the module.yml ownership declarations and the module templates",
        ],
      ],
    },
    {
      file: "README.md",
      syntax: "markdown",
      regions: [["module-roster", ({ manifests }) => readmeModuleRoster(manifests)]],
    },
    {
      file: "docs/new-repo.md",
      syntax: "markdown",
      inlineRegions: [
        ["module-roster", ({ manifests }) => newRepoModuleRoster(manifests)],
        ["dependabot-labels", ({ manifests }) => dependabotLabelsSpan(manifests)],
      ],
    },
    {
      file: "docs/settings.md",
      syntax: "markdown",
      inlineRegions: [["dependabot-labels", ({ manifests }) => dependabotLabelsSpan(manifests)]],
    },
    {
      file: "docs/pages.md",
      syntax: "markdown",
      inlineRegions: [
        ["pages-setup-meaning", ({ pages }) => pagesSetupMeaning(pages)],
        ["pages-setup-default", ({ pages }) => pagesSetupDefault(pages)],
        ["pages-install-default", ({ pages }) => pagesInstallRow(pages)],
        ["pages-build-default", ({ pages }) => pagesBuildRow(pages)],
      ],
    },
    {
      file: "docs/toolchains.md",
      syntax: "markdown",
      regions: [["toolchain-pins", ({ manifests }) => toolchainPinRows(manifests)]],
    },
    {
      file: "skills/repo-platform-add-module/SKILL.md",
      syntax: "markdown",
      regions: [["module-roster", ({ manifests }) => skillModuleRosterRows(manifests)]],
    },
    {
      file: "skills/repo-platform-new-project/references/questions.md",
      syntax: "markdown",
      regions: [["module-roster", ({ manifests }) => skillModuleRosterBullets(manifests)]],
    },
  ];
}

// Fully-generated files (no markers): the whole byte content is the
// generator's output, byte-compared by --check like the regions. Each
// carries its own staleness cause - their sources differ from the
// manifests the regions derive from.
export function wholeFiles(
  manifests: ModuleManifest[],
): [file: string, content: (inputs: RegionInputs) => string, stale: string][] {
  return [
    [
      "templates/module.schema.json",
      () => moduleSchemaJson(),
      "its content does not match the zod schema in scripts/lib/module_manifests.ts " +
        "(a zod upgrade changing the emitted JSON Schema is the usual cause)",
    ],
    [
      THEME_TOKENS_CSS,
      () => themeTokensCss(),
      "its content does not match the token data in actions/pages-site/.vitepress/theme/tokens.ts",
    ],
    ...toolchainPins(manifests).flatMap(
      (pin): [string, (inputs: RegionInputs) => string, string][] =>
        // The template's dotfile and the sync writer's copy under files/,
        // from the one manifest pin.
        [`templates/${pin.module}/${pin.file}`, `files/${pin.module}/${pin.file}`].map(
          (file): [string, (inputs: RegionInputs) => string, string] => [
            file,
            () => pinFileContent(pin),
            `its content does not match the toolchain pin in templates/${pin.module}/module.yml`,
          ],
        ),
    ),
    ...bunPinnedActionDirs(join(REPO_ROOT, "actions")).map(
      (dir): [string, (inputs: RegionInputs) => string, string] => [
        `${dir}/.bun-version`,
        () => pinFileContent(bunToolchainPin(manifests)),
        "its content does not match the bun toolchain pin in templates/bun/module.yml " +
          "(the composite actions run on the manifests' bun pin, never the caller's)",
      ],
    ),
  ];
}
