#!/usr/bin/env bun
// Assemble a build-branch tree: the minimal orphan-branch content that copier
// consumes downstream.
//
// The generated `staging` and `latest` branches carry exactly what copier
// needs and nothing else:
//
// - copier.yml       (byte copy from this checkout's root)
// - template/        (composed from templates/ via compose_template.build)
// - migrations/      (the runner + migration scripts)
// - README.md        (static per-channel explainer)
// - BUILD_INFO.yml   (channel, plus version on the latest channel)
//
// Content is fully deterministic - no timestamps or source SHAs in-tree, so
// the append-only build branches only gain a commit when something real
// changed (provenance lives in the build commit message instead). No .github/
// is included: nothing may trigger on the build branches.
//
// Usage:
//   bun .github/scripts/build_branch_tree.ts --dest DIR --channel staging
//   bun .github/scripts/build_branch_tree.ts --dest DIR --channel latest --version vX.Y.Z

import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { build, writeOutput } from "../../scripts/compose_template.ts";

const REPO_ROOT = resolve(import.meta.dir, "..", "..");

const README = (channel: string) => `\
# repo-platform build branch (${channel})

This branch is GENERATED by the build-branches workflow on \`main\` - do not
commit to it or open pull requests against it (they are closed automatically).
Template sources live in \`templates/\` on \`main\`.

- \`staging\` is rebuilt from the latest \`main\` commit on every push.
- \`latest\` is rebuilt from the latest release and tagged \`templates/vX.Y.Z\`.

Consume with copier, e.g.:

    copier copy gh:Vivswan/repo-platform . --vcs-ref templates/vX.Y.Z   # latest
    copier copy gh:Vivswan/repo-platform . --vcs-ref staging            # staging
`;

function usageError(message: string): never {
  console.error(`error: ${message}`);
  process.exit(2);
}

function copyMigrations(dest: string): void {
  const src = join(REPO_ROOT, "migrations");
  const copyDir = (rel: string) => {
    for (const name of readdirSync(join(src, rel)).sort()) {
      const childRel = rel ? `${rel}/${name}` : name;
      const stat = lstatSync(join(src, childRel));
      if (stat.isDirectory() && !stat.isSymbolicLink()) {
        copyDir(childRel);
      } else if (stat.isFile()) {
        const target = join(dest, "migrations", childRel);
        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, readFileSync(join(src, childRel)));
      }
    }
  };
  copyDir("");
}

interface Args {
  dest: string;
  channel: "staging" | "latest";
  version?: string;
}

function parseArgs(argv: string[]): Args {
  let dest: string | undefined;
  let channel: string | undefined;
  let version: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const value = () => {
      i++;
      if (i >= argv.length) usageError(`argument ${arg}: expected one argument`);
      return argv[i];
    };
    if (arg === "--dest") dest = value();
    else if (arg === "--channel") channel = value();
    else if (arg === "--version") version = value();
    else usageError(`unrecognized argument: ${arg}`);
  }
  if (!dest) usageError("the following arguments are required: --dest");
  if (!channel) usageError("the following arguments are required: --channel");
  if (channel !== "staging" && channel !== "latest") {
    usageError(`argument --channel: invalid choice: '${channel}' (choose from staging, latest)`);
  }
  return { dest, channel, version };
}

function main(): number {
  const args = parseArgs(process.argv.slice(2));

  if (args.channel === "latest" && !args.version) {
    usageError(
      "--channel latest builds a release tree and needs --version; " +
        "pass the release tag, e.g. --version v1.2.3",
    );
  }
  if (args.channel === "staging" && args.version) {
    usageError(
      `--version ${args.version} does not apply to --channel staging ` +
        "(staging always builds from main HEAD); drop --version or use --channel latest",
    );
  }

  const dest = resolve(args.dest);
  if (dest === REPO_ROOT || REPO_ROOT.startsWith(`${dest}/`) || dest.startsWith(`${REPO_ROOT}/`)) {
    usageError(
      `--dest ${dest} is inside the repository and would be wiped along ` +
        "with the checkout; pass a path outside it, e.g. --dest /tmp/build-tree",
    );
  }
  if (existsSync(dest)) rmSync(dest, { recursive: true });
  mkdirSync(dest, { recursive: true });

  const composed = build();
  writeOutput(composed, join(dest, "template"));
  writeFileSync(join(dest, "copier.yml"), readFileSync(join(REPO_ROOT, "copier.yml")));
  copyMigrations(dest);
  writeFileSync(join(dest, "README.md"), README(args.channel));
  let info = `channel: ${args.channel}\n`;
  if (args.version) info += `version: ${args.version}\n`;
  writeFileSync(join(dest, "BUILD_INFO.yml"), info);

  console.log(`assembled ${args.channel} build tree into ${dest}`);
  return 0;
}

process.exit(main());
