#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Assemble a build-branch tree: the minimal orphan-branch content that copier
consumes downstream.

The generated `staging` and `latest` branches carry exactly what copier needs
and nothing else:

- copier.yml       (byte copy from this checkout's root)
- template/        (composed from templates/ via compose_template.build)
- migrations/      (the runner + migration scripts, no __pycache__)
- README.md        (static per-channel explainer)
- BUILD_INFO.yml   (channel, plus version on the latest channel)

Content is fully deterministic - no timestamps or source SHAs in-tree, so the
append-only build branches only gain a commit when something real changed
(provenance lives in the build commit message instead). No .github/ is
included: nothing may trigger on the build branches.

Usage:
  uv run .github/scripts/build_branch_tree.py --dest DIR --channel staging
  uv run .github/scripts/build_branch_tree.py --dest DIR --channel latest --version vX.Y.Z
"""

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
# compose_template.py lives in scripts/ (it is also a local dev tool); this
# script is CI-only and lives in .github/scripts/, so bridge the import.
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from compose_template import build, write_output  # noqa: E402

README = """\
# repo-platform build branch ({channel})

This branch is GENERATED by the build-branches workflow on `main` - do not
commit to it or open pull requests against it (they are closed automatically).
Template sources live in `templates/` on `main`.

- `staging` is rebuilt from the latest `main` commit on every push.
- `latest` is rebuilt from the latest release and tagged `templates/vX.Y.Z`.

Consume with copier, e.g.:

    copier copy gh:Vivswan/repo-platform . --vcs-ref templates/vX.Y.Z   # latest
    copier copy gh:Vivswan/repo-platform . --vcs-ref staging            # staging
"""


def copy_migrations(dest: Path) -> None:
    src = REPO_ROOT / "migrations"
    for path in sorted(src.rglob("*")):
        rel = path.relative_to(src)
        if "__pycache__" in rel.parts or not path.is_file():
            continue
        target = dest / "migrations" / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(path.read_bytes())


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Assemble the minimal build-branch tree copier consumes.",
    )
    parser.add_argument("--dest", required=True, help="output directory (wiped)")
    parser.add_argument("--channel", required=True, choices=["staging", "latest"])
    parser.add_argument("--version", help="release version (vX.Y.Z); latest channel only")
    args = parser.parse_args()

    if args.channel == "latest" and not args.version:
        parser.error("--version is required with --channel latest")
    if args.channel == "staging" and args.version:
        parser.error("--version only applies to --channel latest")

    dest = Path(args.dest).resolve()
    if dest == REPO_ROOT or REPO_ROOT in dest.parents:
        parser.error("--dest must be outside the repository")
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    composed = build()
    write_output(composed, dest / "template")
    (dest / "copier.yml").write_bytes((REPO_ROOT / "copier.yml").read_bytes())
    copy_migrations(dest)
    (dest / "README.md").write_text(README.format(channel=args.channel))
    info = f"channel: {args.channel}\n"
    if args.version:
        info += f"version: {args.version}\n"
    (dest / "BUILD_INFO.yml").write_text(info)

    print(f"assembled {args.channel} build tree into {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
