#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Validate a repo generated/managed by Vivswan/repo-platform.

Checks (errors fail the run):
  1. .copier-answers.yml and .repo-platform.yml exist, and the latter
     records a valid `template.modules` list
  2. .gitignore managed/local marker sections appear exactly once
  3. Every .yml/.yaml file parses
  4. No unresolved merge-conflict markers in text files
  5. .github/workflows/ci.yml exists (the template always generates and
     manages it), an `all-green` job exists and its `needs:` lists every
     other job, and a `typography` job exists

Advisories (printed, never fail): missing actionlint / yamllint /
commit-names jobs in ci.yml.

Usage: uv run actions/validate-template/validate_generated_files.py [--self] [target-dir]
(or: pip install pyyaml && python3 <script>, as the CI steps do)

--self: validate repo-platform itself. Skips the registration-file check
(the template repo is not generated from itself, so it has no
.copier-answers.yml / .repo-platform.yml); all other checks apply.
"""

import argparse
import re
import sys
from collections.abc import Iterator
from pathlib import Path

import yaml

SKIP_DIRS = {
    ".git",
    "node_modules",
    ".venv",
    "dist",
    "build",
    "coverage",
    "htmlcov",
    "__pycache__",
    ".output",
    ".wxt",
    ".astro",
    ".next",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
}

MARKER_FILES = {
    ".gitignore": [
        "# BEGIN REPOSITORY LOCAL",
        "# END REPOSITORY LOCAL",
        "# BEGIN REPO-PLATFORM MANAGED",
        "# END REPO-PLATFORM MANAGED",
    ],
}

CONFLICT = re.compile(r"^(<{7} |={7}$|>{7} )", re.MULTILINE)

TEXT_SUFFIXES = {
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".py",
    ".pyi",
    ".yml",
    ".yaml",
    ".json",
    ".jinja",
    ".md",
    ".html",
    ".css",
    ".toml",
    ".cfg",
    ".ini",
    ".txt",
    ".sh",
    ".astro",
    ".template",
}

ADVISORY_JOBS = ["actionlint", "yamllint", "commit-names"]

KNOWN_MODULES = {
    "agents",
    "bun",
    "uv",
    "pages",
    "release-please",
    "issue-templates",
    "pr-title",
    "auto-assign",
    "settings-sync",
}


def walk(root: Path) -> Iterator[Path]:
    for path in sorted(root.rglob("*")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.is_file() and not path.is_symlink():
            yield path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate a repo generated/managed by Vivswan/repo-platform.",
    )
    parser.add_argument(
        "target",
        nargs="?",
        default=".",
        help="directory to validate (default: current directory)",
    )
    parser.add_argument(
        "--self",
        dest="self_mode",
        action="store_true",
        help="validate repo-platform itself (skips the registration-file check)",
    )
    args = parser.parse_args()
    root = Path(args.target).resolve()
    errors: list[str] = []
    advisories: list[str] = []

    # 1. Registration files (not applicable to the template repo itself)
    if not args.self_mode:
        for required in (".copier-answers.yml", ".repo-platform.yml"):
            if not (root / required).is_file():
                errors.append(
                    f"{required} is missing - the repo was not generated by the "
                    "repo-platform template (or the file was deleted); restore it "
                    "from git history or regenerate with "
                    "'copier copy gh:Vivswan/repo-platform . --vcs-ref staging' (or a templates/vX.Y.Z tag)"
                )
        registration = root / ".repo-platform.yml"
        if registration.is_file():
            try:
                data = yaml.safe_load(registration.read_text(encoding="utf-8")) or {}
            except yaml.YAMLError:
                data = {}
            template_block = data.get("template") if isinstance(data, dict) else None
            modules = template_block.get("modules") if isinstance(template_block, dict) else None
            if not isinstance(modules, list):
                errors.append(
                    ".repo-platform.yml: template.modules is missing or not a list "
                    "(the file may have failed to parse); set it to a YAML list of "
                    "module names, e.g. modules: [uv, release-please]"
                )
            else:
                unknown = sorted(
                    str(m) for m in modules if not isinstance(m, str) or m not in KNOWN_MODULES
                )
                if unknown:
                    errors.append(
                        f".repo-platform.yml: unknown module(s): {', '.join(unknown)} - "
                        f"valid modules are: {', '.join(sorted(KNOWN_MODULES))}; "
                        "fix the template.modules list"
                    )

    # 2. Marker sections exactly once (.gitignore is always generated by the
    # template - absence means the repo is damaged, not unconfigured)
    for rel, markers in MARKER_FILES.items():
        path = root / rel
        if not path.is_file():
            errors.append(
                f"{rel} is missing - the template always generates it, so the repo "
                "is damaged; restore the file from git history or run a template sync"
            )
            continue
        content = path.read_text(encoding="utf-8", errors="replace")
        for marker in markers:
            count = content.count(marker)
            if count != 1:
                errors.append(
                    f"{rel}: marker {marker!r} appears {count} times (expected 1) - "
                    "a merge or manual edit broke the managed sections; restore one "
                    "LOCAL section followed by one MANAGED section"
                )

    # 3 + 4. YAML parses; no conflict markers
    for path in walk(root):
        rel = path.relative_to(root)
        if path.suffix in (".yml", ".yaml"):
            try:
                yaml.safe_load(path.read_text(encoding="utf-8"))
            except yaml.YAMLError as exc:
                errors.append(
                    f"{rel}: does not parse as YAML ({exc}); fix the syntax at the position shown"
                )
        if path.suffix in TEXT_SUFFIXES or path.suffix == "":
            try:
                content = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            if CONFLICT.search(content):
                errors.append(
                    f"{rel}: contains unresolved merge-conflict markers left by "
                    "copier or git; edit the file and resolve each conflict block"
                )

    # 5. all-green convention in ci.yml. The file is template-managed and
    # always generated (repo-specific jobs live in the repo-owned checks.yml
    # it calls), so a missing ci.yml means the repo is damaged.
    ci_path = root / ".github" / "workflows" / "ci.yml"
    if not ci_path.is_file():
        errors.append(
            ".github/workflows/ci.yml is missing - the template always "
            "generates and manages it; restore the file from git history or "
            "run a template sync"
        )
    else:
        try:
            ci = yaml.safe_load(ci_path.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            ci = {}
        jobs = ci.get("jobs") or {}
        if not jobs:
            errors.append(
                "ci.yml: exists but defines no jobs - the file is empty or failed "
                "to parse as YAML; restore the managed file via a template sync"
            )
        else:
            if "all-green" not in jobs:
                errors.append(
                    "ci.yml: no `all-green` job - branch protection gates on that "
                    "single required check; add an all-green job whose `needs:` "
                    "lists every other job"
                )
            else:
                needs = jobs["all-green"].get("needs") or []
                if isinstance(needs, str):
                    needs = [needs]
                # release-please style jobs that run after the gate are exempt.
                downstream = {
                    name
                    for name, job in jobs.items()
                    if name != "all-green"
                    and "all-green"
                    in (
                        [job.get("needs")]
                        if isinstance(job.get("needs"), str)
                        else (job.get("needs") or [])
                    )
                }
                expected = set(jobs) - {"all-green"} - downstream
                missing = expected - set(needs)
                if missing:
                    errors.append(
                        f"ci.yml: all-green `needs:` is missing job(s): "
                        f"{', '.join(sorted(missing))} - those jobs cannot gate "
                        "merges; add them to the all-green job's needs list"
                    )
            if "typography" not in jobs:
                errors.append(
                    "ci.yml: no `typography` job - the no-look-alike-characters rule "
                    "is unenforced; add a job using "
                    "Vivswan/repo-platform/actions/check-typography"
                )
            for advisory in ADVISORY_JOBS:
                if advisory not in jobs:
                    advisories.append(f"ci.yml: consider adding a `{advisory}` job")

    for advisory in advisories:
        print(f"advisory: {advisory}")
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        print(f"\n{len(errors)} error(s).", file=sys.stderr)
        return 1
    print("Validation passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
