#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Validate a repo generated/managed by Vivswan/repo-platform.

Checks (errors fail the run):
  1. .copier-answers.yml and .repo-platform.yml exist
  2. .gitignore managed/local marker sections appear exactly once
  3. Every .yml/.yaml file parses
  4. No unresolved merge-conflict markers in text files
  5. If .github/workflows/ci.yml exists: an `all-green` job exists and its
     `needs:` lists every other job, and a `typography` job exists

Advisories (printed, never fail): missing actionlint / yamllint /
commit-names jobs in ci.yml.

Usage: uv run actions/validate-template/validate_generated_files.py [--self] [target-dir]
(or: pip install pyyaml && python3 <script>, as the CI steps do)

--self: validate repo-platform itself. Skips the registration-file check
(the template repo is not generated from itself, so it has no
.copier-answers.yml / .repo-platform.yml); all other checks apply.
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

SKIP_DIRS = {
    ".git",
    "node_modules",
    ".venv",
    "dist",
    "build",
    "coverage",
    "htmlcov",
    "__pycache__",
    ".output",
    ".wxt",
    ".astro",
    ".next",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
}

MARKER_FILES = {
    ".gitignore": [
        "# BEGIN REPOSITORY LOCAL",
        "# END REPOSITORY LOCAL",
        "# BEGIN REPO-PLATFORM MANAGED",
        "# END REPO-PLATFORM MANAGED",
    ],
}

CONFLICT = re.compile(r"^(<{7} |={7}$|>{7} )", re.MULTILINE)

TEXT_SUFFIXES = {
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".py",
    ".pyi",
    ".yml",
    ".yaml",
    ".json",
    ".jinja",
    ".md",
    ".html",
    ".css",
    ".toml",
    ".cfg",
    ".ini",
    ".txt",
    ".sh",
    ".astro",
    ".template",
}

ADVISORY_JOBS = ["actionlint", "yamllint", "commit-names"]


def walk(root: Path):
    for path in sorted(root.rglob("*")):
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.is_file() and not path.is_symlink():
            yield path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate a repo generated/managed by Vivswan/repo-platform.",
    )
    parser.add_argument(
        "target",
        nargs="?",
        default=".",
        help="directory to validate (default: current directory)",
    )
    parser.add_argument(
        "--self",
        dest="self_mode",
        action="store_true",
        help="validate repo-platform itself (skips the registration-file check)",
    )
    args = parser.parse_args()
    root = Path(args.target).resolve()
    errors: list[str] = []
    advisories: list[str] = []

    # 1. Registration files (not applicable to the template repo itself)
    if not args.self_mode:
        for required in (".copier-answers.yml", ".repo-platform.yml"):
            if not (root / required).is_file():
                errors.append(f"{required} is missing")

    # 2. Marker sections exactly once (.gitignore is always generated by the
    # template - absence means the repo is damaged, not unconfigured)
    for rel, markers in MARKER_FILES.items():
        path = root / rel
        if not path.is_file():
            errors.append(f"{rel} is missing")
            continue
        content = path.read_text(encoding="utf-8", errors="replace")
        for marker in markers:
            count = content.count(marker)
            if count != 1:
                errors.append(f"{rel}: marker {marker!r} appears {count} times (expected 1)")

    # 3 + 4. YAML parses; no conflict markers
    for path in walk(root):
        rel = path.relative_to(root)
        if path.suffix in (".yml", ".yaml"):
            try:
                yaml.safe_load(path.read_text(encoding="utf-8"))
            except yaml.YAMLError as exc:
                errors.append(f"{rel}: YAML parse error: {exc}")
        if path.suffix in TEXT_SUFFIXES or path.suffix == "":
            try:
                content = path.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            if CONFLICT.search(content):
                errors.append(f"{rel}: unresolved merge-conflict markers")

    # 5. all-green convention in ci.yml (the file itself is repo-owned and
    # optional, but if it exists it must parse and follow the convention)
    ci_path = root / ".github" / "workflows" / "ci.yml"
    if ci_path.is_file():
        try:
            ci = yaml.safe_load(ci_path.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            ci = {}
        jobs = ci.get("jobs") or {}
        if not jobs:
            errors.append("ci.yml: exists but defines no jobs (parse failure or empty)")
        else:
            if "all-green" not in jobs:
                errors.append("ci.yml: no `all-green` job (the single required status check)")
            else:
                needs = jobs["all-green"].get("needs") or []
                if isinstance(needs, str):
                    needs = [needs]
                # release-please style jobs that run after the gate are exempt.
                downstream = {
                    name
                    for name, job in jobs.items()
                    if name != "all-green"
                    and "all-green"
                    in (
                        [job.get("needs")]
                        if isinstance(job.get("needs"), str)
                        else (job.get("needs") or [])
                    )
                }
                expected = set(jobs) - {"all-green"} - downstream
                missing = expected - set(needs)
                if missing:
                    errors.append(
                        f"ci.yml: all-green `needs:` is missing job(s): {', '.join(sorted(missing))}"
                    )
            if "typography" not in jobs:
                errors.append(
                    "ci.yml: no `typography` job (use Vivswan/repo-platform/actions/check-typography)"
                )
            for advisory in ADVISORY_JOBS:
                if advisory not in jobs:
                    advisories.append(f"ci.yml: consider adding a `{advisory}` job")

    for advisory in advisories:
        print(f"advisory: {advisory}")
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        print(f"\n{len(errors)} error(s).", file=sys.stderr)
        return 1
    print("Validation passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
