// read_target.ts run for real against a stub gh: the live facts it writes
// (outputs and RUNNER_TEMP files) per delivery mode, and the branch-mode
// refusals (the default branch, a missing branch) - each row one whole
// outcome.

import { describe, expect, test } from "bun:test";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { boundedSpawnSync } from "../shared/bounded_spawn";
import { tempDirs } from "../shared/temp_dir";

const temp = tempDirs();
const script = join(import.meta.dir, "../../.github/scripts/sync/read_target.ts");

const REPO = JSON.stringify({
  default_branch: "main",
  description: "A demo",
  homepage: "",
  topics: ["a", "b"],
  private: false,
});

// `gh api repos/<t>` serves the repository; `repos/<t>/branches/<b>` answers
// 200 when the request path's branch segment equals STUB_BRANCH (as sent,
// so an encoded name must arrive encoded), a non-404 failure quoting the
// request path when STUB_BRANCH_FAIL is set, and 404 otherwise.
const ghStub = `#!/usr/bin/env bash
case "$2" in
  repos/o/r) printf '%s' "$STUB_REPO" ;;
  repos/o/r/branches/*)
    if [ -n "$STUB_BRANCH_FAIL" ]; then
      echo "error connecting to api.github.com: GET $2" >&2
      exit 1
    fi
    if [ "\${2#repos/o/r/branches/}" = "$STUB_BRANCH" ]; then exit 0; fi
    echo "HTTP 404: Branch not found" >&2
    exit 1 ;;
  *) echo "unexpected: $*" >&2; exit 2 ;;
esac
`;

function run(env: Record<string, string>) {
  const root = temp.dir("read-target-");
  const bin = join(root, "bin");
  mkdirSync(bin);
  writeFileSync(join(bin, "gh"), ghStub, { mode: 0o755 });
  const runnerTemp = join(root, "rt");
  mkdirSync(runnerTemp);
  const output = join(root, "gh-output.txt");
  writeFileSync(output, "");
  const proc = boundedSpawnSync(["bun", script], {
    env: {
      ...process.env,
      PATH: `${bin}:${process.env.PATH}`,
      STUB_REPO: REPO,
      STUB_BRANCH: "chore/fuzzer",
      TARGET: "o/r",
      TARGET_DISPLAY: "o/r",
      HIDE_DETAILS: "false",
      GH_TOKEN: "t",
      RUNNER_TEMP: runnerTemp,
      GITHUB_OUTPUT: output,
      GITHUB_EVENT_PATH: "",
      TARGET_BRANCH: "",
      ...env,
    },
  });
  return {
    exitCode: proc.exitCode,
    stdout: proc.stdout,
    stderr: proc.stderr,
    outputs: readFileSync(output, "utf-8"),
    description: readFileSync(join(runnerTemp, "description.txt"), "utf-8"),
  };
}

describe("read_target", () => {
  test.each<{
    reason: string;
    env: Record<string, string>;
    exitCode: number;
    outputs: string;
    stdoutHas: string[];
    /** Text that must appear on neither stream (a hidden target's names). */
    absent?: string[];
  }>([
    {
      reason: "default mode: the default branch is the checkout ref and the delivery target",
      env: {},
      exitCode: 0,
      outputs: "default_branch=main\nprivate=false\nmode=default\ncheckout_ref=main\nbranch=\n",
      stdoutHas: [],
    },
    {
      reason: "branch mode: an existing branch becomes the checkout ref",
      env: { TARGET_BRANCH: "chore/fuzzer" },
      exitCode: 0,
      outputs:
        "default_branch=main\nprivate=false\nmode=branch\ncheckout_ref=chore/fuzzer\nbranch=chore/fuzzer\n",
      stdoutHas: [],
    },
    {
      reason: "a branch name with a URL-special character reaches the API percent-encoded",
      env: { TARGET_BRANCH: "fix#123", STUB_BRANCH: "fix%23123" },
      exitCode: 0,
      outputs:
        "default_branch=main\nprivate=false\nmode=branch\ncheckout_ref=fix#123\nbranch=fix#123\n",
      stdoutHas: [],
    },
    {
      reason:
        "branch mode refuses the sync's own rolling branch (a render onto it would skip the disarm)",
      env: { TARGET_BRANCH: "automation/repo-platform", STUB_BRANCH: "automation/repo-platform" },
      exitCode: 1,
      outputs: "default_branch=main\nprivate=false\n",
      stdoutHas: [
        "::error::branch automation/repo-platform is the sync's own rolling branch: it is regenerated by a dispatch without branch, never rendered onto.",
      ],
    },
    {
      reason: "a hidden target's failed probe keeps both spellings of the branch off both streams",
      env: {
        TARGET_BRANCH: "feat/customer#123",
        HIDE_DETAILS: "true",
        TARGET_DISPLAY: "repo #1",
        STUB_BRANCH_FAIL: "1",
      },
      exitCode: 1,
      outputs: "default_branch=main\nprivate=false\n",
      stdoutHas: [
        "::add-mask::feat/customer#123",
        // The mask command escapes % as %25; the runner unescapes it.
        "::add-mask::feat/customer%2523123",
        "(gh output hidden: private repository)",
        "::error::cannot read repo #1's branch (name hidden: private repository) (gh exit 1)",
      ],
      absent: ["customer", "api.github.com"],
    },
    {
      reason: "branch mode refuses the default branch (that flow is the sync PR)",
      env: { TARGET_BRANCH: "main" },
      exitCode: 1,
      outputs: "default_branch=main\nprivate=false\n",
      stdoutHas: ["::error::branch 'main' is o/r's default branch"],
    },
    {
      reason: "branch mode refuses a branch the target does not have",
      env: { TARGET_BRANCH: "feat/missing" },
      exitCode: 1,
      outputs: "default_branch=main\nprivate=false\n",
      stdoutHas: ["::error::o/r has no branch 'feat/missing'; push the branch first, then re-run."],
    },
    {
      reason: "a hidden target's branch is masked and its refusal names no branch",
      env: { TARGET_BRANCH: "feat/missing", HIDE_DETAILS: "true", TARGET_DISPLAY: "repo #1" },
      exitCode: 1,
      outputs: "default_branch=main\nprivate=false\n",
      stdoutHas: [
        "::add-mask::feat/missing",
        "::error::repo #1 has no branch (name hidden: private repository); push the branch first, then re-run.",
      ],
    },
  ])("$reason", ({ env, exitCode, outputs, stdoutHas, absent }) => {
    const r = run(env);
    expect({ exitCode: r.exitCode, outputs: r.outputs, description: r.description }).toEqual({
      exitCode,
      outputs,
      description: "A demo\n",
    });
    for (const line of stdoutHas) expect(r.stdout).toContain(line);
    // The mask commands themselves name the value, so they are excluded
    // from the leak check: the runner consumes them, the log never shows them.
    const shown = `${r.stdout.replaceAll(/^::add-mask::.*$/gm, "")}${r.stderr}`;
    for (const text of absent ?? []) expect(shown).not.toContain(text);
  });
});
