// The writer's record of what it last wrote: .github/repo-platform-manifest.json
// in the shape actions/shared/manifest.ts already emits and parses (one
// entry per line, sha256 of the whole file for managed, of the marker-bounded
// region for split, of the link target for a symbolic link), so a repository
// stamped by the previous pipeline reads as already-recorded. The manifest's own entry carries the build sha in
// its `commit` slot and no hash (a self-hash would be circular).

import { createHash } from "node:crypto";
import type { RegionKind } from "../../../../actions/plan/files_config.ts";
import {
  type AssertNever,
  HASH_REGION_MARKERS,
  HTML_REGION_MARKERS,
  type RegionMarkers,
} from "../../../../actions/shared/grammar.ts";
import {
  entryBody,
  type JsonValue,
  MANIFEST_NAME,
  type ManifestEntryShape,
  parseManifestFiles,
  type RecordedClass,
} from "../../../../actions/shared/manifest.ts";
import { existingFile, writeFile } from "./target_files.ts";

export { MANIFEST_NAME };

/** A null hash is never written by this writer; it is carried from a
 *  record another tool left unstamped, so the file stays held rather than
 *  orphaned. */
export type ManifestRecord =
  | { class: "managed"; hash: string | null }
  | { class: "split"; grammar: "managed-region"; begin: string; end: string; hash: string | null }
  | { class: "starter" }
  | { class: "mirror"; hash: string | null }
  | { class: "link"; hash: string | null };
/** The union and the shared RECORDED_CLASSES table name the same classes, both ways. */
export type RecordedClassesWritten = AssertNever<Exclude<RecordedClass, ManifestRecord["class"]>>;
export type WrittenClassesRecorded = AssertNever<Exclude<ManifestRecord["class"], RecordedClass>>;

export type Records = Record<string, ManifestEntryShape>;

export function sha256(data: Buffer | string): string {
  return createHash("sha256").update(data).digest("hex");
}

export function regionMarkers(kind: RegionKind): RegionMarkers {
  return kind === "hash" ? HASH_REGION_MARKERS : HTML_REGION_MARKERS;
}

/** The previous records: empty for a repository with no manifest yet, a
 *  problem string for one whose manifest cannot be trusted (the caller
 *  reports it and treats every file as unrecorded). */
export function readRecords(target: string): { records: Records; problem: string | null } {
  const bytes = existingFile(target, MANIFEST_NAME);
  if (bytes === null) return { records: {}, problem: null };
  const parsed = parseManifestFiles(bytes.toString("utf-8"));
  if (parsed.problem !== null)
    return { records: {}, problem: `${MANIFEST_NAME} ${parsed.problem}` };
  return { records: parsed.files, problem: null };
}

const HASH_RE = /^[0-9a-f]{64}$/;

/** The recorded sha256 for `path`, or null when the entry is missing, has
 *  no hash, or carries one the writer would never have written. */
export function recordedHash(records: Records, path: string): string | null {
  const hash = records[path]?.hash;
  return typeof hash === "string" && HASH_RE.test(hash) ? hash : null;
}

const COMMENT =
  "Generated by repo-platform - do not edit. Every platform-written path with its ownership " +
  "class: managed (rewritten whole; hash is sha256 of the last written content), split (the " +
  "BEGIN/END-bounded region is rewritten and the repository owns everything outside it; the " +
  "hash covers the region from the BEGIN line through the END line), starter (written once, " +
  "repo-owned from then on), mirror (a byte copy of a written file, declared in " +
  ".repo-platform.yml), link (a relative symbolic link; hash is sha256 of its target). This " +
  "file's own entry records the build commit that wrote the tree.";

/** The manifest text for `records` plus the self entry, entries sorted by path. */
export function renderManifest(records: Record<string, ManifestRecord>, build: string): string {
  const lines = Object.entries(records)
    .filter(([path]) => path !== MANIFEST_NAME)
    .map(([path, record]) => [path, entryBody(record as Record<string, JsonValue>)] as const);
  lines.push([MANIFEST_NAME, entryBody({ class: "managed", hash: null, commit: build })]);
  lines.sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return [
    "{",
    `  "$comment": ${JSON.stringify(COMMENT)},`,
    '  "files": {',
    lines.map(([path, body]) => `    ${JSON.stringify(path)}: ${body}`).join(",\n"),
    "  }",
    "}",
    "",
  ].join("\n");
}

export function writeManifest(
  target: string,
  records: Record<string, ManifestRecord>,
  build: string,
): void {
  writeFile(target, MANIFEST_NAME, Buffer.from(renderManifest(records, build)));
}
