// The literal on the right of every row is the byte the fleet carries today, never the constant re-spelled: a derived
// string that drifts (a renamed owner, a marker label built differently) fails here before any repository sees it.

import { describe, expect, test } from "bun:test";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { SYNC_IDENTITY } from "../../.github/scripts/shared/git_identity.ts";
import { prTitle } from "../../.github/scripts/sync/deliver.ts";
import { renderManifest } from "../../.github/scripts/sync/writer/manifest.ts";
import { RENDERED_HEADER } from "../../.github/scripts/sync/writer/settings_entry.ts";
import { HASH_REGION_MARKERS, HTML_REGION_MARKERS } from "../../actions/shared/grammar.ts";
import {
  AUTOMATION_BRANCH,
  DELIVERY_REF,
  FAILURE_ISSUE_TITLE,
  GENERATED_NOTICE,
  MANAGED_HEADER_PATTERN,
  MANAGED_REGION_LABEL,
  MANIFEST_NAME,
  PLATFORM_NAME,
  PLATFORM_OWNER,
  PLATFORM_SLUG,
  REGISTRATION_PATH,
  SYNC_BOT,
  SYNC_PR_TITLE_PREFIX,
} from "../../actions/shared/platform.ts";
import { boundedSpawnSync } from "../shared/bounded_spawn.ts";
import { tempDirs } from "../shared/temp_dir.ts";

const REPO_ROOT = resolve(import.meta.dir, "../..");
const PACKAGE_JSON = join(REPO_ROOT, "package.json");
const temp = tempDirs();

describe("the platform slug and every string the fleet observes derived from it", () => {
  test("each derived string is the byte the fleet carries today", () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, "utf-8")) as { name: string };
    expect({
      packageName: pkg.name,
      owner: PLATFORM_OWNER,
      name: PLATFORM_NAME,
      slug: PLATFORM_SLUG,
      registration: REGISTRATION_PATH,
      manifest: MANIFEST_NAME,
      regionLabel: MANAGED_REGION_LABEL,
      hashMarkers: HASH_REGION_MARKERS,
      htmlMarkers: HTML_REGION_MARKERS,
      generatedNotice: GENERATED_NOTICE,
      renderedSettingsHeader: RENDERED_HEADER,
      manifestComment: renderManifest({}).split("\n")[1],
      syncBot: SYNC_BOT,
      syncIdentity: SYNC_IDENTITY,
      automationBranch: AUTOMATION_BRANCH,
      failureIssueTitle: FAILURE_ISSUE_TITLE,
      syncPrTitlePrefix: SYNC_PR_TITLE_PREFIX,
      syncPrTitle: prTitle("0123456789abcdef0123456789abcdef01234567"),
      deliveryRef: DELIVERY_REF,
    }).toEqual({
      packageName: "repo-platform",
      owner: "Vivswan",
      name: "repo-platform",
      slug: "Vivswan/repo-platform",
      registration: ".repo-platform.yml",
      manifest: ".github/repo-platform-manifest.json",
      regionLabel: "REPO-PLATFORM MANAGED",
      hashMarkers: { begin: "# BEGIN REPO-PLATFORM MANAGED", end: "# END REPO-PLATFORM MANAGED" },
      htmlMarkers: {
        begin: "<!-- BEGIN REPO-PLATFORM MANAGED -->",
        end: "<!-- END REPO-PLATFORM MANAGED -->",
      },
      generatedNotice: "Generated by repo-platform - do not edit.",
      renderedSettingsHeader: "# Generated by repo-platform - do not edit.",
      manifestComment:
        '  "$comment": "Generated by repo-platform - do not edit. Every platform-written path with its ownership ' +
        "class: managed (rewritten whole; hash is sha256 of the last written content), split (the " +
        "BEGIN/END-bounded region is rewritten and the repository owns everything outside it; the " +
        "hash covers the region from the BEGIN line through the END line), starter (written once, " +
        "repo-owned from then on), mirror (a byte copy of a written file, or with kind symlink a " +
        "relative symbolic link to it whose hash is sha256 of the link target, declared in files.yml or " +
        '.repo-platform.yml).",',
      syncBot: "repo-platform-sync",
      syncIdentity: {
        name: "repo-platform-sync",
        email: "repo-platform-sync@users.noreply.github.com",
      },
      automationBranch: "automation/repo-platform",
      failureIssueTitle: "[repo-platform] sync failed",
      syncPrTitlePrefix: "chore: sync repo-platform build",
      syncPrTitle: "chore: sync repo-platform build 0123456789ab",
      deliveryRef: "stable",
    });
  });

  // The rendered header names the owner in whichever case the writer substituted; the placeholder form in files/ is
  // source, not a managed file, so it must not count.
  test.each([
    ["# This file is managed by Vivswan/repo-platform.", true],
    ["<!-- This file is managed by vivswan/repo-platform -->", true],
    ["# This file is managed by {{github_username}}/repo-platform.", false],
    ["# This file is managed by Vivswan/repo-platformer.", false],
    ["# managed by Vivswan/repo-platform", false],
  ])("the managed header pattern on %j", (line, matches) => {
    expect(MANAGED_HEADER_PATTERN.test(line)).toBe(matches);
  });
});

/** Every plugin biome.json names, so a copied config resolves them beside it. */
function biomePlugins(repoRoot: string): Record<string, string> {
  return Object.fromEntries(
    readdirSync(join(repoRoot, "biome"))
      .filter((name) => name.endsWith(".grit"))
      .map((name) => [`biome/${name}`, readFileSync(join(repoRoot, "biome", name), "utf-8")]),
  );
}

// The ban that keeps the name above the one spelling: Biome's plugin over every code tree but the tests and platform.ts itself.
describe("the biome ban on platform-name literals", () => {
  test("a string, a template, and a regex literal each red under actions/, scripts/, and .github/scripts/; a test file and platform.ts are exempt", () => {
    const lintRoot = temp.dir("platform-name-ban-");
    const config = JSON.parse(readFileSync(join(REPO_ROOT, "biome.json"), "utf-8"));
    const literals = [
      'export const branch = "automation/repo-platform";',
      "export const title = `[${branch}] Repo-Platform`;",
      "export const managed = /REPO-PLATFORM MANAGED/;",
      'export const fine = "another-platform";',
      "",
    ].join("\n");
    const files: Record<string, string> = {
      "biome.json": JSON.stringify({ ...config, vcs: { enabled: false } }),
      ...biomePlugins(REPO_ROOT),
      "actions/x/x.ts": literals,
      "scripts/x.ts": literals,
      ".github/scripts/x.ts": literals,
      "actions/x/x.test.ts": literals,
      "actions/shared/platform.ts": literals,
      "tests/x.ts": literals,
    };
    for (const [rel, content] of Object.entries(files)) {
      mkdirSync(dirname(join(lintRoot, rel)), { recursive: true });
      writeFileSync(join(lintRoot, rel), content);
    }
    const r = boundedSpawnSync(
      [join(REPO_ROOT, "node_modules", ".bin", "biome"), "lint", "--reporter=json", "."],
      { cwd: lintRoot },
    );
    const report = JSON.parse(r.stdout) as {
      diagnostics: { category: string; location: { path: string; start: { line: number } } }[];
    };
    const seen = report.diagnostics
      .filter((d) => d.category === "plugin")
      .map((d) => `${d.location.path}:${d.location.start.line}`)
      .sort();
    expect(seen).toEqual(
      [".github/scripts/x.ts", "actions/x/x.ts", "scripts/x.ts"]
        .flatMap((file) => [1, 2, 3].map((line) => `${file}:${line}`))
        .sort(),
    );
  });
});
