// The literal on the right of every row is the byte the fleet carries today, never the constant re-spelled: a derived
// string that drifts (a renamed owner, a marker label built differently) fails here before any repository sees it.

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { BUILD_IDENTITY, SYNC_IDENTITY } from "../../.github/scripts/shared/git_identity.ts";
import { prTitle } from "../../.github/scripts/sync/deliver.ts";
import { renderManifest } from "../../.github/scripts/sync/writer/manifest.ts";
import { RENDERED_HEADER } from "../../.github/scripts/sync/writer/settings_entry.ts";
import { HASH_REGION_MARKERS, HTML_REGION_MARKERS } from "../../actions/shared/grammar.ts";
import {
  AUTOMATION_BRANCH,
  BUILD_BOT,
  FAILURE_ISSUE_TITLE,
  GENERATED_NOTICE,
  MANAGED_HEADER_PATTERN,
  MANAGED_REGION_LABEL,
  MANIFEST_NAME,
  PLATFORM_NAME,
  PLATFORM_OWNER,
  PLATFORM_SLUG,
  REGISTRATION_PATH,
  SYNC_BOT,
  SYNC_PR_TITLE_PREFIX,
  stickyCommentHeader,
} from "../../actions/shared/platform.ts";
import { CI_WORKSPACE_SECTION, PLATFORM_SECTIONS } from "../../scripts/generate/build_gitignore.ts";

const PACKAGE_JSON = resolve(import.meta.dir, "../../package.json");

describe("the platform slug and every string the fleet observes derived from it", () => {
  test("each derived string is the byte the fleet carries today", () => {
    const pkg = JSON.parse(readFileSync(PACKAGE_JSON, "utf-8")) as { name: string };
    expect({
      packageName: pkg.name,
      owner: PLATFORM_OWNER,
      name: PLATFORM_NAME,
      slug: PLATFORM_SLUG,
      registration: REGISTRATION_PATH,
      manifest: MANIFEST_NAME,
      regionLabel: MANAGED_REGION_LABEL,
      hashMarkers: HASH_REGION_MARKERS,
      htmlMarkers: HTML_REGION_MARKERS,
      generatedNotice: GENERATED_NOTICE,
      renderedSettingsHeader: RENDERED_HEADER,
      manifestComment: renderManifest({}, "0123456789abcdef0123456789abcdef01234567").split(
        "\n",
      )[1],
      gitignoreCiSection: CI_WORKSPACE_SECTION,
      gitignoreFuzzerSection: PLATFORM_SECTIONS.fuzzer,
      syncBot: SYNC_BOT,
      buildBot: BUILD_BOT,
      syncIdentity: SYNC_IDENTITY,
      buildIdentity: BUILD_IDENTITY,
      automationBranch: AUTOMATION_BRANCH,
      failureIssueTitle: FAILURE_ISSUE_TITLE,
      syncPrTitlePrefix: SYNC_PR_TITLE_PREFIX,
      syncPrTitle: prTitle("0123456789abcdef0123456789abcdef01234567"),
      stickyHeader: stickyCommentHeader("check-file-size"),
    }).toEqual({
      packageName: "repo-platform",
      owner: "Vivswan",
      name: "repo-platform",
      slug: "Vivswan/repo-platform",
      registration: ".repo-platform.yml",
      manifest: ".github/repo-platform-manifest.json",
      regionLabel: "REPO-PLATFORM MANAGED",
      hashMarkers: { begin: "# BEGIN REPO-PLATFORM MANAGED", end: "# END REPO-PLATFORM MANAGED" },
      htmlMarkers: {
        begin: "<!-- BEGIN REPO-PLATFORM MANAGED -->",
        end: "<!-- END REPO-PLATFORM MANAGED -->",
      },
      generatedNotice: "Generated by repo-platform - do not edit.",
      renderedSettingsHeader: "# Generated by repo-platform - do not edit.",
      manifestComment:
        '  "$comment": "Generated by repo-platform - do not edit. Every platform-written path with its ownership ' +
        "class: managed (rewritten whole; hash is sha256 of the last written content), split (the " +
        "BEGIN/END-bounded region is rewritten and the repository owns everything outside it; the " +
        "hash covers the region from the BEGIN line through the END line), starter (written once, " +
        "repo-owned from then on), mirror (a byte copy of a written file, or with kind symlink a " +
        "relative symbolic link to it whose hash is sha256 of the link target, declared in " +
        ".repo-platform.yml), link (a relative symbolic link; hash is sha256 of its target). This " +
        "file's own entry records the build commit that wrote the tree.\",",
      gitignoreCiSection: "## CI workspace paths (repo-platform)\n/results.sarif\n",
      gitignoreFuzzerSection:
        "## Fuzzer workspace paths (repo-platform fuzzer)\n/.fuzz-failures/\n",
      syncBot: "repo-platform-sync",
      buildBot: "repo-platform-build",
      syncIdentity: {
        name: "repo-platform-sync",
        email: "repo-platform-sync@users.noreply.github.com",
      },
      buildIdentity: {
        name: "repo-platform-build",
        email: "repo-platform-build@users.noreply.github.com",
      },
      automationBranch: "automation/repo-platform",
      failureIssueTitle: "[repo-platform] sync failed",
      syncPrTitlePrefix: "chore: sync repo-platform build",
      syncPrTitle: "chore: sync repo-platform build 0123456789ab",
      stickyHeader: "repo-platform/check-file-size",
    });
  });

  // The rendered header names the owner in whichever case the writer substituted; the placeholder form in files/ is
  // source, not a managed file, so it must not count.
  test.each([
    ["# This file is managed by Vivswan/repo-platform.", true],
    ["<!-- This file is managed by vivswan/repo-platform -->", true],
    ["# This file is managed by {{github_username}}/repo-platform.", false],
    ["# This file is managed by Vivswan/repo-platformer.", false],
    ["# managed by Vivswan/repo-platform", false],
  ])("the managed header pattern on %j", (line, matches) => {
    expect(MANAGED_HEADER_PATTERN.test(line)).toBe(matches);
  });
});
