import { readFileSync } from "node:fs";
import { join } from "node:path";
import { substringCount } from "../../shared/grammar.ts";
import type { Context } from "../context.ts";
import { error, type Finding } from "../findings.ts";
import { ungatedBaseRegionPaths } from "../ownership.ts";
import { isRegularFile } from "../readers.ts";

/** Managed-region markers exactly once and in order, for every region
 *  file the roster expects on this render. Ungated BASE region files are
 *  always generated by the template, so their ABSENCE is damage and
 *  errors; a missing gated or module region file is the manifest parity
 *  check's report. Counting is SUBSTRING semantics on purpose: a buried
 *  mention of a region marker is a duplicate by the fleet-wide region
 *  convention (the sync's appendix neutralization and the region slicer
 *  count the same way), and order is checked too - counting alone would
 *  pass a swapped BEGIN/END pair. Repo-owned content above BEGIN and below
 *  END is legal and unchecked. */
export function checkSplitMarkers(ctx: Context): Finding[] {
  const findings: Finding[] = [];
  const alwaysGenerated = ungatedBaseRegionPaths();
  for (const entry of ctx.ownership) {
    if (entry.kind !== "region") continue;
    const path = join(ctx.root, entry.path);
    if (!isRegularFile(path)) {
      if (alwaysGenerated.has(entry.path)) {
        findings.push(
          error(
            `${entry.path} is missing - the template always generates it, so the repo ` +
              "is damaged; restore the file from git history or run a template sync",
          ),
        );
      }
      continue;
    }
    // latin1 for byte fidelity, like the stamper and the sync rebuild: a
    // UTF-8 decode folds invalid sequences onto the replacement character,
    // which could mask or invent marker text.
    const content = readFileSync(path).toString("latin1");
    let exactlyOnce = true;
    for (const marker of [entry.begin, entry.end]) {
      const count = substringCount(content, marker);
      if (count !== 1) {
        exactlyOnce = false;
        findings.push(
          error(
            `${entry.path}: marker '${marker}' appears ${count} times (expected 1) - ` +
              "a merge or manual edit broke the managed region; restore one " +
              "BEGIN/END marker pair via a template sync",
          ),
        );
      }
    }
    if (exactlyOnce && content.indexOf(entry.end) <= content.indexOf(entry.begin)) {
      findings.push(
        error(
          `${entry.path}: the BEGIN/END managed-region markers appear out of order - ` +
            "the region runs BEGIN through END; restore the order via a template sync",
        ),
      );
    }
  }
  return findings;
}
