
      - uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          components: clippy, rustfmt
      - name: Fetch dependencies (cargo)
        run: cargo fetch --locked
