// The split declarations: reading them from a manifest (splitEntries) and
// the template sources that must carry each declared marker pair once.

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { splitEntries } from "../../../.github/scripts/sync/preserve_local_content.ts";
import { B, E, HB, HE, repoRoot } from "./fixtures";

describe("splitEntries", () => {
  const regionEntry = (over: Record<string, unknown> = {}) => ({
    class: "split",
    grammar: "managed-region",
    begin: B,
    end: E,
    hash: null,
    ...over,
  });

  test("returns the split entries with the grammar's declaration shape", () => {
    const manifest = JSON.stringify({
      files: {
        "AGENTS.md": regionEntry(),
        ".gitignore": regionEntry({ begin: HB, end: HE }),
        ".github/workflows/ci.yml": { class: "managed", hash: null },
        ".github/workflows/checks.yml": { class: "starter" },
      },
    });
    expect(splitEntries(manifest, "m")).toEqual([
      { path: "AGENTS.md", grammar: "managed-region", begin: B, end: E },
      { path: ".gitignore", grammar: "managed-region", begin: HB, end: HE },
    ]);
  });

  test("throws on a split entry with no grammar (a grammar-less manifest)", () => {
    const manifest = JSON.stringify({
      files: { "AGENTS.md": { class: "split", begin: B, end: E, hash: null } },
    });
    expect(() => splitEntries(manifest, "m")).toThrow("declares no grammar");
  });

  test("throws on an unknown grammar instead of degrading", () => {
    // The fresh render's manifest is generated by this change's own
    // compose, so any other grammar is damage, never a shape to read.
    for (const grammar of ["prefix", "one-marker", "four-marker"]) {
      const manifest = JSON.stringify({
        files: { "AGENTS.md": regionEntry({ grammar }) },
      });
      expect(() => splitEntries(manifest, "m")).toThrow(`unknown grammar "${grammar}"`);
    }
  });

  test("throws on a missing or non-ASCII marker string", () => {
    const missing = JSON.stringify({
      files: { "AGENTS.md": { class: "split", grammar: "managed-region", begin: B, hash: null } },
    });
    expect(() => splitEntries(missing, "m")).toThrow("printable-ASCII");
    const nonAscii = JSON.stringify({
      files: { "AGENTS.md": regionEntry({ begin: "# local § begin" }) },
    });
    expect(() => splitEntries(nonAscii, "m")).toThrow("printable-ASCII");
  });

  test("throws on a split path that could escape the target root", () => {
    for (const path of ["../victim", "a/../../victim", "/etc/victim", "a//b"]) {
      const manifest = JSON.stringify({ files: { [path]: regionEntry() } });
      expect(() => splitEntries(manifest, "m")).toThrow("not a clean relative path");
    }
  });

  test("throws on non-JSON input and on a files-less document", () => {
    expect(() => splitEntries("not json", "m")).toThrow("does not parse as a manifest");
    expect(() => splitEntries("{}", "m")).toThrow("no top-level 'files' mapping");
  });

  test("a duplicated key throws instead of last-win laundering", () => {
    // Raw JSON.parse keeps the LAST value silently: a duplicated class
    // field would declassify a split entry out of every carry with no
    // error. The shared parser rejects the duplicate before any read.
    const doubled = '{"files": {"AGENTS.md": {"class": "split", "class": "starter"}}}';
    expect(() => splitEntries(doubled, "m")).toThrow("binds a key more than once");
  });

  test("an array-shaped files value fails loud, never open", () => {
    // '"files": []' passes `typeof === "object"` and would yield ZERO
    // entries - every carry would silently skip after recopy already
    // overwrote local content.
    expect(() => splitEntries('{"files": []}', "m")).toThrow("no top-level 'files' mapping");
    const arrayEntry = JSON.stringify({ files: { "AGENTS.md": [] } });
    expect(() => splitEntries(arrayEntry, "m")).toThrow("is not an object");
  });

  // The appendix writes comments in the markers' syntax, and the manifest
  // text is attacker-adjacent at this boundary: it is whatever the target
  // repo's stamped file claims, so the one-comment rule has to hold here
  // and not just at declaration time.
  test.each([
    { reason: "a non-comment marker", begin: "// begin managed" },
    { reason: "two HTML comments on one marker", begin: "<!-- closed --> active <!-- final -->" },
    { reason: "a degenerate HTML opener", begin: "<!-->" },
  ])("throws on a marker that is not one hash or HTML comment: $reason", ({ begin }) => {
    const manifest = JSON.stringify({ files: { "AGENTS.md": regionEntry({ begin }) } });
    expect(() => splitEntries(manifest, "m")).toThrow(
      "not a hash comment or a complete HTML comment",
    );
  });

  test("throws on markers that contain each other (substring counting)", () => {
    const manifest = JSON.stringify({
      files: { "AGENTS.md": regionEntry({ begin: "# MANAGED", end: "# MANAGED END" }) },
    });
    expect(() => splitEntries(manifest, "m")).toThrow("substring-free");
  });
});

// Every split template source must carry its declared BEGIN/END markers
// exactly once, in order - the composer enforces this via
// declarationTextErrors; this is the fast regression net for the template
// files themselves.
describe("split templates carry one ordered marker pair", () => {
  test("each split source has BEGIN before END, each exactly once", () => {
    const templatesDir = join(repoRoot, "templates");
    const templated: [string, string, string][] = [
      [
        join(
          templatesDir,
          "base",
          "{% if 'custom-license' not in modules %}LICENSE.md{% endif %}.jinja",
        ),
        B,
        E,
      ],
      [join(templatesDir, "base", ".gitattributes.jinja"), HB, HE],
      [join(templatesDir, "base", ".editorconfig.jinja"), HB, HE],
      [join(templatesDir, "base", ".github", "CODEOWNERS.jinja"), HB, HE],
      [join(templatesDir, "base", ".gitignore.jinja"), HB, HE],
      [join(templatesDir, "base", "AGENTS.md.jinja"), B, E],
    ];
    for (const [path, begin, end] of templated) {
      const source = readFileSync(path, "utf-8");
      expect(source.split(begin).length).toBe(2);
      expect(source.split(end).length).toBe(2);
      expect(source.indexOf(begin)).toBeLessThan(source.indexOf(end));
    }
  });
});
