import { describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  ALLOWLIST_FILE,
  COMMENT_CAPS,
  COMMENT_MARKER,
  type CommentScope,
  check,
  classify,
  describe as describeFinding,
  type Finding,
  HARD,
  isGenerated,
  isLiteralLine,
  isManaged,
  isUnbreakable,
  judgeFile,
  type Kind,
  type Outcome,
  parseAllowlist,
  parseArgs,
  REASON_RULE,
  report,
  type Tier,
  type Verdict,
  WARN,
} from "../../../actions/check-file-size/check-file-size.ts";
import { boundedSpawnSync } from "../../shared/bounded_spawn.ts";
import { tempDirs } from "../../shared/temp_dir.ts";

const temp = tempDirs();
const ACTION_DIR = resolve(import.meta.dir, "../../../actions/check-file-size");
const SCRIPT = join(ACTION_DIR, "check-file-size.ts");
const REPO_ROOT = resolve(import.meta.dir, "../../..");

function git(root: string, ...args: string[]): void {
  const proc = boundedSpawnSync(["git", "-C", root, ...args]);
  if (proc.exitCode !== 0) throw new Error(`git ${args.join(" ")}: ${proc.stderr}`);
}

/** A git checkout holding `tracked` (added to the index) and `untracked`
 *  (on disk only). */
function checkout(tracked: Record<string, string>, untracked: Record<string, string> = {}): string {
  const root = temp.dir("check-file-size-");
  git(root, "init", "-q");
  for (const [rel, text] of Object.entries({ ...tracked, ...untracked })) {
    mkdirSync(dirname(join(root, rel)), { recursive: true });
    writeFileSync(join(root, rel), text);
  }
  git(root, "add", "-A", ...Object.keys(tracked));
  return root;
}

const lines = (count: number): string => `${Array.from({ length: count }, () => "x").join("\n")}\n`;
const MANAGED = "# This file is managed by Vivswan/repo-platform.\n";

describe("classify", () => {
  test.each<[string, Kind | null]>([
    ["src/app.ts", "source"],
    ["src/App.tsx", "source"],
    ["src/app.mts", "source"],
    ["lib/util.cjs", "source"],
    ["pkg/types.pyi", "source"],
    ["lib/mod.rs", "source"],
    ["Main.java", "source"],
    ["include/x.h", "source"],
    ["src/app.test.ts", "test"],
    ["src/widget.spec.ts", "test"],
    ["pkg/foo_test.go", "test"],
    ["spec/foo_spec.rb", null],
    ["test_module.py", "test"],
    ["tests/helper.ts", "test"],
    ["test/helpers/fixtures.ts", "test"],
    ["src/__tests__/util.js", "test"],
    ["src/policy/store_tests.rs", "test"],
    ["src/policy/tests.rs", "test"],
    ["src/proptests.rs", "test"],
    ["src/tests_util.rs", "source"],
    ["src/large.cc", "source"],
    ["include/x.hpp", "source"],
    ["src/a.cxx", "source"],
    ["include/b.hh", "source"],
    ["src/testing/util.ts", "source"],
    [".github/workflows/ci.yml", "workflow"],
    [".github/workflows/ci.yaml", "workflow"],
    ["actions/check/action.yml", "workflow"],
    ["action.yml", "workflow"],
    [".github/workflows/nested/x.yml", null],
    ["config/settings.yml", null],
    ["scripts/run.sh", "shell"],
    ["bin/setup.bash", "shell"],
    [".zshrc.zsh", "shell"],
    ["README.md", "markdown"],
    ["docs/guide.md", "markdown"],
    ["package.json", null],
    ["bun.lock", null],
    ["logo.png", null],
    ["Makefile", null],
    ["node_modules/pkg/index.js", null],
    ["vendor/lib.go", null],
    ["tests/golden-renders/minimal/README.md", null],
    ["src/__snapshots__/app.test.ts", null],
  ])("%s -> %s", (path, kind) => {
    expect(classify(path)).toBe(kind);
  });
});

describe("isGenerated / isManaged", () => {
  test.each<[string, string, boolean, boolean]>([
    [
      "generated by",
      "# Generated by Powerlevel10k configuration wizard on 2026-02-23.\nx\n",
      true,
      false,
    ],
    ["auto-generated", "// auto-generated, see the build\nx\n", true, false],
    ["autogenerated", "// AUTOGENERATED FILE\nx\n", true, false],
    ["this file is generated", "/* This file is generated. */\nx\n", true, false],
    ["do not edit", "# DO NOT EDIT - built from the manifests\nx\n", true, false],
    ["generated file", "<!-- generated file -->\nx\n", true, false],
    ["the repo's own generator", "// Regions rewritten by scripts/generate.ts\nx\n", true, false],
    ["a marker on the tenth line", `${lines(9)}// generated by x\n`, true, false],
    ["the managed header is managed, not generated", `${MANAGED}x\n`, false, true],
    [
      "a managed header with a dotted owner",
      "# This file is managed by a.b-c/repo-platform.\n",
      false,
      true,
    ],
    ["a string literal is not a header", 'const label = "do not edit";\n', false, false],
    [
      "prose using the word generate",
      "// Copies GENERATED from the manifests are NOT compared\nx\n",
      false,
      false,
    ],
    ["a marker past the header window", `${lines(10)}// generated by x\n`, false, false],
    ["a python docstring header", '"""Generated by foo."""\nx\n', true, false],
    ["a single-quoted docstring header", "'''Generated by foo.'''\nx\n", true, false],
    ["a bare string literal is not a comment", '"do not edit";\nx\n', false, false],
    [
      "a managed sentence in a string literal is not a header",
      'const note = "This file is managed by acme/repo-platform";\n',
      false,
      false,
    ],
    ["no header", "const x = 1;\n", false, false],
  ])("%s", (_name, text, generated, managed) => {
    expect([isGenerated(text), isManaged(text)]).toEqual([generated, managed]);
  });
});

describe("judgeFile line counts", () => {
  const kinds: Kind[] = ["source", "test", "workflow", "shell", "markdown"];
  // A 50-line matched generated region rides along in every fixture and
  // never counts; the same fixtures without it would judge identically.
  const region = `# BEGIN GENERATED: x\n${lines(48)}# END GENERATED: x\n`;
  test.each(kinds)("%s: at each cap passes, one over lands in that tier", (kind) => {
    const hard = HARD.lines[kind];
    const warn = WARN.lines[kind];
    const path = `file.${kind}`;
    expect(judgeFile(path, kind, `${region}${lines(warn)}`)).toEqual([]);
    expect(judgeFile(path, kind, `${lines(warn + 1)}${region}`)).toEqual([
      { path, kind, tier: "warn", measure: "lines", value: warn + 1, cap: warn },
    ]);
    expect(judgeFile(path, kind, `${region}${lines(hard)}`)).toEqual([
      { path, kind, tier: "warn", measure: "lines", value: hard, cap: warn },
    ]);
    expect(judgeFile(path, kind, `${lines(hard + 1)}${region}`)).toEqual([
      { path, kind, tier: "hard", measure: "lines", value: hard + 1, cap: hard },
    ]);
  });

  test("an unmatched BEGIN GENERATED fences nothing (control); both markers on one line fence that line", () => {
    const cap = HARD.lines.source;
    const finding = (value: number): Finding => ({
      path: "a.ts",
      kind: "source",
      tier: "hard",
      measure: "lines",
      value,
      cap,
    });
    expect(judgeFile("a.ts", "source", `// BEGIN GENERATED: x\n${lines(cap)}`)).toEqual([
      finding(cap + 1),
    ]);
    // The warn boundary, where one uncounted marker line decides.
    expect(
      judgeFile(
        "a.ts",
        "source",
        `// BEGIN GENERATED: x END GENERATED: x\n${lines(WARN.lines.source)}`,
      ),
    ).toEqual([]);
    expect(
      judgeFile("a.ts", "source", `// BEGIN GENERATED: x END GENERATED: x\n${lines(cap + 1)}`),
    ).toEqual([finding(cap + 1)]);
  });

  test("a missing trailing newline still counts the last line; a trailing newline adds none", () => {
    const cap = HARD.lines.source;
    const finding = (tier: Tier, value: number, over: number): Finding => ({
      path: "a.ts",
      kind: "source",
      tier,
      measure: "lines",
      value,
      cap: over,
    });
    const body = Array.from({ length: cap + 1 }, () => "x").join("\n");
    expect(judgeFile("a.ts", "source", body)).toEqual([finding("hard", cap + 1, cap)]);
    expect(judgeFile("a.ts", "source", lines(cap))).toEqual([
      finding("warn", cap, WARN.lines.source),
    ]);
  });
});

describe("judgeFile line width", () => {
  const wide = (width: number, tokens = 4): string => {
    const each = Math.floor(width / tokens);
    return Array.from({ length: tokens }, (_, i) =>
      "a".repeat(each - (i < tokens - 1 ? 1 : 0)),
    ).join(" ");
  };
  /** Expected rows as [tier, line, width, cap]; expanded to whole width
   *  findings on "f" before comparing. */
  const widthFinding = (kind: Kind, [tier, line, value, cap]: (Tier | number)[]): Finding => ({
    path: "f",
    kind,
    tier: tier as Tier,
    measure: "width",
    line: line as number,
    value: value as number,
    cap: cap as number,
  });

  test.each<[string, Kind, string, (Tier | number)[][]]>([
    ["a breakable line over the hard cap", "source", `${wide(300)}\n`, [["hard", 1, 300, 256]]],
    [
      "a breakable line over the warn cap only",
      "source",
      `${wide(232)}\n`,
      [["warn", 1, 232, WARN.width]],
    ],
    ["a line at the warn cap", "source", `${"a".repeat(WARN.width - 2)} b\n`, []],
    ["a CRLF line at the warn cap", "source", `${"a".repeat(WARN.width - 2)} b\r\n`, []],
    ["a single unbreakable token over the hard cap", "source", `${"u".repeat(300)}\n`, []],
    ["an indented single token over the hard cap", "source", `    ${"u".repeat(300)}\n`, []],
    [
      "a literal assigned on one line is two tokens and fails (control for the single-token rule)",
      "source",
      `const x = "${"a".repeat(280)}";\n`,
      [["hard", 1, 293, 256]],
    ],
    [
      "an unmatched BEGIN GENERATED fences no width either",
      "source",
      `// BEGIN GENERATED: x\n${wide(300)}\n`,
      [["hard", 2, 300, 256]],
    ],
    [
      "a key with a wide value is two tokens and fails",
      "workflow",
      `  run: ${"u".repeat(300)}
`,
      [["hard", 1, 307, 256]],
    ],
    [
      "a line over the warn cap with one wide token among others still warns",
      "shell",
      `echo ${"u".repeat(190)} ${"v".repeat(30)}
`,
      [["warn", 1, 226, WARN.width]],
    ],
    [
      "a wide line inside a generated region, then the same line outside it",
      "source",
      `// BEGIN GENERATED: x\n${wide(300)}\n// END GENERATED: x\n${wide(300)}\n`,
      [["hard", 4, 300, 256]],
    ],
    ["markdown prose has no width cap", "markdown", `${wide(1000)}\n`, []],
    [
      "width counts code points, not bytes",
      "source",
      `${wide(232).replace(/a/g, "é")}\n`,
      [["warn", 1, 232, WARN.width]],
    ],
    [
      "a warn-wide line that is one assigned string literal",
      "source",
      `const x = "${"a ".repeat(115)}";\n`,
      [],
    ],
    [
      "a warn-wide line that is one returned literal",
      "source",
      `  return '${"a ".repeat(115)}';\n`,
      [],
    ],
    [
      "a warn-wide keyed literal with a trailing comma",
      "source",
      `  key: \`${"a ".repeat(115)}\`,\n`,
      [],
    ],
    ["a warn-wide bash assignment", "shell", `msg="${"a ".repeat(115)}"\n`, []],
    ["a warn-wide concatenation piece", "source", `  "${"a ".repeat(115)}" +\n`, []],
    ["a warn-wide regex literal", "test", `const re = /${"a ".repeat(115)}/i;\n`, []],
    [
      "a hard-wide assigned literal is still a hard finding",
      "source",
      `const x = "${"a ".repeat(150)}";\n`,
      [["hard", 1, 313, 256]],
    ],
    [
      "a warn-wide literal beside other code (control)",
      "source",
      `  foo("${"a ".repeat(115)}", bar);\n`,
      [["warn", 1, 245, WARN.width]],
    ],
    ["a warn-wide python raw literal", "source", `pattern = r"${"a ".repeat(115)}"\n`, []],
    [
      "both markers on one line fence that line alone",
      "source",
      `// BEGIN GENERATED: x ${wide(300)} END GENERATED: x\n${wide(300)}\n`,
      [["hard", 2, 300, 256]],
    ],
  ])("%s", (_name, kind, text, expected) => {
    expect(judgeFile("f", kind, text)).toEqual(expected.map((row) => widthFinding(kind, row)));
  });
});

describe("isLiteralLine", () => {
  test("pathological inputs finish in linear time (the regex form took seconds at 100k)", () => {
    const cases: [string, boolean][] = [
      [`\`\`${" ".repeat(100_000)}x`, false],
      [`\`\`${" ".repeat(100_000)}`, true],
      ["`".repeat(100_000), false],
      [`const x = "${"a ".repeat(50_000)}";${" ".repeat(50_000)}`, true],
    ];
    const started = performance.now();
    expect(cases.map(([line]) => isLiteralLine(line))).toEqual(cases.map(([, ok]) => ok));
    expect(performance.now() - started).toBeLessThan(1000);
  });

  // Each line is warn-wide (WARN.width < width <= HARD.width) and
  // breakable; a literal line yields no finding, anything else the whole
  // warn width finding.
  const F = "a ".repeat(110).trim();
  test.each<[string, string, boolean]>([
    ["a typed exported declaration", `export const x: Readonly<T[]> = "${F}";`, true],
    ["a template with a trailing comma", `let x = \`${F}\`,`, true],
    ["a returned regex with flags", `  return /${F}/gi`, true],
    ["a keyed literal with trailers", `key: '${F}')]`, true],
    ["a += assignment", `obj.key += "${F}"`, true],
    ["a python raw bytes prefix", `rb"${F}"`, true],
    ["an escaped quote inside", `"esc\\"aped ${F}"`, true],
    ["an escaped slash inside a regex", `/a\\/b ${F}/`, true],
    ["two literals joined on one line", `'${F}' + 'b'`, false],
    ["an unclosed literal", `const x = "unclosed ${F}`, false],
    ["a three-letter prefix", `rbx"${F}"`, false],
    ["a prefixed template", `r\`${F}\``, false],
    ["a comment (an empty regex body is no literal)", `// ${F}`, false],
    ["a literal followed by code", `const x = "${F}" x`, false],
  ])("%s", (_name, line, literal) => {
    const width = [...line].length;
    expect(width).toBeGreaterThan(WARN.width);
    expect(width).toBeLessThanOrEqual(HARD.width);
    const finding: Finding = {
      path: "f",
      kind: "source",
      tier: "warn",
      measure: "width",
      line: 1,
      value: width,
      cap: WARN.width,
    };
    expect(judgeFile("f", "source", `${line}\n`)).toEqual(literal ? [] : [finding]);
  });
});

describe("judgeFile comment blocks", () => {
  const { block: BLOCK, header: HEADER } = COMMENT_CAPS;
  const slashes = (count: number): string =>
    `${Array.from({ length: count }, (_, i) => `// c${i}`).join("\n")}\n`;
  const hashes = (count: number): string =>
    `${Array.from({ length: count }, (_, i) => `# c${i}`).join("\n")}\n`;
  /** A `/* ... *\/` comment of `count` lines including both delimiter lines. */
  const starred = (count: number, open = "/*"): string =>
    `${open}\n${Array.from({ length: count - 2 }, (_, i) => ` * c${i}`).join("\n")}\n */\n`;
  /** Expected rows: an over-cap block, or a bare marker line; every comment
   *  finding is a warning, so the tier is implied and the cap follows the
   *  scope. */
  type Row = [line: number, length: number, scope: CommentScope] | [marker: number];
  const commentFinding = (path: string, kind: Kind, row: Row): Finding =>
    row.length === 1
      ? { path, kind, tier: "warn", measure: "marker", line: row[0] }
      : {
          path,
          kind,
          tier: "warn",
          measure: "comment",
          line: row[0],
          value: row[1],
          cap: COMMENT_CAPS[row[2]],
          scope: row[2],
        };

  test("the caps: one warn-only tier per scope", () => {
    expect(COMMENT_CAPS).toEqual({ block: 8, header: 20 });
  });

  // Every case names its file, since the comment syntax follows the extension.
  test.each<[string, string, string, Row[]]>([
    ["a block at the cap passes", "f.ts", `x\n\n${slashes(BLOCK)}x\n`, []],
    [
      "a block one over the cap warns",
      "f.ts",
      `x\n\n${slashes(BLOCK + 1)}x\n`,
      [[3, BLOCK + 1, "block"]],
    ],
    [
      "a block far over the cap still only warns",
      "f.ts",
      `x\n\n${slashes(50)}x\n`,
      [[3, 50, "block"]],
    ],
    ["a header at the cap passes", "f.ts", `${slashes(HEADER)}x\n`, []],
    [
      "a header one over the cap warns",
      "f.ts",
      `${slashes(HEADER + 1)}x\n`,
      [[1, HEADER + 1, "header"]],
    ],
    [
      "a header after a shebang is still the header, and the shebang does not count",
      "f.ts",
      `#!/usr/bin/env bun\n${slashes(HEADER + 1)}x\n`,
      [[2, HEADER + 1, "header"]],
    ],
    [
      "a header after a shebang and a blank line",
      "f.sh",
      `#!/bin/sh\n\n${hashes(HEADER + 1)}echo x\n`,
      [[3, HEADER + 1, "header"]],
    ],
    [
      "a shebang alone is no comment block (control)",
      "f.sh",
      `#!/bin/sh\n${hashes(HEADER)}echo x\n`,
      [],
    ],
    [
      "a shebang with a space before the path is still a shebang",
      "f.py",
      `#! /usr/bin/env python3\n${hashes(HEADER + 1)}x = 1\n`,
      [[2, HEADER + 1, "header"]],
    ],
    [
      "a Rust inner attribute on line 1 is code, not a shebang",
      "f.rs",
      `#![allow(dead_code)]\n${slashes(BLOCK + 1)}pub fn f() {}\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a header past the block cap but under the header cap passes; the same block after code is judged as a block",
      "f.ts",
      `${slashes(BLOCK + 1)}x\n\n${slashes(BLOCK + 1)}x\n`,
      [[BLOCK + 4, BLOCK + 1, "block"]],
    ],
    [
      "a second block before any code is a block, not a header",
      "f.ts",
      `${slashes(2)}\n${slashes(BLOCK + 1)}x\n`,
      [[4, BLOCK + 1, "block"]],
    ],
    [
      "a /* */ block spanning lines counts every line, delimiters included",
      "f.ts",
      `x\n${starred(BLOCK + 1)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a JSDoc block is a block",
      "f.mts",
      `x\n${starred(BLOCK + 1, "/**")}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a blank line inside a /* */ comment does not split it",
      "f.js",
      `x\n/*\n${"a\n\nb\n".repeat(3)}*/\nx\n`,
      [[2, 11, "block"]],
    ],
    [
      "a // run flowing into a /* */ block is one block",
      "f.ts",
      `x\n${slashes(BLOCK)}${starred(3)}x\n`,
      [[2, BLOCK + 3, "block"]],
    ],
    [
      "a closing delimiter followed by code is a code line: the block ends before it",
      "f.ts",
      `x\n/*\n${"a\n".repeat(BLOCK)}*/ y();\n${slashes(BLOCK)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a closing delimiter followed by a comment continues the block",
      "f.ts",
      `x\n/*\n${"a\n".repeat(6)}*/ // b\n${slashes(9)}x\n`,
      [[2, 17, "block"]],
    ],
    [
      "a one-line /* */ followed by a // comment is a comment line",
      "f.ts",
      `x\n${"/* a */ // b\n".repeat(BLOCK + 1)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    ["a one-line /* */ before code is code", "f.ts", `${"/* a */ x();\n".repeat(20)}`, []],
    [
      "a generated region inside an open /* */ contributes nothing and ends the run",
      "f.ts",
      `x();\n/*\n// BEGIN GENERATED: x\n${"g\n".repeat(20)}// END GENERATED: x\n*/\n`,
      [],
    ],
    [
      "a # run in a shell file",
      "f.sh",
      `echo x\n${hashes(BLOCK + 1)}echo y\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a # run in a workflow, indented under a key",
      ".github/workflows/ci.yml",
      `on: push\njobs:\n${hashes(BLOCK + 1).replace(/^/gm, "  ")}  a: b\n`,
      [[3, BLOCK + 1, "block"]],
    ],
    [
      "a # header in a python file",
      "f.py",
      `${hashes(HEADER + 1)}x = 1\n`,
      [[1, HEADER + 1, "header"]],
    ],
    [
      "directive lines count as comment lines",
      "f.sh",
      `echo x\n# shellcheck disable=SC2034\n${hashes(BLOCK)}echo y\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    ["an inline trailing comment is not a block", "f.ts", `${"x(); // c\n".repeat(50)}`, []],
    ["a blank line splits two blocks", "f.ts", `x\n${slashes(BLOCK)}\n${slashes(BLOCK)}x\n`, []],
    [
      "the same lines without the blank are one block (control)",
      "f.ts",
      `x\n${slashes(BLOCK)}${slashes(BLOCK)}x\n`,
      [[2, 2 * BLOCK, "block"]],
    ],
    ["markdown is prose: its # headings are not comments", "README.md", hashes(50), []],
    ["a # run in a // language is code", "f.ts", `x\n${hashes(50)}x\n`, []],
    ["a // run in a # language is code", "f.sh", `x\n${slashes(50)}x\n`, []],
    [
      "a comment block inside a generated region is not counted; the marker ends a run",
      "f.ts",
      `x\n${slashes(BLOCK)}// BEGIN GENERATED: x\n${slashes(50)}// END GENERATED: x\nx\n`,
      [],
    ],
    [
      "a CRLF file counts the same",
      "f.ts",
      `x\r\n\r\n${slashes(BLOCK + 1).replace(/\n/g, "\r\n")}x\r\n`,
      [[3, BLOCK + 1, "block"]],
    ],
    [
      "an unterminated /* */ block runs to the end of the file",
      "f.ts",
      `x\n/*\n${"a\n".repeat(BLOCK)}`,
      [[2, BLOCK + 1, "block"]],
    ],
    // The exemption marker: a comment line inside the block, reason required.
    [
      "an exempted block over the cap produces nothing",
      "f.ts",
      `x\n// ${COMMENT_MARKER} the license text upstream ships\n${slashes(50)}x\n`,
      [],
    ],
    [
      "the marker on the block's last line exempts it too",
      "f.ts",
      `x\n${slashes(50)}// ${COMMENT_MARKER} upstream text\nx\n`,
      [],
    ],
    [
      "an exempted header over its cap produces nothing",
      "f.ts",
      `// ${COMMENT_MARKER} upstream text\n${slashes(HEADER + 5)}x\n`,
      [],
    ],
    [
      "the # form exempts a shell block",
      "f.sh",
      `echo x\n# ${COMMENT_MARKER} upstream text\n${hashes(50)}echo y\n`,
      [],
    ],
    [
      "the /* */ form exempts, and the closing delimiter is not the reason",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} upstream text */\n${slashes(50)}x\n`,
      [],
    ],
    [
      "a marker inside a /* */ body exempts that block",
      "f.ts",
      `x\n/*\n * ${COMMENT_MARKER} upstream text\n${" * a\n".repeat(50)} */\nx\n`,
      [],
    ],
    [
      "a bare marker warns and exempts nothing: the over-cap block warns as well",
      "f.ts",
      `x\n// ${COMMENT_MARKER}\n${slashes(BLOCK)}x\n`,
      [[2], [2, BLOCK + 1, "block"]],
    ],
    [
      "a bare /* */ marker warns: the closing delimiter is no reason",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} */\n${slashes(2)}x\n`,
      [[2]],
    ],
    [
      "a bare marker in an under-cap block is the only finding",
      "f.sh",
      `echo x\n# ${COMMENT_MARKER}\n# a\necho y\n`,
      [[2]],
    ],
    [
      "the marker exempts only its own block: the next one over the cap still warns",
      "f.ts",
      `x\n// ${COMMENT_MARKER} upstream text\n${slashes(50)}\n${slashes(BLOCK + 1)}x\n`,
      [[54, BLOCK + 1, "block"]],
    ],
    [
      "a marker on a code line's trailing comment is not in any block (control)",
      "f.ts",
      `x(); // ${COMMENT_MARKER} upstream text\n${slashes(BLOCK + 1)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a marker after a closing delimiter and code is on a code line: not in the block",
      "f.ts",
      `x();\n/*\n${" * a\n".repeat(8)}*/ y(); // ${COMMENT_MARKER}\n`,
      [[2, 9, "block"]],
    ],
    [
      "a marker before the closing delimiter on the closer line is in the block",
      "f.ts",
      `x();\n/*\n${" * a\n".repeat(50)} * ${COMMENT_MARKER} upstream text */\n`,
      [],
    ],
    [
      "every marker counts: a bare one warns while a reasoned one exempts the same block",
      "f.ts",
      `x\n// ${COMMENT_MARKER} upstream text\n// ${COMMENT_MARKER}\n${slashes(50)}x\n`,
      [[3]],
    ],
    [
      "a one-line /* */ marker followed by an empty // comment is bare: the closing delimiter ends the reason",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} */ //\n${slashes(BLOCK)}x\n`,
      [[2], [2, BLOCK + 1, "block"]],
    ],
    [
      "two markers on one line are both read: the reasoned one exempts, the bare one warns",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} upstream text */ // ${COMMENT_MARKER}\n${slashes(50)}x\n`,
      [[2]],
    ],
    [
      "a # reason may start with a closing delimiter (no block syntax to end it)",
      "f.sh",
      `echo x\n# ${COMMENT_MARKER} */ is the upstream glob\n${hashes(50)}echo y\n`,
      [],
    ],
    [
      "a marker inside a generated region is not read",
      "f.ts",
      `x\n// BEGIN GENERATED: x\n// ${COMMENT_MARKER} upstream text\n// END GENERATED: x\n${slashes(BLOCK + 1)}x\n`,
      [[5, BLOCK + 1, "block"]],
    ],
  ])("%s", (_name, path, text, expected) => {
    const kind = classify(path);
    if (kind === null) throw new Error(`${path} has no kind`);
    expect(judgeFile(path, kind, text)).toEqual(
      expected.map((row) => commentFinding(path, kind, row)),
    );
  });
});

describe("isUnbreakable", () => {
  test.each<[string, boolean]>([
    ["https://example.com/a/very/long/path", true],
    ["    indented-token", true],
    ["two tokens", false],
    ["  run: value", false],
    ["", false],
    ["   ", false],
  ])("%j", (line, unbreakable) => {
    expect(isUnbreakable(line)).toBe(unbreakable);
  });
});

describe("parseAllowlist", () => {
  test("entries need a reason on the same line; comments and blanks are skipped", () => {
    const text = [
      "# header comment",
      "",
      "scripts/big.ts # vendored from upstream",
      "  tests/big.test.ts   #   spaced reason  ",
      "scripts/bare.ts",
      "scripts/empty.ts #",
    ].join("\n");
    expect(parseAllowlist(text)).toEqual({
      entries: [
        { path: "scripts/big.ts", reason: "vendored from upstream", line: 3 },
        { path: "tests/big.test.ts", reason: "spaced reason", line: 4 },
      ],
      failures: [
        `${ALLOWLIST_FILE}:5: 'scripts/bare.ts' has no '# reason'; ${REASON_RULE}`,
        `${ALLOWLIST_FILE}:6: 'scripts/empty.ts' has no '# reason'; ${REASON_RULE}`,
      ],
    });
  });
});

describe("check", () => {
  const BIG = lines(HARD.lines.source + 1);
  const WARM = lines(WARN.lines.source + 1);
  const WIDE = `${"a ".repeat(140).trim()}\n`;
  const bigLine = `src/big.ts: ${HARD.lines.source + 1} lines (cap ${HARD.lines.source} for source)`;
  const summary = (root: string, rendered?: string[]) => {
    const verdict = check(root, { rendered });
    return {
      failures: verdict.failures.map(describeFinding),
      warnings: verdict.warnings.map(describeFinding),
      allowlistErrors: verdict.allowlistErrors,
      managedSkipped: verdict.managedSkipped,
    };
  };

  test("judges tracked files only; ignored, untracked, generated, managed and exempt files never count", () => {
    const root = checkout(
      {
        ".gitignore": "ignored/\n",
        "src/big.ts": BIG,
        "src/warm.ts": WARM,
        "src/wide.sh": WIDE,
        "src/chatty.ts": `${"// h\n".repeat(COMMENT_CAPS.header + 1)}x\n\n${"// b\n".repeat(COMMENT_CAPS.block + 1)}x\n`,
        "src/exempt.ts": `// ${COMMENT_MARKER} upstream text\n${"// h\n".repeat(60)}x\n\n// ${COMMENT_MARKER}\nx\n`,
        "src/gen.ts": `// This file is generated by gen.ts\n${BIG}`,
        ".github/workflows/ci.yml": `${MANAGED}${WIDE}`,
        ".github/dependabot.yml": `${MANAGED}${BIG}`,
        "vendor/big.js": BIG,
        "data/big.json": BIG,
        "docs/wide.md": WIDE,
        "src/fine.ts": lines(10),
      },
      { "src/untracked.ts": BIG, "ignored/big.ts": BIG },
    );
    expect(summary(root)).toEqual({
      failures: [bigLine, `src/wide.sh:1: 279 chars (cap ${HARD.width})`],
      warnings: [
        `src/chatty.ts:1: ${COMMENT_CAPS.header + 1} comment lines (cap ${COMMENT_CAPS.header} for a header)`,
        `src/chatty.ts:${COMMENT_CAPS.header + 4}: ${COMMENT_CAPS.block + 1} comment lines (cap ${COMMENT_CAPS.block})`,
        `src/exempt.ts:64: ${COMMENT_MARKER} needs a reason`,
        `src/warm.ts: ${WARN.lines.source + 1} lines (cap ${WARN.lines.source} for source)`,
      ],
      allowlistErrors: [],
      // Only the classified managed file counts; dependabot.yml is not a kind.
      managedSkipped: 1,
    });
  });

  test("a rendered tree is judged inside its golden directory with the managed skip off", () => {
    const root = checkout({
      "tests/golden-renders/all/.github/workflows/auto.yml": `${MANAGED}${WIDE}`,
      "tests/golden-renders/all/src/gen.ts": `// generated by x\n${BIG}`,
      "tests/golden-renders/other/.github/workflows/auto.yml": `${MANAGED}${WIDE}`,
      ".github/workflows/auto.yml": `${MANAGED}${WIDE}`,
    });
    // Control: without the flag every golden is exempt and the managed root file is skipped.
    expect(summary(root)).toEqual({
      failures: [],
      warnings: [],
      allowlistErrors: [],
      managedSkipped: 1,
    });
    expect(summary(root, ["tests/golden-renders/all"])).toEqual({
      failures: [
        `tests/golden-renders/all/.github/workflows/auto.yml:2: 279 chars (cap ${HARD.width})`,
      ],
      warnings: [],
      allowlistErrors: [],
      managedSkipped: 1,
    });
  });

  test("a rendered tree outside the goldens is judged once, and a missing one throws", () => {
    const root = checkout({ "out/src/big.ts": BIG });
    expect(summary(root, ["out"]).failures).toEqual([
      `out/src/big.ts: ${HARD.lines.source + 1} lines (cap ${HARD.lines.source} for source)`,
    ]);
    expect(() => check(root, { rendered: ["missing"] })).toThrow(
      "--rendered missing: no tracked files under it",
    );
    expect(() => check(root, { rendered: ["."] })).toThrow("--rendered .: must be a subdirectory");
    expect(() => check(root, { rendered: ["out", "out/src"] })).toThrow(
      "--rendered out/src: already inside --rendered out",
    );
  });

  test("an allowlisted path with a reason silences both tiers; the unlisted control still fails", () => {
    const root = checkout({
      "src/big.ts": `${BIG}${WIDE}`,
      "src/other.ts": BIG,
      [ALLOWLIST_FILE]: "src/big.ts # vendored from upstream\n",
    });
    expect(summary(root)).toEqual({
      failures: [
        `src/other.ts: ${HARD.lines.source + 1} lines (cap ${HARD.lines.source} for source)`,
      ],
      warnings: [],
      allowlistErrors: [],
      managedSkipped: 0,
    });
  });

  test("an allowlisted warn-tier file is silenced too, and is not stale", () => {
    const root = checkout({ "src/warm.ts": WARM, [ALLOWLIST_FILE]: "src/warm.ts # known\n" });
    expect(summary(root)).toEqual({
      failures: [],
      warnings: [],
      allowlistErrors: [],
      managedSkipped: 0,
    });
  });

  test("an entry without a reason fails and exempts nothing", () => {
    const root = checkout({ "src/big.ts": BIG, [ALLOWLIST_FILE]: "src/big.ts\n" });
    expect(summary(root)).toEqual({
      failures: [bigLine],
      warnings: [],
      allowlistErrors: [`${ALLOWLIST_FILE}:1: 'src/big.ts' has no '# reason'; ${REASON_RULE}`],
      managedSkipped: 0,
    });
  });

  test("a stale entry (file back under every cap, or not tracked) fails", () => {
    const root = checkout({
      "src/fine.ts": lines(10),
      [ALLOWLIST_FILE]: "src/fine.ts # was big\nsrc/gone.ts # deleted since\n",
    });
    expect(summary(root)).toEqual({
      failures: [],
      warnings: [],
      allowlistErrors: [
        `${ALLOWLIST_FILE}:1: 'src/fine.ts' is stale (under every cap, or not a tracked file); remove the entry`,
        `${ALLOWLIST_FILE}:2: 'src/gone.ts' is stale (under every cap, or not a tracked file); remove the entry`,
      ],
      managedSkipped: 0,
    });
  });

  test("this repository passes with its allowlist, rendered goldens included", () => {
    const verdict = check(REPO_ROOT, { rendered: ["tests/golden-renders/all-modules"] });
    expect([...verdict.failures.map(describeFinding), ...verdict.allowlistErrors]).toEqual([]);
  });
});

describe("the CLI", () => {
  const hardBody = (hardLines: number) =>
    [
      "## File size check",
      "",
      "1 over a hard cap (fails), 1 warning(s).",
      "",
      "| File | Size | Tier | Cap |",
      "| --- | --- | --- | --- |",
      `| \`src/big.ts\` | ${hardLines} lines | hard | ${HARD.lines.source} |`,
      `| \`src/warm.sh:1\` | 239 chars | warn | ${WARN.width} |`,
      "",
      `Split the file, wrap the line, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`,
      "",
    ].join("\n");
  const warmBody = [
    "## File size check",
    "",
    "0 over a hard cap (fails), 2 warning(s).",
    "",
    "| File | Size | Tier | Cap |",
    "| --- | --- | --- | --- |",
    "| `src/chatty.ts:1` | 30 comment lines (header) | warn | 20 |",
    `| \`src/warm.sh:1\` | 239 chars | warn | ${WARN.width} |`,
    "",
    `Split the file, wrap the line, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`,
    "",
  ].join("\n");
  const cleanBody = [
    "## File size check",
    "",
    "Every file is under its caps.",
    "",
    "1 managed file(s) skipped; repo-platform owns them.",
    "",
  ].join("\n");

  /** Runs the script as action.yml does, over a planted stale comment body
   *  (so a run that leaves one behind shows). */
  const run = (root: string) => {
    const scratch = temp.dir("check-file-size-cli-");
    const reportPath = join(scratch, "report.md");
    const summaryPath = join(scratch, "summary.md");
    const outputPath = join(scratch, "output.txt");
    writeFileSync(reportPath, "stale\n");
    writeFileSync(summaryPath, "");
    writeFileSync(outputPath, "");
    const proc = boundedSpawnSync(["bun", SCRIPT, root], {
      env: {
        ...process.env,
        REPORT_PATH: reportPath,
        GITHUB_STEP_SUMMARY: summaryPath,
        GITHUB_OUTPUT: outputPath,
      },
    });
    return {
      exitCode: proc.exitCode,
      stdout: proc.stdout.trimEnd().split("\n"),
      stderr: proc.stderr.trimEnd().split("\n"),
      comment: existsSync(reportPath) ? readFileSync(reportPath, "utf-8") : null,
      summary: readFileSync(summaryPath, "utf-8"),
      output: readFileSync(outputPath, "utf-8"),
    };
  };

  test("findings: exit 1, ::error:: lines, the table as comment body, summary, and report=findings", () => {
    const hardLines = HARD.lines.source + 1;
    const wide = `${"a ".repeat(120).trim()}\n`;
    const root = checkout({ "src/big.ts": lines(hardLines), "src/warm.sh": wide });
    expect(run(root)).toEqual({
      exitCode: 1,
      stdout: [`::warning::src/warm.sh:1: 239 chars (cap ${WARN.width})`],
      stderr: [
        `::error::src/big.ts: ${hardLines} lines (cap ${HARD.lines.source} for source)`,
        `1 finding(s). Split the file, wrap the line, shorten or exempt the comment, or list the path in ${ALLOWLIST_FILE} with a '# reason'.`,
      ],
      comment: hardBody(hardLines),
      summary: hardBody(hardLines),
      output: "report=findings\n",
    });
  });

  test("warnings only, an over-cap comment among them: exit 0 with the same three sinks", () => {
    const root = checkout({
      "src/warm.sh": `${"a ".repeat(120).trim()}\n`,
      "src/chatty.ts": `${"// h\n".repeat(30)}x\n`,
    });
    expect(run(root)).toEqual({
      exitCode: 0,
      stdout: [
        "::warning::src/chatty.ts:1: 30 comment lines (cap 20 for a header)",
        `::warning::src/warm.sh:1: 239 chars (cap ${WARN.width})`,
        "File size check passed (2 warning(s), 0 managed file(s) skipped).",
      ],
      stderr: [""],
      comment: warmBody,
      summary: warmBody,
      output: "report=findings\n",
    });
  });

  test("clean: exit 0, a summary, no comment body (the action deletes the comment), report=clean", () => {
    const root = checkout({ "src/fine.ts": lines(3), "src/managed.ts": `${MANAGED}${lines(3)}` });
    expect(run(root)).toEqual({
      exitCode: 0,
      stdout: ["File size check passed (0 warning(s), 1 managed file(s) skipped)."],
      stderr: [""],
      comment: null,
      summary: cleanBody,
      output: "report=clean\n",
    });
  });

  test("error: a root that is no checkout exits 1 with the failure in the summary, no comment body, report=error", () => {
    const root = temp.dir("check-file-size-notgit-");
    const message = `git ls-files failed in ${root}: fatal: not a git repository (or any of the parent directories): .git`;
    expect(run(root)).toEqual({
      exitCode: 1,
      stdout: [""],
      stderr: [`::error::check-file-size did not run to completion: ${message}`],
      comment: null,
      summary: `## File size check\n\nThe check did not run to completion: ${message}\n`,
      output: "report=error\n",
    });
  });

  test("parseArgs takes a root and repeatable --rendered directories", () => {
    expect(parseArgs([])).toEqual({ root: process.cwd(), rendered: [] });
    expect(parseArgs(["/r", "--rendered", "a", "--rendered", "b"])).toEqual({
      root: "/r",
      rendered: ["a", "b"],
    });
    expect(() => parseArgs(["--rendered"])).toThrow("--rendered needs a directory");
  });
});

describe("report", () => {
  const verdict: Verdict = {
    failures: [
      { path: "a.ts", kind: "source", tier: "hard", measure: "lines", value: 2100, cap: 2000 },
    ],
    warnings: [
      {
        path: "b.sh",
        kind: "shell",
        tier: "warn",
        line: 7,
        measure: "width",
        value: 180,
        cap: 150,
      },
      {
        path: "c.ts",
        kind: "source",
        tier: "warn",
        line: 12,
        measure: "comment",
        value: 9,
        cap: 8,
        scope: "block",
      },
      {
        path: "d.ts",
        kind: "source",
        tier: "warn",
        line: 1,
        measure: "comment",
        value: 21,
        cap: 20,
        scope: "header",
      },
      { path: "e.sh", kind: "shell", tier: "warn", measure: "marker", line: 3 },
    ],
    allowlistErrors: [`${ALLOWLIST_FILE}:1: 'c.ts' is stale`],
    managedSkipped: 3,
  };

  test.each<[string, Outcome, string[]]>([
    [
      "findings render hard first as one table, allowlist errors and the managed count after",
      { state: "findings", verdict },
      [
        "## File size check",
        "",
        "1 over a hard cap (fails), 4 warning(s).",
        "",
        "| File | Size | Tier | Cap |",
        "| --- | --- | --- | --- |",
        "| `a.ts` | 2100 lines | hard | 2000 |",
        "| `b.sh:7` | 180 chars | warn | 150 |",
        "| `c.ts:12` | 9 comment lines | warn | 8 |",
        "| `d.ts:1` | 21 comment lines (header) | warn | 20 |",
        "| `e.sh:3` | comment-cap: ignore without a reason | warn | - |",
        "",
        `### ${ALLOWLIST_FILE}`,
        "",
        `- ${ALLOWLIST_FILE}:1: 'c.ts' is stale`,
        "",
        `Split the file, wrap the line, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`,
        "",
        "3 managed file(s) skipped; repo-platform owns them.",
        "",
      ],
    ],
    [
      "clean says so and keeps the managed count",
      { state: "clean", verdict: { ...verdict, failures: [], warnings: [], allowlistErrors: [] } },
      [
        "## File size check",
        "",
        "Every file is under its caps.",
        "",
        "3 managed file(s) skipped; repo-platform owns them.",
        "",
      ],
    ],
    [
      "an error names what stopped the check",
      { state: "error", message: "boom" },
      ["## File size check", "", "The check did not run to completion: boom", ""],
    ],
  ])("%s", (_name, outcome, expected) => {
    expect(report(outcome)).toBe(expected.join("\n"));
  });
});
