import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  ALLOWLIST_FILE,
  COMMENT_CAPS,
  COMMENT_MARKER,
  type CommentScope,
  check,
  classify,
  describe as describeFinding,
  type Finding,
  HARD,
  isGenerated,
  judgeFile,
  type Kind,
  REASON_RULE,
  type Tier,
  WARN,
} from "../../../actions/check-file-size/check-file-size.ts";
import { COMMENT_LINE, isManaged } from "../../../actions/shared/managed_header.ts";
import { loadAction, stepNamed } from "../../shared/action_step.ts";
import { boundedSpawnSync } from "../../shared/bounded_spawn.ts";
import { checkout } from "../../shared/fixture_checkout.ts";
import { fixtureGitEnv } from "../../shared/fixture_git.ts";
import { tempDirs } from "../../shared/temp_dir.ts";

const temp = tempDirs();
const SCRIPT = resolve(import.meta.dir, "../../../actions/check-file-size/check-file-size.ts");
const REPO_ROOT = resolve(import.meta.dir, "../../..");

const lines = (count: number): string => `${Array.from({ length: count }, () => "x").join("\n")}\n`;
const MANAGED = "# This file is managed by Vivswan/repo-platform.\n";

describe("classify", () => {
  // The kind picks the cap: a source file misread as a test gets the larger cap and passes silently. Rust's sibling test
  // modules and the workflows depth rule are conventions no file declares.
  test.each<[string, Kind | null]>([
    ["src/app.ts", "source"],
    ["src/App.tsx", "source"],
    ["src/app.mts", "source"],
    ["lib/util.cjs", "source"],
    ["pkg/types.pyi", "source"],
    ["lib/mod.rs", "source"],
    ["Main.java", "source"],
    ["include/x.h", "source"],
    ["src/app.test.ts", "test"],
    ["src/widget.spec.ts", "test"],
    ["pkg/foo_test.go", "test"],
    ["spec/foo_spec.rb", null],
    ["test_module.py", "test"],
    ["tests/helper.ts", "test"],
    ["test/helpers/fixtures.ts", "test"],
    ["src/__tests__/util.js", "test"],
    ["src/policy/store_tests.rs", "test"],
    ["src/policy/tests.rs", "test"],
    ["src/proptests.rs", "test"],
    ["src/tests_util.rs", "source"],
    ["src/large.cc", "source"],
    ["include/x.hpp", "source"],
    ["src/a.cxx", "source"],
    ["include/b.hh", "source"],
    ["src/testing/util.ts", "source"],
    [".github/workflows/ci.yml", "workflow"],
    [".github/workflows/ci.yaml", "workflow"],
    ["actions/check/action.yml", "workflow"],
    ["action.yml", "workflow"],
    [".github/workflows/nested/x.yml", null],
    ["config/settings.yml", null],
    ["scripts/run.sh", "shell"],
    ["bin/setup.bash", "shell"],
    [".zshrc.zsh", "shell"],
    ["README.md", "markdown"],
    ["docs/guide.md", "markdown"],
    ["package.json", null],
    ["bun.lock", null],
    ["logo.png", null],
    ["Makefile", null],
    ["node_modules/pkg/index.js", null],
    ["vendor/lib.go", null],
    ["tests/goldens/minimal/README.md", null],
    ["src/__snapshots__/app.test.ts", null],
  ])("%s -> %s", (path, kind) => {
    expect(classify(path)).toBe(kind);
  });
});

/** Abridged header excerpts of this repository's hand-written files that
 *  name a generator without declaring anything about themselves. */
const GENERATOR_MENTIONS: [string, string][] = [
  [
    "a helper naming the generator that calls it (action_steps.ts)",
    "// Composite action manifests read the way Actions reads them: their steps\n// and the action directories whose bun-setup step reads an action-local\n// .bun-version pin (scripts/generate/toolchain_pins.ts writes them).\n",
  ],
  [
    "a loader naming the outputs derived from it (files_config.ts)",
    "// Shared loader for files.yml (the writer's file table).\n//\n// scripts/generate/build_gitignore.ts derives the block files from\n// its modules; the sync writer reads them at runtime.\n",
  ],
  [
    "a table whose rows are a generated region (docs/new-repo.md)",
    "// The files table is generated from files.yml\n// (scripts/generate/files_table.ts);\n",
  ],
];

describe("isGenerated / isManaged", () => {
  // The generator phrasings (protoc-gen-go, bindgen, flex, grammar-kit, p10k) are external: a hand-written file taken
  // for generated is skipped silently, and a file that merely names a generator must not be. The managed rows are
  // cross-file with MANAGED_HEADER_PATTERN.
  test.each<[string, string, boolean, boolean]>([
    ...GENERATOR_MENTIONS.map(([name, text]): [string, string, boolean, boolean] => [
      name,
      text,
      false,
      false,
    ]),
    [
      "the gitignore generator's header comment",
      "# Generated from github/gitignore - do not edit between the BEGIN/END\nx\n",
      true,
      false,
    ],
    [
      "a go header, the directive after the tool",
      "// Code generated by protoc-gen-go. DO NOT EDIT.\nx\n",
      true,
      false,
    ],
    ["a jsdoc opener", "/** Generated by x. */\nx\n", true, false],
    [
      "rust-bindgen's header",
      "/* automatically generated by rust-bindgen 0.69.4 */\nx\n",
      true,
      false,
    ],
    ["flex's header", "/* A lexical scanner generated by flex */\nx\n", true, false],
    [
      "grammar-kit's header",
      "// This is a generated file. Not intended for manual editing.\nx\n",
      true,
      false,
    ],
    ["z3's header", "// automatically generated file.\nx\n", true, false],
    [
      "clang's header, the noun phrase continued",
      "/* This generated file is for internal use. Do not include it from headers. */\nx\n",
      true,
      false,
    ],
    [
      "the noun phrase in prose still counts: real headers continue it too (clang's)",
      "// repo's own copies, so each generated file has exactly one author: the\nx\n",
      true,
      false,
    ],
    [
      "generated by",
      "# Generated by Powerlevel10k configuration wizard on 2026-02-23.\nx\n",
      true,
      false,
    ],
    ["auto-generated", "// auto-generated, see the build\nx\n", true, false],
    ["autogenerated", "// AUTOGENERATED FILE\nx\n", true, false],
    ["this file is generated", "/* This file is generated. */\nx\n", true, false],
    ["do not edit", "# DO NOT EDIT - built from the manifests\nx\n", true, false],
    ["generated file", "<!-- generated file -->\nx\n", true, false],
    ["a marker on the tenth line", `${lines(9)}// generated by x\n`, true, false],
    ["the managed header is managed, not generated", `${MANAGED}x\n`, false, true],
    [
      "a managed header with a dotted owner",
      "# This file is managed by a.b-c/repo-platform.\n",
      false,
      true,
    ],
    ["a string literal is not a header", 'const label = "do not edit";\n', false, false],
    [
      "prose using the word generate",
      "// Copies GENERATED from the manifests are NOT compared\nx\n",
      false,
      false,
    ],
    ["a marker past the header window", `${lines(10)}// generated by x\n`, false, false],
    ["a python docstring header", '"""Generated by foo."""\nx\n', true, false],
    ["a single-quoted docstring header", "'''Generated by foo.'''\nx\n", true, false],
    ["a bare string literal is not a comment", '"do not edit";\nx\n', false, false],
    [
      "a managed sentence in a string literal is not a header",
      'const note = "This file is managed by acme/repo-platform";\n',
      false,
      false,
    ],
    ["no header", "const x = 1;\n", false, false],
  ])(
    "a header is generated or managed by its vocabulary: %s",
    (_name, text, generated, managed) => {
      expect([isGenerated(text), isManaged(text)]).toEqual([generated, managed]);
    },
  );
});

describe("judgeFile line counts", () => {
  const kinds: Kind[] = ["source", "test", "workflow", "shell", "markdown"];
  // A 50-line matched generated region rides along in every kind's rows and never counts: without the mask a file
  // carrying a fenced region fails on lines its author cannot shorten. WARN is derived from HARD; the boundary rows
  // keep the derivation from drifting.
  const region = `# BEGIN GENERATED: x\n${lines(48)}# END GENERATED: x\n`;
  const finding = (kind: Kind, tier: Tier, value: number): Finding => ({
    path: `file.${kind}`,
    kind,
    tier,
    measure: "lines",
    value,
    cap: tier === "hard" ? HARD.lines[kind] : WARN.lines[kind],
  });
  const SOURCE = HARD.lines.source;
  test.each<[string, Kind, string, Finding[]]>([
    ...kinds.flatMap((kind): [string, Kind, string, Finding[]][] => {
      const hard = HARD.lines[kind];
      const warn = WARN.lines[kind];
      return [
        [`${kind} at the warn cap`, kind, `${region}${lines(warn)}`, []],
        [
          `${kind} one over the warn cap`,
          kind,
          `${lines(warn + 1)}${region}`,
          [finding(kind, "warn", warn + 1)],
        ],
        [`${kind} at the hard cap`, kind, `${region}${lines(hard)}`, [finding(kind, "warn", hard)]],
        [
          `${kind} one over the hard cap`,
          kind,
          `${lines(hard + 1)}${region}`,
          [finding(kind, "hard", hard + 1)],
        ],
      ];
    }),
    [
      "an unmatched BEGIN GENERATED fences nothing (control)",
      "source",
      `// BEGIN GENERATED: x\n${lines(SOURCE)}`,
      [finding("source", "hard", SOURCE + 1)],
    ],
    [
      "both markers on one line fence that line alone: at the warn boundary",
      "source",
      `// BEGIN GENERATED: x END GENERATED: x\n${lines(WARN.lines.source)}`,
      [],
    ],
    [
      "both markers on one line fence that line alone: one over the hard cap",
      "source",
      `// BEGIN GENERATED: x END GENERATED: x\n${lines(SOURCE + 1)}`,
      [finding("source", "hard", SOURCE + 1)],
    ],
    [
      "a missing trailing newline still counts the last line",
      "source",
      Array.from({ length: SOURCE + 1 }, () => "x").join("\n"),
      [finding("source", "hard", SOURCE + 1)],
    ],
    [
      "a trailing newline adds no line",
      "source",
      lines(SOURCE),
      [finding("source", "warn", SOURCE)],
    ],
  ])("%s", (_name, kind, text, expected) => {
    expect(judgeFile(`file.${kind}`, kind, text)).toEqual(expected);
  });
});

describe("judgeFile comment blocks", () => {
  const { block: BLOCK, header: HEADER } = COMMENT_CAPS;
  const slashes = (count: number): string =>
    `${Array.from({ length: count }, (_, i) => `// c${i}`).join("\n")}\n`;
  const hashes = (count: number): string =>
    `${Array.from({ length: count }, (_, i) => `# c${i}`).join("\n")}\n`;
  const starred = (count: number, open = "/*"): string =>
    `${open}\n${Array.from({ length: count - 2 }, (_, i) => ` * c${i}`).join("\n")}\n */\n`;
  type Row = [line: number, length: number, scope: CommentScope] | [marker: number];
  const commentFinding = (path: string, kind: Kind, row: Row): Finding =>
    row.length === 1
      ? { path, kind, tier: "warn", measure: "marker", line: row[0] }
      : {
          path,
          kind,
          tier: "warn",
          measure: "comment",
          line: row[0],
          value: row[1],
          cap: COMMENT_CAPS[row[2]],
          scope: row[2],
        };
  const judgeComments = (path: string, text: string, expected: Row[]): void => {
    const kind = classify(path);
    if (kind === null) throw new Error(`${path} has no kind`);
    expect(judgeFile(path, kind, text)).toEqual(
      expected.map((row) => commentFinding(path, kind, row)),
    );
  };

  // docs/fleet-guidelines.md names the prefixes by hand and COMMENT_LINE (actions/shared/managed_header.ts) is the
  // source, so the two can drift apart. Each prefix the guide names is driven through a block, indented, in two
  // languages (the prefix decides, never the extension), and the guide's set is the regex's alternatives, exactly.
  const documented = (() => {
    const bullet = readFileSync(join(REPO_ROOT, "docs/fleet-guidelines.md"), "utf8")
      .split("\n")
      .find((line) => line.startsWith("- **A comment block**"));
    if (bullet === undefined)
      throw new Error("docs/fleet-guidelines.md lost its comment block bullet");
    return [...bullet.matchAll(/`([^`]+)`/g)].map((match) => match[1]);
  })();
  test("the guide names exactly the comment prefixes the regex knows", () => {
    const alternatives = COMMENT_LINE.source
      .replace(/^\^\\s\*\(/, "")
      .replace(/\)$/, "")
      .split("|")
      .map((alternative) => alternative.replace(/\\(.)/g, "$1"));
    expect([...documented].sort()).toEqual([...alternatives].sort());
  });
  test.each(documented)(
    "a run of lines opening with %s is a block, in any judged kind",
    (prefix) => {
      const run = (count: number): string =>
        `${Array.from({ length: count }, (_, i) => `  ${prefix} c${i}`).join("\n")}\n`;
      judgeComments("f.ts", `x\n${run(BLOCK + 1)}x\n`, [[2, BLOCK + 1, "block"]]);
      judgeComments("f.sh", `x\n${run(BLOCK + 1)}x\n`, [[2, BLOCK + 1, "block"]]);
      judgeComments("f.ts", `x\n${run(BLOCK)}x\n`, []);
    },
  );

  // Every case names its file: the kind read off it decides whether blocks are judged at all (markdown is prose).
  test.each<[string, string, string, Row[]]>([
    ["a block at the cap passes", "f.ts", `x\n\n${slashes(BLOCK)}x\n`, []],
    [
      "a block one over the cap warns",
      "f.ts",
      `x\n\n${slashes(BLOCK + 1)}x\n`,
      [[3, BLOCK + 1, "block"]],
    ],
    [
      "a block far over the cap still only warns",
      "f.ts",
      `x\n\n${slashes(50)}x\n`,
      [[3, 50, "block"]],
    ],
    ["a header at the cap passes", "f.ts", `${slashes(HEADER)}x\n`, []],
    [
      "a header one over the cap warns",
      "f.ts",
      `${slashes(HEADER + 1)}x\n`,
      [[1, HEADER + 1, "header"]],
    ],
    [
      "a header after a shebang is still the header, and the shebang does not count",
      "f.ts",
      `#!/usr/bin/env bun\n${slashes(HEADER + 1)}x\n`,
      [[2, HEADER + 1, "header"]],
    ],
    [
      "a header after a shebang and a blank line",
      "f.sh",
      `#!/bin/sh\n\n${hashes(HEADER + 1)}echo x\n`,
      [[3, HEADER + 1, "header"]],
    ],
    [
      "a shebang alone is no comment block (control)",
      "f.sh",
      `#!/bin/sh\n${hashes(HEADER)}echo x\n`,
      [],
    ],
    [
      "a shebang with a space before the path is still a shebang",
      "f.py",
      `#! /usr/bin/env python3\n${hashes(HEADER + 1)}x = 1\n`,
      [[2, HEADER + 1, "header"]],
    ],
    [
      "a header past the block cap but under the header cap passes; the same block after code is judged as a block",
      "f.ts",
      `${slashes(BLOCK + 1)}x\n\n${slashes(BLOCK + 1)}x\n`,
      [[BLOCK + 4, BLOCK + 1, "block"]],
    ],
    [
      "a second block before any code is a block, not a header",
      "f.ts",
      `${slashes(2)}\n${slashes(BLOCK + 1)}x\n`,
      [[4, BLOCK + 1, "block"]],
    ],
    [
      "a /* */ block whose body lines open with * counts every line, delimiters included",
      "f.ts",
      `x\n${starred(BLOCK + 1)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a JSDoc block is a block",
      "f.mts",
      `x\n${starred(BLOCK + 1, "/**")}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a // run flowing into a /* */ block is one block",
      "f.ts",
      `x\n${slashes(BLOCK)}${starred(3)}x\n`,
      [[2, BLOCK + 3, "block"]],
    ],
    [
      "a one-line /* */ followed by a // comment is a comment line",
      "f.ts",
      `x\n${"/* a */ // b\n".repeat(BLOCK + 1)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a generated region before the header does not demote it: the header cap applies",
      "f.ts",
      `// BEGIN GENERATED: x\ng\n// END GENERATED: x\n${slashes(HEADER)}x\n`,
      [],
    ],
    [
      "the same header one over the header cap warns as a header, the region not counted",
      "f.ts",
      `// BEGIN GENERATED: x\ng\n// END GENERATED: x\n${slashes(HEADER + 1)}x\n`,
      [[4, HEADER + 1, "header"]],
    ],
    [
      "a code line between the region and the block still demotes it (control)",
      "f.ts",
      `// BEGIN GENERATED: x\ng\n// END GENERATED: x\nx\n${slashes(BLOCK + 1)}x\n`,
      [[5, BLOCK + 1, "block"]],
    ],
    [
      "a generated region ends the header run: the comments after it are a block",
      "f.ts",
      `${slashes(2)}// BEGIN GENERATED: x\n// END GENERATED: x\n${slashes(BLOCK + 1)}x\n`,
      [[5, BLOCK + 1, "block"]],
    ],
    [
      "a generated region inside an open /* */ contributes nothing and ends the run",
      "f.ts",
      `x();\n/*\n// BEGIN GENERATED: x\n${"g\n".repeat(20)}// END GENERATED: x\n*/\n`,
      [],
    ],
    [
      "a # run in a shell file",
      "f.sh",
      `echo x\n${hashes(BLOCK + 1)}echo y\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a # run in a workflow, indented under a key",
      ".github/workflows/ci.yml",
      `on: push\njobs:\n${hashes(BLOCK + 1).replace(/^/gm, "  ")}  a: b\n`,
      [[3, BLOCK + 1, "block"]],
    ],
    [
      "a # header in a python file",
      "f.py",
      `${hashes(HEADER + 1)}x = 1\n`,
      [[1, HEADER + 1, "header"]],
    ],
    [
      "directive lines count as comment lines",
      "f.sh",
      `echo x\n# shellcheck disable=SC2034\n${hashes(BLOCK)}echo y\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    ["an inline trailing comment is not a block", "f.ts", `${"x(); // c\n".repeat(50)}`, []],
    ["a blank line splits two blocks", "f.ts", `x\n${slashes(BLOCK)}\n${slashes(BLOCK)}x\n`, []],
    [
      "the same lines without the blank are one block (control)",
      "f.ts",
      `x\n${slashes(BLOCK)}${slashes(BLOCK)}x\n`,
      [[2, 2 * BLOCK, "block"]],
    ],
    ["markdown is prose: its # headings are not comments", "README.md", hashes(50), []],
    [
      "a line opening with code is code, whatever comment syntax it holds",
      "f.ts",
      `x\n${'const s = "// c"; /* d */\n'.repeat(BLOCK + 1)}x\n`,
      [],
    ],
    [
      "a comment block inside a generated region is not counted; the marker ends a run",
      "f.ts",
      `x\n${slashes(BLOCK)}// BEGIN GENERATED: x\n${slashes(50)}// END GENERATED: x\nx\n`,
      [],
    ],
    [
      "a CRLF file counts the same",
      "f.ts",
      `x\r\n\r\n${slashes(BLOCK + 1).replace(/\n/g, "\r\n")}x\r\n`,
      [[3, BLOCK + 1, "block"]],
    ],
    // The misreads docs/fleet-guidelines.md names under "The accepted cost", one row each, so the guide cannot keep
    // naming a cost the code no longer pays.
    [
      "the guide's cost: a string's lines opening with a prefix read as a block",
      "f.ts",
      `x\nconst t = \`\n${"# c\n// c\n".repeat(BLOCK)}\`;\nx\n`,
      [[3, 2 * BLOCK, "block"]],
    ],
    [
      "the guide's cost: a here-doc's # lines read as a block like the same lines after it",
      "f.sh",
      `cat <<'EOF'\n${hashes(BLOCK + 1)}EOF\n${hashes(BLOCK + 1)}echo y\n`,
      [
        [2, BLOCK + 1, "block"],
        [BLOCK + 4, BLOCK + 1, "block"],
      ],
    ],
    [
      "the guide's cost: a yaml block scalar's # lines read as a block",
      ".github/workflows/f.yml",
      `run: |\n${hashes(BLOCK + 1).replace(/^/gm, "  ")}x: y\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "the guide's cost: a /* */ body whose lines open with no * reads as code, so no block forms",
      "f.js",
      `x\n/*\n${"a\n\nb\n".repeat(3)}*/\nx\n`,
      [],
    ],
    [
      "an exempted block over the cap produces nothing",
      "f.ts",
      `x\n// ${COMMENT_MARKER} the license text upstream ships\n${slashes(50)}x\n`,
      [],
    ],
    [
      "the marker on the block's last line exempts it too",
      "f.ts",
      `x\n${slashes(50)}// ${COMMENT_MARKER} upstream text\nx\n`,
      [],
    ],
    [
      "an exempted header over its cap produces nothing",
      "f.ts",
      `// ${COMMENT_MARKER} upstream text\n${slashes(HEADER + 5)}x\n`,
      [],
    ],
    [
      "the # form exempts a shell block",
      "f.sh",
      `echo x\n# ${COMMENT_MARKER} upstream text\n${hashes(50)}echo y\n`,
      [],
    ],
    [
      "the /* */ form exempts, and the closing delimiter is not the reason",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} upstream text */\n${slashes(50)}x\n`,
      [],
    ],
    [
      "a marker inside a /* */ body exempts that block",
      "f.ts",
      `x\n/*\n * ${COMMENT_MARKER} upstream text\n${" * a\n".repeat(50)} */\nx\n`,
      [],
    ],
    [
      "a bare marker warns and exempts nothing: the over-cap block warns as well",
      "f.ts",
      `x\n// ${COMMENT_MARKER}\n${slashes(BLOCK)}x\n`,
      [[2], [2, BLOCK + 1, "block"]],
    ],
    [
      "a bare marker inside a /* */ body takes no reason from the lines after it",
      "f.ts",
      `x();\n/*\n * ${COMMENT_MARKER}\n${" * text\n".repeat(9)} */\n`,
      [[3], [2, 12, "block"]],
    ],
    [
      "a bare /* */ marker warns: the closing delimiter is no reason",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} */\n${slashes(2)}x\n`,
      [[2]],
    ],
    [
      "a bare marker in an under-cap block is the only finding",
      "f.sh",
      `echo x\n# ${COMMENT_MARKER}\n# a\necho y\n`,
      [[2]],
    ],
    [
      "the marker exempts only its own block: the next one over the cap still warns",
      "f.ts",
      `x\n// ${COMMENT_MARKER} upstream text\n${slashes(50)}\n${slashes(BLOCK + 1)}x\n`,
      [[54, BLOCK + 1, "block"]],
    ],
    [
      "a marker on a code line's trailing comment is not in any block (control)",
      "f.ts",
      `x(); // ${COMMENT_MARKER} upstream text\n${slashes(BLOCK + 1)}x\n`,
      [[2, BLOCK + 1, "block"]],
    ],
    [
      "a marker before the closing delimiter on the closer line is in the block",
      "f.ts",
      `x();\n/*\n${" * a\n".repeat(50)} * ${COMMENT_MARKER} upstream text */\n`,
      [],
    ],
    [
      "every marker counts: a bare one warns while a reasoned one exempts the same block",
      "f.ts",
      `x\n// ${COMMENT_MARKER} upstream text\n// ${COMMENT_MARKER}\n${slashes(50)}x\n`,
      [[3]],
    ],
    [
      "a one-line /* */ marker followed by an empty // comment is bare: delimiters are no reason",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} */ //\n${slashes(BLOCK)}x\n`,
      [[2], [2, BLOCK + 1, "block"]],
    ],
    [
      "two markers on one line are both read: the reasoned one exempts, the bare one warns",
      "f.ts",
      `x\n/* ${COMMENT_MARKER} upstream text */ // ${COMMENT_MARKER}\n${slashes(50)}x\n`,
      [[2]],
    ],
    [
      "a reason may open with a closing delimiter: the word after it is the reason",
      "f.sh",
      `echo x\n# ${COMMENT_MARKER} */ is the upstream glob\n${hashes(50)}echo y\n`,
      [],
    ],
    [
      "a reason in any script is a reason (a word-character regex read this one as bare)",
      "f.ts",
      `x\n// ${COMMENT_MARKER} 保留上游许可证\n${slashes(50)}x\n`,
      [],
    ],
    [
      "a marker inside a generated region is not read",
      "f.ts",
      `x\n// BEGIN GENERATED: x\n// ${COMMENT_MARKER} upstream text\n// END GENERATED: x\n${slashes(BLOCK + 1)}x\n`,
      [[5, BLOCK + 1, "block"]],
    ],
  ])("%s", (_name, path, text, expected) => {
    judgeComments(path, text, expected);
  });
});

describe("check", () => {
  const BIG = lines(HARD.lines.source + 1);
  const WARM = lines(WARN.lines.source + 1);
  const bigLine = `src/big.ts: ${HARD.lines.source + 1} lines (cap ${HARD.lines.source} for source)`;
  const summary = (root: string) => {
    const verdict = check(root);
    return {
      failures: verdict.failures.map(describeFinding),
      warnings: verdict.warnings.map(describeFinding),
      allowlistErrors: verdict.allowlistErrors,
      managedSkipped: verdict.managedSkipped,
    };
  };

  test("judges tracked files only; ignored, untracked, generated, managed, goldens and exempt files never count", () => {
    const root = checkout(
      temp,
      "check-file-size-",
      {
        ".gitignore": "ignored/\n",
        "tests/goldens/all/.github/workflows/auto.yml": `${MANAGED}x\n`,
        "tests/goldens/all/src/gen.ts": `// generated by x\n${BIG}`,
        "src/big.ts": BIG,
        "src/warm.ts": WARM,
        "src/chatty.ts": `${"// h\n".repeat(COMMENT_CAPS.header + 1)}x\n\n${"// b\n".repeat(COMMENT_CAPS.block + 1)}x\n`,
        "src/exempt.ts": `// ${COMMENT_MARKER} upstream text\n${"// h\n".repeat(60)}x\n\n// ${COMMENT_MARKER}\nx\n`,
        "src/gen.ts": `// This file is generated by gen.ts\n${BIG}`,
        ".github/workflows/ci.yml": `${MANAGED}x\n`,
        ".github/dependabot.yml": `${MANAGED}${BIG}`,
        "vendor/big.js": BIG,
        "data/big.json": BIG,
        "docs/chatty.md": `${"# h\n".repeat(50)}`,
        "src/fine.ts": lines(10),
      },
      { "src/untracked.ts": BIG, "ignored/big.ts": BIG },
    );
    expect(summary(root)).toEqual({
      failures: [bigLine],
      warnings: [
        `src/chatty.ts:1: ${COMMENT_CAPS.header + 1} comment lines (cap ${COMMENT_CAPS.header} for a header)`,
        `src/chatty.ts:${COMMENT_CAPS.header + 4}: ${COMMENT_CAPS.block + 1} comment lines (cap ${COMMENT_CAPS.block})`,
        `src/exempt.ts:64: ${COMMENT_MARKER} needs a reason`,
        `src/warm.ts: ${WARN.lines.source + 1} lines (cap ${WARN.lines.source} for source)`,
      ],
      allowlistErrors: [],
      // Only the classified managed file counts; dependabot.yml is not a kind.
      managedSkipped: 1,
    });
  });

  // The fleet's bypass: an allowlist matching by prefix, silencing the control, or exempting without a reason would pass
  // silently. The stale rule is what keeps the file honest once the path shrinks.
  test.each<[string, Record<string, string>, ReturnType<typeof summary>]>([
    [
      "a path with a reason is silenced; header comments, blanks and spacing are skipped; the unlisted control still fails",
      {
        "src/big.ts": BIG,
        "src/other.ts": BIG,
        [ALLOWLIST_FILE]: "# header comment\n\n  src/big.ts   #   vendored from upstream  \n",
      },
      {
        failures: [
          `src/other.ts: ${HARD.lines.source + 1} lines (cap ${HARD.lines.source} for source)`,
        ],
        warnings: [],
        allowlistErrors: [],
        managedSkipped: 0,
      },
    ],
    [
      "a warn-tier file is silenced too, and is not stale",
      { "src/warm.ts": WARM, [ALLOWLIST_FILE]: "src/warm.ts # known\n" },
      { failures: [], warnings: [], allowlistErrors: [], managedSkipped: 0 },
    ],
    [
      "an entry without a reason, or with an empty one, fails and exempts nothing",
      { "src/big.ts": BIG, "src/other.ts": BIG, [ALLOWLIST_FILE]: "src/big.ts\nsrc/other.ts #\n" },
      {
        failures: [
          bigLine,
          `src/other.ts: ${HARD.lines.source + 1} lines (cap ${HARD.lines.source} for source)`,
        ],
        warnings: [],
        allowlistErrors: [
          `${ALLOWLIST_FILE}:1: 'src/big.ts' has no '# reason'; ${REASON_RULE}`,
          `${ALLOWLIST_FILE}:2: 'src/other.ts' has no '# reason'; ${REASON_RULE}`,
        ],
        managedSkipped: 0,
      },
    ],
    [
      "a stale entry (file back under every cap, or not tracked) fails",
      {
        "src/fine.ts": lines(10),
        [ALLOWLIST_FILE]: "src/fine.ts # was big\nsrc/gone.ts # deleted since\n",
      },
      {
        failures: [],
        warnings: [],
        allowlistErrors: [
          `${ALLOWLIST_FILE}:1: 'src/fine.ts' is stale (under every cap, or not a tracked file); remove the entry`,
          `${ALLOWLIST_FILE}:2: 'src/gone.ts' is stale (under every cap, or not a tracked file); remove the entry`,
        ],
        managedSkipped: 0,
      },
    ],
  ])("allowlist: %s", (_name, tree, expected) => {
    expect(summary(checkout(temp, "check-file-size-", tree))).toEqual(expected);
  });
});

describe("the CLI", () => {
  // action.yml gates the sticky comment on the `report` output: one literal posts, the other deletes, and both steps are
  // continue-on-error, so a value the script renames is never posted or never deleted, green. The two literals are read
  // from the manifest so neither side can move alone.
  const gateValue = (stepName: string): string => {
    const gate = String(stepNamed(loadAction("actions/check-file-size/action.yml"), stepName).if);
    const value = /steps\.check\.outputs\.report == '([a-z]+)'/.exec(gate)?.[1];
    if (value === undefined) throw new Error(`no report gate in ${gate}`);
    return value;
  };
  const POSTED = gateValue("Post the findings as a sticky PR comment");
  const DELETED = gateValue("Remove a stale sticky comment");
  const REMEDY = `Split the file, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`;
  const hardLines = HARD.lines.source + 1;
  const stale = `${ALLOWLIST_FILE}:1: 'src/fine.ts' is stale (under every cap, or not a tracked file); remove the entry`;
  const table = (rows: string[]) => [
    "| File | Size | Tier | Cap |",
    "| --- | --- | --- | --- |",
    ...rows,
  ];
  const findingsBody = [
    "## File size check",
    "",
    "1 over a hard cap (fails), 3 warning(s).",
    "",
    ...table([
      `| \`src/big.ts\` | ${hardLines} lines | hard | ${HARD.lines.source} |`,
      `| \`src/chatty.ts:2\` | ${COMMENT_CAPS.block + 1} comment lines | warn | ${COMMENT_CAPS.block} |`,
      `| \`src/header.ts:1\` | ${COMMENT_CAPS.header + 1} comment lines (header) | warn | ${COMMENT_CAPS.header} |`,
      `| \`src/marker.sh:1\` | comment-cap: ignore without a reason | warn | - |`,
    ]),
    "",
    REMEDY,
    "",
    "1 managed file(s) skipped; repo-platform owns them.",
    "",
  ].join("\n");
  const warmBody = [
    "## File size check",
    "",
    "0 over a hard cap (fails), 1 warning(s).",
    "",
    ...table([
      `| \`src/chatty.ts:1\` | 30 comment lines (header) | warn | ${COMMENT_CAPS.header} |`,
    ]),
    "",
    REMEDY,
    "",
  ].join("\n");
  const staleBody = [
    "## File size check",
    "",
    "0 over a hard cap (fails), 0 warning(s).",
    "",
    `### ${ALLOWLIST_FILE}`,
    "",
    `- ${stale}`,
    "",
    REMEDY,
    "",
  ].join("\n");
  const cleanBody = [
    "## File size check",
    "",
    "Every file is under its caps.",
    "",
    "1 managed file(s) skipped; repo-platform owns them.",
    "",
  ].join("\n");

  /** Runs the script as action.yml does, over a planted stale comment body
   *  (so a run that leaves one behind shows). */
  const run = (root: string) => {
    const scratch = temp.dir("check-file-size-cli-");
    const reportPath = join(scratch, "report.md");
    const summaryPath = join(scratch, "summary.md");
    const outputPath = join(scratch, "output.txt");
    writeFileSync(reportPath, "stale\n");
    writeFileSync(summaryPath, "");
    writeFileSync(outputPath, "");
    const proc = boundedSpawnSync(["bun", SCRIPT, root], {
      env: {
        ...fixtureGitEnv(),
        REPORT_PATH: reportPath,
        GITHUB_STEP_SUMMARY: summaryPath,
        GITHUB_OUTPUT: outputPath,
      },
    });
    return {
      exitCode: proc.exitCode,
      stdout: proc.stdout.trimEnd().split("\n"),
      stderr: proc.stderr.trimEnd().split("\n"),
      comment: existsSync(reportPath) ? readFileSync(reportPath, "utf-8") : null,
      summary: readFileSync(summaryPath, "utf-8"),
      output: readFileSync(outputPath, "utf-8"),
    };
  };
  const notGit = () => temp.dir("check-file-size-notgit-");
  const gitMessage = (root: string) =>
    `git ls-files failed in ${root}: fatal: not a git repository (or any of the parent directories): .git`;

  test.each<[string, () => string, (root: string) => ReturnType<typeof run>]>([
    [
      "findings: exit 1 on the hard finding alone, ::error:: and ::warning:: lines, the table hard first, and the managed count, as comment and summary",
      () =>
        checkout(temp, "check-file-size-", {
          "src/big.ts": lines(hardLines),
          "src/chatty.ts": `x\n${"// c\n".repeat(COMMENT_CAPS.block + 1)}x\n`,
          "src/header.ts": `${"// h\n".repeat(COMMENT_CAPS.header + 1)}x\n`,
          "src/marker.sh": `# ${COMMENT_MARKER}\necho x\n`,
          "src/managed.ts": `${MANAGED}x\n`,
        }),
      () => ({
        exitCode: 1,
        stdout: [
          `::warning::src/chatty.ts:2: ${COMMENT_CAPS.block + 1} comment lines (cap ${COMMENT_CAPS.block})`,
          `::warning::src/header.ts:1: ${COMMENT_CAPS.header + 1} comment lines (cap ${COMMENT_CAPS.header} for a header)`,
          `::warning::src/marker.sh:1: ${COMMENT_MARKER} needs a reason`,
        ],
        stderr: [
          `::error::src/big.ts: ${hardLines} lines (cap ${HARD.lines.source} for source)`,
          `1 finding(s). Split the file, shorten or exempt the comment, or list the path in ${ALLOWLIST_FILE} with a '# reason'.`,
        ],
        comment: findingsBody,
        summary: findingsBody,
        output: `report=${POSTED}\n`,
      }),
    ],
    [
      "a warning only, an over-cap header: exit 0 with the same three sinks",
      () =>
        checkout(temp, "check-file-size-", {
          "src/chatty.ts": `${"// h\n".repeat(30)}x\n`,
        }),
      () => ({
        exitCode: 0,
        stdout: [
          `::warning::src/chatty.ts:1: 30 comment lines (cap ${COMMENT_CAPS.header} for a header)`,
          "File size check passed (1 warning(s), 0 managed file(s) skipped).",
        ],
        stderr: [""],
        comment: warmBody,
        summary: warmBody,
        output: `report=${POSTED}\n`,
      }),
    ],
    [
      "a stale allowlist entry alone: exit 1 and the comment posted with the allowlist section; read as clean, the action would delete the comment while the run fails with no table",
      () =>
        checkout(temp, "check-file-size-", {
          "src/fine.ts": lines(3),
          [ALLOWLIST_FILE]: "src/fine.ts # was big\n",
        }),
      () => ({
        exitCode: 1,
        stdout: [""],
        stderr: [
          `::error::${stale}`,
          `1 finding(s). Split the file, shorten or exempt the comment, or list the path in ${ALLOWLIST_FILE} with a '# reason'.`,
        ],
        comment: staleBody,
        summary: staleBody,
        output: `report=${POSTED}\n`,
      }),
    ],
    [
      "clean: exit 0, a summary, no comment body (the action deletes the comment)",
      () =>
        checkout(temp, "check-file-size-", {
          "src/fine.ts": lines(3),
          "src/managed.ts": `${MANAGED}${lines(3)}`,
        }),
      () => ({
        exitCode: 0,
        stdout: ["File size check passed (0 warning(s), 1 managed file(s) skipped)."],
        stderr: [""],
        comment: null,
        summary: cleanBody,
        output: `report=${DELETED}\n`,
      }),
    ],
    [
      "error: a root that is no checkout exits 1 with the failure in the summary and no comment body",
      notGit,
      (root) => ({
        exitCode: 1,
        stdout: [""],
        stderr: [`::error::check-file-size did not run to completion: ${gitMessage(root)}`],
        comment: null,
        summary: `## File size check\n\nThe check did not run to completion: ${gitMessage(root)}\n`,
        output: "report=error\n",
      }),
    ],
  ])("%s", (_name, makeRoot, expected) => {
    const root = makeRoot();
    expect(run(root)).toEqual(expected(root));
  });
});

// docs/fleet-guidelines.md spells the caps by hand for the fleet; the tests above read them from the source, so a changed
// ratio or cap would leave the guide lying with nothing red.
test("the caps table in docs/fleet-guidelines.md is the caps the code judges by", () => {
  const rows = readFileSync(join(REPO_ROOT, "docs/fleet-guidelines.md"), "utf8")
    .split("\n")
    .filter((line) => /^\| (source|test|workflow|shell|markdown|comment block) \|/.test(line))
    .map((line) => line.split("|").map((cell) => cell.trim()))
    .map((cells) => [cells[1], cells[3], cells[4]?.replace(/ \(.*\)$/, "")]);
  const kinds: Kind[] = ["source", "test", "workflow", "shell", "markdown"];
  expect(rows).toEqual([
    ...kinds.map((kind) => [kind, `${HARD.lines[kind]} lines`, `${WARN.lines[kind]} lines`]),
    [
      "comment block",
      "never fails",
      `${COMMENT_CAPS.block} lines; ${COMMENT_CAPS.header} for the file header`,
    ],
  ]);
});
