- Deno: `deno install`, `deno test`, `deno task <task>` (tasks, imports, and lint/format settings in `deno.json`)
- `.dvmrc` is managed by sync; pin another version in a repo-owned workflow's version input, not in the dotfile.
