#!/usr/bin/env bun
// Reads the target's live data: default branch and private flag to
// GITHUB_OUTPUT; description, homepage, and comma-joined topics to RUNNER_TEMP
// files (step outputs leak into env-group prints). Hidden targets' values are
// masked BEFORE anything is written. Resolves the delivery mode too: a
// dispatch naming a `branch` (read off the event payload, never a step
// input) puts the sync in branch mode - checkout_ref is that branch and the
// render lands on it - after refusing the default branch and a branch the
// target does not have.
//
// Env: TARGET, TARGET_DISPLAY, HIDE_DETAILS, GH_TOKEN, RUNNER_TEMP,
// GITHUB_OUTPUT, GITHUB_EVENT_PATH (TARGET_BRANCH overrides the payload).
// Outputs: default_branch, private, mode (default|branch), checkout_ref,
// branch (empty in default mode).

import { writeFileSync, writeSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { readDispatchBranch } from "../fleet/discovery.ts";
import { addMask, env, error, hideDetails, requireEnv, setOutput } from "../shared/gha.ts";
import { parseJsonWith } from "../shared/json.ts";
import { capture } from "../shared/proc.ts";
import { AUTOMATION_BRANCH } from "./automation_branch.ts";

const target = requireEnv("TARGET");
// capture() pipes stderr (the hang bound needs the pipe); re-emit it whole
// so gh's own diagnostics still reach the log as before - with writeSync,
// because an async stream write racing the process.exit below truncates at
// the pipe buffer (~64 KiB).
const proc = capture(["gh", "api", `repos/${target}`]);
writeSync(2, proc.stderr);
if (proc.exitCode !== 0) {
  const display = env("TARGET_DISPLAY");
  error(
    proc.timedOut
      ? `cannot read ${display}: the repository read timed out (proc.ts hang bound); re-run the sync`
      : `cannot read ${display}: the REPO_PLATFORM_TOKEN cannot access it. ` +
          `Grant the PAT access to ${display} (repository access list) with Contents and Pull requests read/write, then re-run.`,
  );
  process.exit(1);
}
const info = parseJsonWith(
  z.object({
    default_branch: z.string(),
    description: z.string().nullable(),
    homepage: z.string().nullable(),
    topics: z.array(z.string()),
    private: z.boolean(),
  }),
  proc.stdout,
  "read_target: repos/<target> response",
);
const branch = info.default_branch;
const description = info.description ?? "";
const homepage = info.homepage ?? "";
// The starter's `topics` answer is the comma-separated form copier asks for.
const topics = info.topics.join(",");
const runnerTemp = requireEnv("RUNNER_TEMP");
writeFileSync(join(runnerTemp, "description.txt"), `${description}\n`);
writeFileSync(join(runnerTemp, "homepage.txt"), `${homepage}\n`);
writeFileSync(join(runnerTemp, "topics.txt"), `${topics}\n`);
if (hideDetails()) {
  // addMask escapes %/CR/LF (workflow-command data is single-line). Short
  // values stay unmasked: a three-letter topic would garble every log line.
  for (const value of [description, homepage, ...info.topics]) {
    if (value.length >= 4) addMask(value);
  }
  // An unusual branch name is target-derived, whatever its length; only
  // main/master stay unmasked (masking those would garble every log line
  // containing them, and they disclose nothing).
  if (branch !== "main" && branch !== "master") {
    addMask(branch);
  }
}
setOutput("default_branch", branch);
setOutput("private", String(info.private));

const targetBranch = readDispatchBranch();
if (targetBranch !== "") {
  if (hideDetails()) addMask(targetBranch);
  const display = env("TARGET_DISPLAY");
  const shown = hideDetails() ? "(name hidden: private repository)" : `'${targetBranch}'`;
  if (targetBranch === branch) {
    error(
      `branch ${shown} is ${display}'s default branch: the default branch is synced through a sync PR (dispatch without branch); the branch mode renders onto a PR's branch.`,
    );
    process.exit(1);
  }
  if (targetBranch === AUTOMATION_BRANCH) {
    error(
      `branch ${AUTOMATION_BRANCH} is the sync's own rolling branch: it is regenerated by a dispatch without branch, never rendered onto.`,
    );
    process.exit(1);
  }
  // The branch must exist before anything renders for it: a checkout of a
  // missing ref would fail later with a less specific message. Encoded per
  // segment: a `#` or `?` in a valid branch name would end the path early,
  // while the slashes stay slashes (the endpoint takes them either way).
  // The encoded spelling is target-derived too, so it is masked alongside.
  const encoded = targetBranch.split("/").map(encodeURIComponent).join("/");
  if (hideDetails() && encoded !== targetBranch) addMask(encoded);
  const probe = capture(["gh", "api", `repos/${target}/branches/${encoded}`, "--silent"]);
  if (probe.exitCode !== 0) {
    if (/\bHTTP 404\b/.test(probe.stderr) && !probe.timedOut) {
      error(`${display} has no branch ${shown}; push the branch first, then re-run.`);
    } else {
      // gh's stderr quotes the request path; a hidden target's stays off
      // the public log entirely.
      if (hideDetails()) console.log("(gh output hidden: private repository)");
      else writeSync(2, probe.stderr);
      error(
        probe.timedOut
          ? `reading ${display}'s branch ${shown} timed out (proc.ts hang bound); re-run the sync`
          : `cannot read ${display}'s branch ${shown} (gh exit ${probe.exitCode}); the REPO_PLATFORM_TOKEN must read the repository`,
      );
    }
    process.exit(1);
  }
}
setOutput("mode", targetBranch === "" ? "default" : "branch");
setOutput("checkout_ref", targetBranch === "" ? branch : targetBranch);
setOutput("branch", targetBranch);
