#!/usr/bin/env bun

// A comment line is one COMMENT_LINE matches (actions/shared/managed_header.ts): read by prefix, whatever the language,
// never by grammar. The caps that reading feeds are the warn tier, so a string line opening with `//` counts toward a
// warning at most.
// Policy: docs/fleet-guidelines.md.

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { workflowCommand } from "../shared/action_runtime.ts";
import { loadAllowlist, staleEntries } from "../shared/allowlist.ts";
import { type Outcome as CheckOutcome, runCheck } from "../shared/check_main.ts";
import { COMMENT_LINE, headerLines, isManaged } from "../shared/managed_header.ts";
import { PLATFORM_NAME } from "../shared/platform.ts";
import { repositoryFiles } from "../shared/repository_files.ts";

export type Kind = "source" | "test" | "workflow" | "shell" | "markdown";
export type Tier = "hard" | "warn";
/** The header is the first comment block when no code precedes it (a
 *  shebang or a generated region may); every other block is judged as a
 *  block. */
export type CommentScope = "header" | "block";

export interface Caps {
  lines: Readonly<Record<Kind, number>>;
}

export const HARD: Caps = {
  lines: { source: 2000, test: 3200, workflow: 1000, shell: 1000, markdown: 1300 },
};
const WARN_RATIO = 0.8;
/** The annotating tier: derived from HARD so the two can never disagree. */
export const WARN: Caps = {
  lines: Object.fromEntries(
    Object.entries(HARD.lines).map(([kind, cap]) => [kind, Math.round(cap * WARN_RATIO)]),
  ) as Caps["lines"],
};
/** Maximum line width, in code points, for every kind but PROSE: one tier, a
 *  failure. Below it, line length is the per-language formatter's to judge. */
export const HARD_WIDTH = 256;
/** Maximum comment block length, in lines, by scope: one annotating tier,
 *  never a failure, so not derived from any hard cap. Fleet-wide, like every
 *  cap here: the fleet takes the action from `@stable`. */
export const COMMENT_CAPS: Readonly<Record<CommentScope, number>> = { block: 10, header: 25 };
/** The per-block exemption, on a comment line inside the block (a comment
 *  line directly above it is part of it); the reason after it is mandatory. */
export const COMMENT_MARKER = "comment-cap: ignore";
/** Prose has no width cap and no comment cap: the fleet writes one source
 *  line per paragraph, so its lines are long by design, and its `#` headings
 *  are not comments. */
const PROSE: Kind = "markdown";

export const ALLOWLIST_FILE = ".file-size-allow.local";

const SOURCE_EXTENSIONS = new Set([
  "ts",
  "tsx",
  "mts",
  "cts",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "pyi",
  "rs",
  "go",
  "swift",
  "kt",
  "java",
  "c",
  "h",
  "cpp",
  "cc",
  "cxx",
  "hh",
  "hpp",
]);
const SHELL_EXTENSIONS = new Set(["sh", "bash", "zsh"]);
const TEST_DIRS = new Set(["test", "tests", "__tests__"]);
/** Test files by name: the JS/Python/Go conventions, and Rust's sibling
 *  test modules (`foo_tests.rs`, `tests.rs`, `proptests.rs`). */
const TEST_NAME =
  /(\.test\.|_test\.|\.spec\.|_spec\.|^test_|_tests\.rs$|^tests\.rs$|^proptests\.rs$)/;
/** Directory names whose contents are vendored or generated wholesale. */
const EXEMPT_DIRS = new Set(["node_modules", "vendor", "third_party", "goldens", "__snapshots__"]);

/** Only comment lines count and only these phrasings match; a generator's path is no signal, since hand-written
 *  headers name the generators they serve.
 *    "do not edit" inside a string literal        -> not a header
 *    "copies generated from the manifests" prose  -> no phrasing matches
 */
const GENERATED_HEADER =
  /\b(generated by|auto-?generated|this file is generated|generated file|do not edit)\b/i;
/** Marker-fenced generated regions inside otherwise hand-written files. */
const REGION_BEGIN = /\bBEGIN GENERATED\b/;
const REGION_END = /\bEND GENERATED\b/;

function extensionOf(relPath: string): string {
  const name = relPath.slice(relPath.lastIndexOf("/") + 1);
  const dot = name.lastIndexOf(".");
  return dot === -1 ? "" : name.slice(dot + 1).toLowerCase();
}

/** The kind a tracked path is judged as, or null when it is exempt. */
export function classify(relPath: string): Kind | null {
  const segments = relPath.split("/");
  const dirs = segments.slice(0, -1);
  if (dirs.some((dir) => EXEMPT_DIRS.has(dir))) return null;
  const name = segments[segments.length - 1];
  const ext = extensionOf(relPath);
  const workflowsDir =
    dirs.length >= 2 &&
    dirs[dirs.length - 2] === ".github" &&
    dirs[dirs.length - 1] === "workflows";
  if ((workflowsDir && (ext === "yml" || ext === "yaml")) || /^action\.ya?ml$/.test(name)) {
    return "workflow";
  }
  if (SHELL_EXTENSIONS.has(ext)) return "shell";
  if (ext === "md") return "markdown";
  if (SOURCE_EXTENSIONS.has(ext)) {
    return TEST_NAME.test(name) || dirs.some((dir) => TEST_DIRS.has(dir)) ? "test" : "source";
  }
  return null;
}

export function isGenerated(text: string): boolean {
  return headerLines(text).some((line) => COMMENT_LINE.test(line) && GENERATED_HEADER.test(line));
}

/** Lines without their terminators: a final newline adds no line, and a
 *  CRLF file's `\r` is not width. */
function splitLines(text: string): string[] {
  const lines = text.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
  if (lines[lines.length - 1] === "") lines.pop();
  return lines;
}

/** A line wrapping cannot fix: one whitespace-free token (a URL, a sha, a
 *  path, an expression), indentation aside. */
export function isUnbreakable(line: string): boolean {
  const token = line.trim();
  return token !== "" && !/\s/.test(token);
}

function generatedRegionMask(lines: string[]): boolean[] {
  const mask = lines.map(() => false);
  let begin = -1;
  lines.forEach((line, index) => {
    if (begin === -1) {
      if (!REGION_BEGIN.test(line)) return;
      if (REGION_END.test(line)) mask[index] = true;
      else begin = index;
    } else if (REGION_END.test(line)) {
      for (let i = begin; i <= index; i++) mask[i] = true;
      begin = -1;
    }
  });
  return mask;
}

/** A shebang is `#!` and an interpreter path. Rust's `#![...]` attribute is not one. */
const SHEBANG = /^#!\s*\//;

interface CommentBlock {
  /** The block's first line, 1-based. */
  line: number;
  length: number;
  scope: CommentScope;
  /** Every exemption marker in the block: its 1-based line and the text after
   *  it on that line, up to the next marker. */
  markers: { line: number; reason: string }[];
}

const MARKER = new RegExp(`\\b${COMMENT_MARKER}\\b`, "g");
/** A reason has a letter or digit in it, in any script: a closing delimiter alone after the marker is none. */
const REASONED = /[\p{L}\p{N}]/u;

/** A shebang is neither code nor comment, and a generated line ends a run
 *  without demoting the header after it. */
function commentBlocks(lines: readonly string[], skip: readonly boolean[]): CommentBlock[] {
  const blocks: CommentBlock[] = [];
  let start = -1;
  let headerAhead = true;
  const end = (at: number): void => {
    if (start === -1) return;
    const markers: CommentBlock["markers"] = [];
    for (let row = start; row < at; row++) {
      const matches = [...lines[row].matchAll(MARKER)];
      matches.forEach((match, i) => {
        const from = match.index + match[0].length;
        markers.push({
          line: row + 1,
          reason: lines[row].slice(from, matches[i + 1]?.index).trim(),
        });
      });
    }
    blocks.push({
      line: start + 1,
      length: at - start,
      scope: headerAhead ? "header" : "block",
      markers,
    });
    start = -1;
    headerAhead = false;
  };
  lines.forEach((line, row) => {
    if (skip[row] || line.trim() === "") {
      end(row);
    } else if (row === 0 && SHEBANG.test(line)) {
      return;
    } else if (COMMENT_LINE.test(line)) {
      if (start === -1) start = row;
    } else {
      end(row);
      headerAhead = false;
    }
  });
  end(lines.length);
  return blocks;
}

interface FindingBase {
  path: string;
  kind: Kind;
  tier: Tier;
}
interface Measured {
  value: number;
  cap: number;
}
/** `line` is 1-based. */
export type Finding =
  | (FindingBase & Measured & { measure: "lines" })
  | (FindingBase & Measured & { measure: "width"; tier: "hard"; line: number })
  | (FindingBase &
      Measured & { measure: "comment"; tier: "warn"; line: number; scope: CommentScope })
  | (FindingBase & { measure: "marker"; tier: "warn"; line: number });

function exceeded(value: number, hard: number, warn: number): { tier: Tier; cap: number } | null {
  if (value > hard) return { tier: "hard", cap: hard };
  if (value > warn) return { tier: "warn", cap: warn };
  return null;
}

export function judgeFile(path: string, kind: Kind, text: string): Finding[] {
  const findings: Finding[] = [];
  const lines = splitLines(text);
  const generated = generatedRegionMask(lines);
  const counted = generated.filter((inRegion) => !inRegion).length;
  const lineCount = exceeded(counted, HARD.lines[kind], WARN.lines[kind]);
  if (lineCount !== null) {
    findings.push({ path, kind, ...lineCount, measure: "lines", value: counted });
  }
  if (kind === PROSE) return findings;
  lines.forEach((line, index) => {
    if (generated[index] || isUnbreakable(line)) return;
    const width = [...line].length;
    if (width <= HARD_WIDTH) return;
    findings.push({
      path,
      kind,
      tier: "hard",
      measure: "width",
      line: index + 1,
      value: width,
      cap: HARD_WIDTH,
    });
  });
  for (const { line, length, scope, markers } of commentBlocks(lines, generated)) {
    for (const marker of markers) {
      if (!REASONED.test(marker.reason)) {
        findings.push({ path, kind, tier: "warn", measure: "marker", line: marker.line });
      }
    }
    if (markers.some((marker) => REASONED.test(marker.reason))) continue;
    const cap = COMMENT_CAPS[scope];
    if (length > cap) {
      findings.push({
        path,
        kind,
        tier: "warn",
        measure: "comment",
        line,
        value: length,
        cap,
        scope,
      });
    }
  }
  return findings;
}

export function describe(finding: Finding): string {
  switch (finding.measure) {
    case "lines":
      return `${finding.path}: ${finding.value} lines (cap ${finding.cap} for ${finding.kind})`;
    case "width":
      return `${finding.path}:${finding.line}: ${finding.value} chars (cap ${finding.cap})`;
    case "comment": {
      const scope = finding.scope === "header" ? " for a header" : "";
      return `${finding.path}:${finding.line}: ${finding.value} comment lines (cap ${finding.cap}${scope})`;
    }
    case "marker":
      return `${finding.path}:${finding.line}: ${COMMENT_MARKER} needs a reason`;
  }
}

function sizeCells(finding: Finding): [size: string, cap: string] {
  switch (finding.measure) {
    case "lines":
      return [`${finding.value} lines`, `${finding.cap}`];
    case "width":
      return [`${finding.value} chars`, `${finding.cap}`];
    case "comment": {
      const scope = finding.scope === "header" ? " (header)" : "";
      return [`${finding.value} comment lines${scope}`, `${finding.cap}`];
    }
    case "marker":
      return [`${COMMENT_MARKER} without a reason`, "-"];
  }
}

export const REASON_RULE =
  "an allowlist entry needs a reason a reader accepts (vendored or upstream-shaped, generated but missed by the header exemption, a split that would break an external contract)";

export interface Verdict {
  /** Hard-tier findings on files the allowlist does not name. */
  failures: (Finding & { tier: "hard" })[];
  /** Warn-tier findings on files the allowlist does not name. */
  warnings: (Finding & { tier: "warn" })[];
  /** Allowlist defects: entries without a reason, and stale entries. */
  allowlistErrors: string[];
  /** Files skipped for carrying the platform's managed header: a fleet repository cannot fix such a file. */
  managedSkipped: number;
}

export function check(root: string): Verdict {
  const allow = loadAllowlist(root, ALLOWLIST_FILE, REASON_RULE);
  const { allowed } = allow;
  const findings: Finding[] = [];
  const found = new Set<string>();
  let managedSkipped = 0;
  for (const relPath of repositoryFiles(root, { untracked: false })) {
    const kind = classify(relPath);
    if (kind === null) continue;
    const text = readFileSync(join(root, relPath), "utf-8");
    if (isGenerated(text)) continue;
    if (isManaged(text)) {
      managedSkipped += 1;
      continue;
    }
    const judged = judgeFile(relPath, kind, text);
    if (judged.length === 0) continue;
    found.add(relPath);
    if (!allowed.has(relPath)) findings.push(...judged);
  }
  const allowlistErrors = [
    ...allow.failures,
    ...staleEntries(allow, found, ALLOWLIST_FILE, "under every cap"),
  ];
  return {
    failures: findings.filter(
      (finding): finding is Finding & { tier: "hard" } => finding.tier === "hard",
    ),
    warnings: findings.filter(
      (finding): finding is Finding & { tier: "warn" } => finding.tier === "warn",
    ),
    allowlistErrors,
    managedSkipped,
  };
}

/** The three outcomes the action distinguishes (its `report` output). */
export type Outcome = CheckOutcome<Verdict>;

export function outcomeOf(verdict: Verdict): Outcome {
  const { failures, warnings, allowlistErrors } = verdict;
  const silent = failures.length + warnings.length + allowlistErrors.length === 0;
  return { state: silent ? "clean" : "findings", verdict };
}

export function report(outcome: Outcome): string {
  const parts = ["## File size check", ""];
  if (outcome.state === "error") {
    parts.push(`The check did not run to completion: ${outcome.message}`);
    return `${parts.join("\n")}\n`;
  }
  const { failures, warnings, allowlistErrors, managedSkipped } = outcome.verdict;
  if (outcome.state === "clean") {
    parts.push("Every file is under its caps.");
  } else {
    parts.push(`${failures.length} over a hard cap (fails), ${warnings.length} warning(s).`);
    const rows = [...failures, ...warnings].map((finding) => {
      const where = finding.measure === "lines" ? finding.path : `${finding.path}:${finding.line}`;
      const [size, cap] = sizeCells(finding);
      return `| \`${where}\` | ${size} | ${finding.tier} | ${cap} |`;
    });
    if (rows.length > 0) {
      parts.push("", "| File | Size | Tier | Cap |", "| --- | --- | --- | --- |", ...rows);
    }
    if (allowlistErrors.length > 0) {
      parts.push("", `### ${ALLOWLIST_FILE}`, "", ...allowlistErrors.map((error) => `- ${error}`));
    }
    parts.push(
      "",
      `Split the file, wrap the line, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`,
    );
  }
  if (managedSkipped > 0) {
    parts.push("", `${managedSkipped} managed file(s) skipped; ${PLATFORM_NAME} owns them.`);
  }
  return `${parts.join("\n")}\n`;
}

const REMEDY = `Split the file, wrap the line, shorten or exempt the comment, or list the path in ${ALLOWLIST_FILE} with a '# reason'.`;

if (import.meta.main) {
  await runCheck<Verdict>({
    name: "check-file-size",
    check,
    outcomeOf,
    report,
    warnings: (verdict) =>
      verdict.warnings.map((warning) => workflowCommand("warning", describe(warning))),
    errors: (verdict) =>
      [...verdict.failures.map(describe), ...verdict.allowlistErrors].map((failure) =>
        workflowCommand("error", failure),
      ),
    passed: (verdict) =>
      `File size check passed (${verdict.warnings.length} warning(s), ${verdict.managedSkipped} managed file(s) skipped).`,
    failed: (count) => `${count} finding(s). ${REMEDY}`,
  });
}
