#!/usr/bin/env bun

// Comments and literals are exactly what the file's tree-sitter grammar tokenizes; every other token, ERROR included, is code.
// Policy: docs/fleet-guidelines.md.

import {
  appendFileSync,
  existsSync,
  lstatSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { Language, Parser, type Tree } from "web-tree-sitter";

export type Kind = "source" | "test" | "workflow" | "shell" | "markdown";
export type Tier = "hard" | "warn";
/** The header is the first comment block when no code precedes it (a
 *  shebang or a generated region may); every other block is judged as a
 *  block. */
export type CommentScope = "header" | "block";

export interface Caps {
  lines: Readonly<Record<Kind, number>>;
  /** Maximum line width, in code points, for the kinds in WIDTH_KINDS. */
  width: number;
}

export const HARD: Caps = {
  lines: { source: 2000, test: 3200, workflow: 1000, shell: 1000, markdown: 1300 },
  width: 256,
};
const WARN_RATIO = 0.8;
/** The annotating tier: line caps derived from HARD so the two can never
 *  disagree; the width cap stays well under the hard one, since a long
 *  shell or yaml string is what it exists to catch. */
export const WARN: Caps = {
  lines: Object.fromEntries(
    Object.entries(HARD.lines).map(([kind, cap]) => [kind, Math.round(cap * WARN_RATIO)]),
  ) as Caps["lines"],
  width: 150,
};
/** Maximum comment block length, in lines, by scope: one annotating tier,
 *  never a failure, so not derived from any hard cap. Fleet-wide, like every
 *  cap here: the fleet takes the action from `@build`. */
export const COMMENT_CAPS: Readonly<Record<CommentScope, number>> = { block: 10, header: 25 };
/** The per-block exemption, on a comment line inside the block (a comment
 *  line directly above it is part of it); the reason after it is mandatory. */
export const COMMENT_MARKER = "comment-cap: ignore";
/** Prose (markdown) has no width cap: the fleet writes one source line per
 *  paragraph, so its lines are long by design. */
export const WIDTH_KINDS: ReadonlySet<Kind> = new Set(["source", "test", "workflow", "shell"]);

export const ALLOWLIST_FILE = ".file-size-allow.local";

const SOURCE_EXTENSIONS = new Set([
  "ts",
  "tsx",
  "mts",
  "cts",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "pyi",
  "rs",
  "go",
  "swift",
  "kt",
  "java",
  "c",
  "h",
  "cpp",
  "cc",
  "cxx",
  "hh",
  "hpp",
]);
const SHELL_EXTENSIONS = new Set(["sh", "bash", "zsh"]);
/** Every extension whose files get comment and literal judgement. Markdown is prose and needs no grammar. */
const JUDGED_EXTENSIONS: ReadonlySet<string> = new Set([
  ...SOURCE_EXTENSIONS,
  ...SHELL_EXTENSIONS,
  "yml",
  "yaml",
]);
const TEST_DIRS = new Set(["test", "tests", "__tests__"]);
/** Test files by name: the JS/Python/Go conventions, and Rust's sibling
 *  test modules (`foo_tests.rs`, `tests.rs`, `proptests.rs`). */
const TEST_NAME =
  /(\.test\.|_test\.|\.spec\.|_spec\.|^test_|_tests\.rs$|^tests\.rs$|^proptests\.rs$)/;
/** Directory names whose contents are vendored or generated wholesale. */
const EXEMPT_DIRS = new Set(["node_modules", "vendor", "third_party", "goldens", "__snapshots__"]);

/** Only comment lines count and only these phrasings match; a generator's path is no signal, since hand-written
 *  headers name the generators they serve.
 *    "do not edit" inside a string literal        -> not a header
 *    "copies generated from the manifests" prose  -> no phrasing matches
 */
const HEADER_LINES = 10;
const COMMENT_LINE = /^\s*(#|\/\/|\/\*|\*|<!--|--|;|%|\{#|"""|''')/;
const GENERATED_HEADER =
  /\b(generated by|auto-?generated|this file is generated|generated file|do not edit)\b/i;
/** The header every file repo-platform manages carries (the text
 *  validate-managed-files checks): a fleet repository cannot fix such a file. */
const MANAGED_HEADER = /\bThis file is managed by [\w.-]+\/repo-platform\b/;
/** Marker-fenced generated regions inside otherwise hand-written files. */
const REGION_BEGIN = /\bBEGIN GENERATED\b/;
const REGION_END = /\bEND GENERATED\b/;

function extensionOf(relPath: string): string {
  const name = relPath.slice(relPath.lastIndexOf("/") + 1);
  const dot = name.lastIndexOf(".");
  return dot === -1 ? "" : name.slice(dot + 1).toLowerCase();
}

/** The kind a tracked path is judged as, or null when it is exempt. */
export function classify(relPath: string): Kind | null {
  const segments = relPath.split("/");
  const dirs = segments.slice(0, -1);
  if (dirs.some((dir) => EXEMPT_DIRS.has(dir))) return null;
  const name = segments[segments.length - 1];
  const ext = extensionOf(relPath);
  const workflowsDir =
    dirs.length >= 2 &&
    dirs[dirs.length - 2] === ".github" &&
    dirs[dirs.length - 1] === "workflows";
  if ((workflowsDir && (ext === "yml" || ext === "yaml")) || /^action\.ya?ml$/.test(name)) {
    return "workflow";
  }
  if (SHELL_EXTENSIONS.has(ext)) return "shell";
  if (ext === "md") return "markdown";
  if (SOURCE_EXTENSIONS.has(ext)) {
    return TEST_NAME.test(name) || dirs.some((dir) => TEST_DIRS.has(dir)) ? "test" : "source";
  }
  return null;
}

function headerLines(text: string): string[] {
  return text.split("\n", HEADER_LINES);
}

export function isGenerated(text: string): boolean {
  return headerLines(text).some((line) => COMMENT_LINE.test(line) && GENERATED_HEADER.test(line));
}

export function isManaged(text: string): boolean {
  return headerLines(text).some((line) => COMMENT_LINE.test(line) && MANAGED_HEADER.test(line));
}

/** Lines without their terminators: a final newline adds no line, and a
 *  CRLF file's `\r` is not width. */
function splitLines(text: string): string[] {
  const lines = text.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
  if (lines[lines.length - 1] === "") lines.pop();
  return lines;
}

/** A line wrapping cannot fix: one whitespace-free token (a URL, a sha, a
 *  path, an expression), indentation aside. */
export function isUnbreakable(line: string): boolean {
  const token = line.trim();
  return token !== "" && !/\s/.test(token);
}

function generatedRegionMask(lines: string[]): boolean[] {
  const mask = lines.map(() => false);
  let begin = -1;
  lines.forEach((line, index) => {
    if (begin === -1) {
      if (!REGION_BEGIN.test(line)) return;
      if (REGION_END.test(line)) mask[index] = true;
      else begin = index;
    } else if (REGION_END.test(line)) {
      for (let i = begin; i <= index; i++) mask[i] = true;
      begin = -1;
    }
  });
  return mask;
}

// The per-language surface is this table and nothing else.
// JS's html_comment is null: `<!-- a -->` and a line-start `-->` both run to the line end, so `-->` is text.
interface Delimiters {
  open: string;
  close: string;
}
interface GrammarSpec {
  wasm: string;
  comments: Readonly<Record<string, Delimiters | null>>;
  /** Token types the warn width tier leaves alone. */
  literals: readonly string[];
}

const PACKAGES = join(import.meta.dir, "node_modules");
// tree-sitter-wasms 0.1.13 loads only under web-tree-sitter 0.25.x: 0.26 rejects its dylink format.
const prebuilt = (name: string): string =>
  join(PACKAGES, "tree-sitter-wasms", "out", `tree-sitter-${name}.wasm`);
const STARRED: Delimiters = { open: "/*", close: "*/" };
const JS: Omit<GrammarSpec, "wasm"> = {
  comments: { comment: STARRED, html_comment: null },
  literals: ["string", "template_string", "template_literal_type", "regex"],
};
const C_LIKE: Omit<GrammarSpec, "wasm"> = {
  comments: { comment: STARRED },
  literals: ["string_literal", "raw_string_literal", "char_literal"],
};
const GRAMMARS = {
  typescript: { wasm: prebuilt("typescript"), ...JS },
  tsx: { wasm: prebuilt("tsx"), ...JS },
  javascript: { wasm: prebuilt("javascript"), ...JS },
  python: { wasm: prebuilt("python"), comments: { comment: null }, literals: ["string"] },
  rust: {
    wasm: prebuilt("rust"),
    comments: { line_comment: null, block_comment: STARRED },
    literals: C_LIKE.literals,
  },
  go: {
    wasm: prebuilt("go"),
    comments: C_LIKE.comments,
    literals: ["interpreted_string_literal", "raw_string_literal", "rune_literal"],
  },
  c: { wasm: prebuilt("c"), ...C_LIKE },
  cpp: { wasm: prebuilt("cpp"), ...C_LIKE },
  java: {
    wasm: prebuilt("java"),
    comments: { line_comment: null, block_comment: STARRED },
    literals: ["string_literal", "character_literal"],
  },
  kotlin: {
    wasm: prebuilt("kotlin"),
    comments: { line_comment: null, multiline_comment: STARRED },
    literals: ["string_literal", "character_literal"],
  },
  // The tree-sitter-wasms bash build imports libc isalpha, which the loader lacks: `case` and `[[` crash the parse.
  bash: {
    wasm: join(PACKAGES, "tree-sitter-bash", "tree-sitter-bash.wasm"),
    comments: { comment: null },
    literals: ["string", "raw_string", "ansi_c_string", "regex"],
  },
  // The tree-sitter-wasms yaml build crashes at parse time under every loader that accepts the others.
  yaml: {
    wasm: join(PACKAGES, "@tree-sitter-grammars", "tree-sitter-yaml", "tree-sitter-yaml.wasm"),
    comments: { comment: null },
    literals: ["double_quote_scalar", "single_quote_scalar"],
  },
} satisfies Record<string, GrammarSpec>;
type GrammarName = keyof typeof GRAMMARS;

/** Why a judged extension has no grammar. Its files get no comment judgement and no literal exemption. */
export interface Unjudged {
  reason: string;
}

// C headers go to C++, the superset.
const EXTENSION_GRAMMAR: Readonly<Record<string, GrammarName | Unjudged>> = {
  ts: "typescript",
  mts: "typescript",
  cts: "typescript",
  tsx: "tsx",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  py: "python",
  pyi: "python",
  rs: "rust",
  go: "go",
  swift: {
    reason:
      "the prebuilt Swift grammar keeps scanner state across files, so a raw string in one file changes how the next file tokenizes",
  },
  kt: "kotlin",
  java: "java",
  c: "c",
  h: "cpp",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hh: "cpp",
  hpp: "cpp",
  sh: "bash",
  bash: "bash",
  zsh: "bash",
  yml: "yaml",
  yaml: "yaml",
};

export interface Grammar {
  /** One parser per grammar per run. */
  parser: Parser;
  /** Comment node type to the delimiters that end a marker's reason, or null. */
  comments: ReadonlyMap<string, Delimiters | null>;
  literals: ReadonlySet<string>;
}

/** By judged extension: its grammar, or why it has none. */
export type Grammars = ReadonlyMap<string, Grammar | Unjudged>;

/** Every grammar's wasm, for the guard that its imports resolve against the runtime. */
export const GRAMMAR_WASMS: readonly string[] = Object.values(GRAMMARS).map((spec) => spec.wasm);

async function loadGrammar(spec: GrammarSpec): Promise<Grammar | Unjudged> {
  try {
    const parser = new Parser();
    parser.setLanguage(await Language.load(spec.wasm));
    return {
      parser,
      comments: new Map(Object.entries(spec.comments)),
      literals: new Set(spec.literals),
    };
  } catch (error) {
    return { reason: `${spec.wasm}: ${error instanceof Error ? error.message : String(error)}` };
  }
}

export async function loadGrammars(): Promise<Grammars> {
  await Parser.init();
  const loaded = new Map<GrammarName, Grammar | Unjudged>();
  const grammars = new Map<string, Grammar | Unjudged>();
  for (const ext of [...JUDGED_EXTENSIONS].sort()) {
    const name = EXTENSION_GRAMMAR[ext] ?? { reason: "no grammar maps this extension" };
    if (typeof name !== "string") {
      grammars.set(ext, name);
      continue;
    }
    const grammar = loaded.get(name) ?? (await loadGrammar(GRAMMARS[name]));
    loaded.set(name, grammar);
    grammars.set(ext, grammar);
  }
  return grammars;
}

/** A shebang is `#!` and an interpreter path. Rust's `#![...]` attribute is code. */
const SHEBANG = /^#!\s*\//;

interface Token {
  // Named and anonymous are tree-sitter's leaf classes: an identifier is named, punctuation and keywords are anonymous.
  kind: "comment" | "literal" | "key" | "named" | "anonymous" | "shebang";
  /** The grammar's node type. */
  type: string;
  startRow: number;
  /** The last row it puts a character on. */
  endRow: number;
  /** Set for comments (read for the exemption markers) and for row-0 tokens (read for the shebang). */
  text?: string;
}

// Some grammars put the `key` field on a wrapper spanning exactly the literal (yaml's flow_node).
interface Ancestor {
  field: string | null;
  startIndex: number;
  endIndex: number;
}

/** The tree's tokens in document order. Whitespace and zero-width (MISSING) leaves are dropped. */
function tokenize(tree: Tree, grammar: Grammar): Token[] {
  const tokens: Token[] = [];
  const ancestors: Ancestor[] = [];
  const cursor = tree.walk();
  let descend = true;
  for (;;) {
    if (descend) {
      const type = cursor.nodeType;
      const field = cursor.currentFieldName;
      const startIndex = cursor.startIndex;
      const endIndex = cursor.endIndex;
      // Only named nodes can be comments or literals: TypeScript's `string` type keyword is an anonymous node of that type.
      const named = cursor.nodeIsNamed;
      const whole = named && (grammar.comments.has(type) || grammar.literals.has(type));
      if (!whole && cursor.gotoFirstChild()) {
        ancestors.push({ field, startIndex, endIndex });
        continue;
      }
      const start = cursor.startPosition;
      const end = cursor.endPosition;
      if (startIndex !== endIndex && type.trim() !== "") {
        let kind: Token["kind"] = !named
          ? "anonymous"
          : grammar.comments.has(type)
            ? "comment"
            : grammar.literals.has(type)
              ? "literal"
              : "named";
        if (kind === "literal" && isKey(field, ancestors, startIndex, endIndex)) kind = "key";
        const endRow = end.column === 0 && end.row > start.row ? end.row - 1 : end.row;
        const token: Token = { kind, type, startRow: start.row, endRow };
        if (kind === "comment" || start.row === 0) token.text = cursor.nodeText;
        if (start.row === 0 && kind !== "literal" && SHEBANG.test(token.text ?? "")) {
          token.kind = "shebang";
        }
        tokens.push(token);
      }
    }
    if (cursor.gotoNextSibling()) {
      descend = true;
      continue;
    }
    if (!cursor.gotoParent()) break;
    ancestors.pop();
    descend = false;
  }
  cursor.delete();
  return tokens;
}

function isKey(
  field: string | null,
  ancestors: readonly Ancestor[],
  startIndex: number,
  endIndex: number,
): boolean {
  if (field === "key") return true;
  for (let i = ancestors.length - 1; i >= 0; i--) {
    const wrapper = ancestors[i];
    if (wrapper.startIndex !== startIndex || wrapper.endIndex !== endIndex) return false;
    if (wrapper.field === "key") return true;
  }
  return false;
}

// A row takes its strongest token's kind, so a blank row inside a block comment is comment.
type RowKind = "blank" | "shebang" | "comment" | "code";
const ROW_RANK: Readonly<Record<RowKind, number>> = { blank: 0, shebang: 1, comment: 2, code: 3 };
const ROW_KIND: Readonly<Record<Token["kind"], RowKind>> = {
  comment: "comment",
  shebang: "shebang",
  literal: "code",
  key: "code",
  named: "code",
  anonymous: "code",
};

interface Analysis {
  rows: RowKind[];
  // Rows the warn width tier leaves alone.
  literalRows: boolean[];
  comments: Token[];
}

// Rows past `rowCount` are dropped: the parser sees an empty row after a final newline.
function analyze(grammar: Grammar, text: string, rowCount: number): Analysis {
  const tree = grammar.parser.parse(text);
  if (tree === null) throw new Error("tree-sitter returned no tree");
  let tokens: Token[];
  try {
    tokens = tokenize(tree, grammar);
  } finally {
    tree.delete();
  }
  const rows: RowKind[] = Array.from({ length: rowCount }, () => "blank");
  const rowTokens: Token[][] = Array.from({ length: rowCount }, () => []);
  for (const token of tokens) {
    const kind = ROW_KIND[token.kind];
    for (let row = token.startRow; row <= Math.min(token.endRow, rowCount - 1); row++) {
      if (ROW_RANK[kind] > ROW_RANK[rows[row]]) rows[row] = kind;
      rowTokens[row].push(token);
    }
  }
  const literalRows = rowTokens.map((onRow) => {
    const at = onRow.findIndex((token) => token.kind === "literal");
    if (at === -1 || onRow.some((token) => token.kind === "comment")) return false;
    const before = onRow[at - 1];
    if (before !== undefined && before.kind !== "anonymous") return false;
    return onRow.slice(at + 1).every((token) => token.kind === "anonymous");
  });
  return { rows, literalRows, comments: tokens.filter((token) => token.kind === "comment") };
}

interface CommentBlock {
  /** The block's first line, 1-based. */
  line: number;
  length: number;
  scope: CommentScope;
  /** Every exemption marker in the block: its 1-based line and the reason
   *  after it (empty for a bare marker, which exempts nothing). */
  markers: { line: number; reason: string }[];
}

const MARKER = new RegExp(`\\b${COMMENT_MARKER}\\b`, "g");

// The closer applies only when the token opens with its pair: JS's `comment` type covers `//` and `/* */` alike.
function commentBlocks(analysis: Analysis, grammar: Grammar, skip: boolean[]): CommentBlock[] {
  const { rows, comments } = analysis;
  const blocks: CommentBlock[] = [];
  const blockAt: (CommentBlock | undefined)[] = rows.map(() => undefined);
  let start = -1;
  let headerAhead = true;
  const end = (at: number): void => {
    if (start === -1) return;
    const block: CommentBlock = {
      line: start + 1,
      length: at - start,
      scope: headerAhead ? "header" : "block",
      markers: [],
    };
    blocks.push(block);
    for (let row = start; row < at; row++) blockAt[row] = block;
    start = -1;
    headerAhead = false;
  };
  rows.forEach((kind, row) => {
    if (skip[row] || kind === "blank") {
      end(row);
    } else if (kind === "code") {
      end(row);
      headerAhead = false;
    } else if (kind === "comment" && start === -1) {
      start = row;
    }
  });
  end(rows.length);
  for (const { type, startRow, text = "" } of comments) {
    const delimiters = grammar.comments.get(type) ?? null;
    const closers =
      delimiters !== null && text.startsWith(delimiters.open) ? [delimiters.close] : [];
    const matches = [...text.matchAll(MARKER)];
    matches.forEach((match, i) => {
      const row = startRow + (text.slice(0, match.index).match(/\n/g)?.length ?? 0);
      const block = blockAt[row];
      if (block === undefined) return;
      const from = match.index + match[0].length;
      const stops = ["\n", ...closers].map((stop) => text.indexOf(stop, from));
      stops.push(matches[i + 1]?.index ?? -1);
      const until = Math.min(...stops.filter((stop) => stop !== -1), text.length);
      block.markers.push({ line: row + 1, reason: text.slice(from, until).trim() });
    });
  }
  return blocks;
}

interface FindingBase {
  path: string;
  kind: Kind;
  tier: Tier;
}
interface Measured {
  value: number;
  cap: number;
}
/** `line` is 1-based. */
export type Finding =
  | (FindingBase & Measured & { measure: "lines" })
  | (FindingBase & Measured & { measure: "width"; line: number })
  | (FindingBase &
      Measured & { measure: "comment"; tier: "warn"; line: number; scope: CommentScope })
  | (FindingBase & { measure: "marker"; tier: "warn"; line: number });

function exceeded(value: number, hard: number, warn: number): { tier: Tier; cap: number } | null {
  if (value > hard) return { tier: "hard", cap: hard };
  if (value > warn) return { tier: "warn", cap: warn };
  return null;
}

export function judgeFile(path: string, kind: Kind, text: string, grammars: Grammars): Finding[] {
  const findings: Finding[] = [];
  const lines = splitLines(text);
  const generated = generatedRegionMask(lines);
  const found = grammars.get(extensionOf(path));
  const grammar = found !== undefined && "parser" in found ? found : null;
  const analysis = grammar === null ? null : analyze(grammar, text, lines.length);
  const counted = generated.filter((inRegion) => !inRegion).length;
  const lineCount = exceeded(counted, HARD.lines[kind], WARN.lines[kind]);
  if (lineCount !== null) {
    findings.push({ path, kind, ...lineCount, measure: "lines", value: counted });
  }
  if (WIDTH_KINDS.has(kind)) {
    lines.forEach((line, index) => {
      if (generated[index] || isUnbreakable(line)) return;
      const width = [...line].length;
      const over = exceeded(width, HARD.width, WARN.width);
      if (over === null || (over.tier === "warn" && analysis?.literalRows[index])) return;
      findings.push({ path, kind, ...over, measure: "width", line: index + 1, value: width });
    });
  }
  if (analysis !== null && grammar !== null) {
    for (const { line, length, scope, markers } of commentBlocks(analysis, grammar, generated)) {
      for (const marker of markers) {
        if (marker.reason === "") {
          findings.push({ path, kind, tier: "warn", measure: "marker", line: marker.line });
        }
      }
      if (markers.some((marker) => marker.reason !== "")) continue;
      const cap = COMMENT_CAPS[scope];
      if (length > cap) {
        findings.push({
          path,
          kind,
          tier: "warn",
          measure: "comment",
          line,
          value: length,
          cap,
          scope,
        });
      }
    }
  }
  return findings;
}

export function describe(finding: Finding): string {
  switch (finding.measure) {
    case "lines":
      return `${finding.path}: ${finding.value} lines (cap ${finding.cap} for ${finding.kind})`;
    case "width":
      return `${finding.path}:${finding.line}: ${finding.value} chars (cap ${finding.cap})`;
    case "comment": {
      const scope = finding.scope === "header" ? " for a header" : "";
      return `${finding.path}:${finding.line}: ${finding.value} comment lines (cap ${finding.cap}${scope})`;
    }
    case "marker":
      return `${finding.path}:${finding.line}: ${COMMENT_MARKER} needs a reason`;
  }
}

function sizeCells(finding: Finding): [size: string, cap: string] {
  switch (finding.measure) {
    case "lines":
      return [`${finding.value} lines`, `${finding.cap}`];
    case "width":
      return [`${finding.value} chars`, `${finding.cap}`];
    case "comment": {
      const scope = finding.scope === "header" ? " (header)" : "";
      return [`${finding.value} comment lines${scope}`, `${finding.cap}`];
    }
    case "marker":
      return [`${COMMENT_MARKER} without a reason`, "-"];
  }
}

export interface AllowEntry {
  path: string;
  reason: string;
  line: number;
}

export const REASON_RULE =
  "an allowlist entry needs a reason a reader accepts (vendored or upstream-shaped, generated but missed by the header exemption, a split that would break an external contract)";

export function parseAllowlist(text: string): { entries: AllowEntry[]; failures: string[] } {
  const entries: AllowEntry[] = [];
  const failures: string[] = [];
  splitLines(text).forEach((raw, index) => {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) return;
    const hash = line.indexOf("#");
    const path = (hash === -1 ? line : line.slice(0, hash)).trim();
    const reason = hash === -1 ? "" : line.slice(hash + 1).trim();
    if (reason === "") {
      failures.push(`${ALLOWLIST_FILE}:${index + 1}: '${path}' has no '# reason'; ${REASON_RULE}`);
      return;
    }
    entries.push({ path, reason, line: index + 1 });
  });
  return { entries, failures };
}

function trackedFiles(root: string): string[] {
  const args = ["git", "-C", root, "ls-files", "-z"];
  const proc = Bun.spawnSync(args, { stdout: "pipe", stderr: "pipe" });
  if (proc.exitCode !== 0) {
    throw new Error(`git ls-files failed in ${root}: ${proc.stderr.toString().trim()}`);
  }
  return proc.stdout
    .toString()
    .split("\0")
    .filter((path) => path !== "");
}

export interface Verdict {
  /** Hard-tier findings on files the allowlist does not name. */
  failures: (Finding & { tier: "hard" })[];
  /** Warn-tier findings on files the allowlist does not name. */
  warnings: (Finding & { tier: "warn" })[];
  /** Allowlist defects: entries without a reason, and stale entries. */
  allowlistErrors: string[];
  /** Files skipped for carrying repo-platform's managed header. */
  managedSkipped: number;
  unjudged: { extension: string; files: number; reason: string }[];
}

export function check(root: string, grammars: Grammars): Verdict {
  const allowFile = join(root, ALLOWLIST_FILE);
  const allow = existsSync(allowFile)
    ? parseAllowlist(readFileSync(allowFile, "utf-8"))
    : { entries: [], failures: [] };
  const allowed = new Set(allow.entries.map((entry) => entry.path));
  const findings: Finding[] = [];
  const found = new Set<string>();
  let managedSkipped = 0;
  const unjudged = new Map<string, Verdict["unjudged"][number]>();

  const judge = (relPath: string, kind: Kind, text: string): void => {
    const extension = extensionOf(relPath);
    const grammar = grammars.get(extension);
    if (grammar !== undefined && "reason" in grammar) {
      const entry = unjudged.get(extension) ?? { extension, files: 0, reason: grammar.reason };
      entry.files += 1;
      unjudged.set(extension, entry);
    }
    const judged = judgeFile(relPath, kind, text, grammars);
    if (judged.length === 0) return;
    found.add(relPath);
    if (!allowed.has(relPath)) findings.push(...judged);
  };
  const readTracked = (relPath: string): string | null => {
    const path = join(root, relPath);
    if (!existsSync(path) || lstatSync(path).isSymbolicLink()) return null;
    return readFileSync(path, "utf-8");
  };

  for (const relPath of trackedFiles(root)) {
    const kind = classify(relPath);
    if (kind === null) continue;
    const text = readTracked(relPath);
    if (text === null || isGenerated(text)) continue;
    if (isManaged(text)) {
      managedSkipped += 1;
      continue;
    }
    judge(relPath, kind, text);
  }
  const allowlistErrors = [...allow.failures];
  for (const entry of allow.entries) {
    if (!found.has(entry.path)) {
      allowlistErrors.push(
        `${ALLOWLIST_FILE}:${entry.line}: '${entry.path}' is stale (under every cap, or not a tracked file); remove the entry`,
      );
    }
  }
  return {
    failures: findings.filter(
      (finding): finding is Finding & { tier: "hard" } => finding.tier === "hard",
    ),
    warnings: findings.filter(
      (finding): finding is Finding & { tier: "warn" } => finding.tier === "warn",
    ),
    allowlistErrors,
    managedSkipped,
    unjudged: [...unjudged.values()].sort((a, b) => a.extension.localeCompare(b.extension)),
  };
}

/** The three outcomes the action distinguishes (its `report` output). */
export type Outcome =
  | { state: "findings" | "clean"; verdict: Verdict }
  | { state: "error"; message: string };

export function outcomeOf(verdict: Verdict): Outcome {
  const { failures, warnings, allowlistErrors } = verdict;
  const silent = failures.length + warnings.length + allowlistErrors.length === 0;
  return { state: silent ? "clean" : "findings", verdict };
}

export function report(outcome: Outcome): string {
  const parts = ["## File size check", ""];
  if (outcome.state === "error") {
    parts.push(`The check did not run to completion: ${outcome.message}`);
    return `${parts.join("\n")}\n`;
  }
  const { failures, warnings, allowlistErrors, managedSkipped, unjudged } = outcome.verdict;
  if (outcome.state === "clean") {
    parts.push("Every file is under its caps.");
  } else {
    parts.push(`${failures.length} over a hard cap (fails), ${warnings.length} warning(s).`);
    const rows = [...failures, ...warnings].map((finding) => {
      const where = finding.measure === "lines" ? finding.path : `${finding.path}:${finding.line}`;
      const [size, cap] = sizeCells(finding);
      return `| \`${where}\` | ${size} | ${finding.tier} | ${cap} |`;
    });
    if (rows.length > 0) {
      parts.push("", "| File | Size | Tier | Cap |", "| --- | --- | --- | --- |", ...rows);
    }
    if (allowlistErrors.length > 0) {
      parts.push("", `### ${ALLOWLIST_FILE}`, "", ...allowlistErrors.map((error) => `- ${error}`));
    }
    parts.push(
      "",
      `Split the file, wrap the line, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`,
    );
  }
  if (managedSkipped > 0) {
    parts.push("", `${managedSkipped} managed file(s) skipped; repo-platform owns them.`);
  }
  for (const { extension, files, reason } of unjudged) {
    parts.push(
      "",
      `${files} \`.${extension}\` file(s) not judged for comment blocks or literal lines (no working grammar: ${reason}).`,
    );
  }
  return `${parts.join("\n")}\n`;
}

export function parseArgs(argv: string[]): { root: string } {
  if (argv.length > 1) throw new Error(`unexpected argument(s): ${argv.slice(1).join(" ")}`);
  return { root: resolve(argv[0] ?? ".") };
}

if (import.meta.main) {
  // Cleared first, so a crash below leaves no comment body behind.
  const reportPath = process.env.REPORT_PATH;
  if (reportPath) rmSync(reportPath, { force: true });
  const emit = (outcome: Outcome): void => {
    const body = report(outcome);
    if (reportPath && outcome.state === "findings") writeFileSync(reportPath, body);
    if (process.env.GITHUB_STEP_SUMMARY) appendFileSync(process.env.GITHUB_STEP_SUMMARY, body);
    if (process.env.GITHUB_OUTPUT)
      appendFileSync(process.env.GITHUB_OUTPUT, `report=${outcome.state}\n`);
  };
  let verdict: Verdict;
  try {
    const { root } = parseArgs(process.argv.slice(2));
    verdict = check(root, await loadGrammars());
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`::error::check-file-size did not run to completion: ${message}`);
    emit({ state: "error", message });
    process.exit(1);
  }
  for (const warning of verdict.warnings) console.log(`::warning::${describe(warning)}`);
  const failures = [...verdict.failures.map(describe), ...verdict.allowlistErrors];
  if (failures.length > 0) {
    for (const failure of failures) console.error(`::error::${failure}`);
    console.error(
      `${failures.length} finding(s). Split the file, wrap the line, shorten or exempt the comment, or list the path in ${ALLOWLIST_FILE} with a '# reason'.`,
    );
  } else {
    console.log(
      `File size check passed (${verdict.warnings.length} warning(s), ${verdict.managedSkipped} managed file(s) skipped).`,
    );
  }
  // Last, so nothing after it can leave a recorded state the run's exit contradicts.
  emit(outcomeOf(verdict));
  process.exit(failures.length > 0 ? 1 : 0);
}
