#!/usr/bin/env bun

// Two-tier caps (HARD fails, WARN annotates) on file length and line width,
// and a warn-only cap on comment block length, over the tracked files of a
// checkout; .file-size-allow.local exempts a path with a mandatory `# reason`,
// `comment-cap: ignore <reason>` one comment block. Policy: docs/new-repo.md.

import {
  appendFileSync,
  existsSync,
  lstatSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, relative, resolve } from "node:path";

export type Kind = "source" | "test" | "workflow" | "shell" | "markdown";
export type Tier = "hard" | "warn";
/** The header is the first comment block when no code precedes it; every
 *  other block is judged as a block. */
export type CommentScope = "header" | "block";

export interface Caps {
  lines: Readonly<Record<Kind, number>>;
  /** Maximum line width, in code points, for the kinds in WIDTH_KINDS. */
  width: number;
}

/** The failing tier. */
export const HARD: Caps = {
  lines: { source: 2000, test: 3200, workflow: 1000, shell: 1000, markdown: 1300 },
  width: 256,
};
/** The annotating tier's share of each hard LINE cap. */
const WARN_RATIO = 0.8;
/** The annotating tier: line caps derived from HARD so the two can never
 *  disagree; the width cap stays well under the hard one, since a long
 *  shell or yaml string is what it exists to catch. */
export const WARN: Caps = {
  lines: Object.fromEntries(
    Object.entries(HARD.lines).map(([kind, cap]) => [kind, Math.round(cap * WARN_RATIO)]),
  ) as Caps["lines"],
  width: 150,
};
/** Maximum comment block length, in lines, by scope: one annotating tier,
 *  never a failure, so not derived from any hard cap. Fleet-wide, like every
 *  cap here: the fleet takes the action from `@build`. */
export const COMMENT_CAPS: Readonly<Record<CommentScope, number>> = { block: 10, header: 25 };
/** The per-block exemption, on a comment line inside the block (a comment
 *  line directly above it is part of it); the reason after it is mandatory. */
export const COMMENT_MARKER = "comment-cap: ignore";
/** Prose (markdown) has no width cap: the fleet writes one source line per
 *  paragraph, so its lines are long by design. */
export const WIDTH_KINDS: ReadonlySet<Kind> = new Set(["source", "test", "workflow", "shell"]);

export const ALLOWLIST_FILE = ".file-size-allow.local";

const SOURCE_EXTENSIONS = new Set([
  "ts",
  "tsx",
  "mts",
  "cts",
  "js",
  "jsx",
  "mjs",
  "cjs",
  "py",
  "pyi",
  "rs",
  "go",
  "swift",
  "kt",
  "java",
  "c",
  "h",
  "cpp",
  "cc",
  "cxx",
  "hh",
  "hpp",
]);
const SHELL_EXTENSIONS = new Set(["sh", "bash", "zsh"]);
/** Files whose whole-line comments are `#` runs; every other source
 *  extension uses `//` runs and `/* *\/` blocks (Python is listed here, so
 *  it is checked before the source set). */
const HASH_EXTENSIONS = new Set([...SHELL_EXTENSIONS, "yml", "yaml", "py", "pyi"]);
const TEST_DIRS = new Set(["test", "tests", "__tests__"]);
/** Test files by name: the JS/Python/Go conventions, and Rust's sibling
 *  test modules (`foo_tests.rs`, `tests.rs`, `proptests.rs`). */
const TEST_NAME =
  /(\.test\.|_test\.|\.spec\.|_spec\.|^test_|_tests\.rs$|^tests\.rs$|^proptests\.rs$)/;
/** Directory names whose contents are vendored or generated wholesale. */
const EXEMPT_DIRS = new Set([
  "node_modules",
  "vendor",
  "third_party",
  "golden-renders",
  "goldens",
  "__snapshots__",
]);

/** A comment in the file's first lines declaring it generated: the common
 *  phrasings, anywhere on the line. Only comment lines count, so a string
 *  literal holding "do not edit" is not a header; prose that merely uses the
 *  word "generate" ("copies generated from the manifests") matches no
 *  phrasing; and a generator's path is no signal at all, since hand-written
 *  headers name the generators they serve. */
const HEADER_LINES = 10;
const COMMENT_LINE = /^\s*(#|\/\/|\/\*|\*|<!--|--|;|%|\{#|"""|''')/;
const GENERATED_HEADER =
  /\b(generated by|auto-?generated|this file is generated|generated file|do not edit)\b/i;
/** The header every file repo-platform manages carries (the text
 *  validate-template checks): a fleet repository cannot fix such a file. */
const MANAGED_HEADER = /\bThis file is managed by [\w.-]+\/repo-platform\b/;
/** Marker-fenced generated regions inside otherwise hand-written files. */
const REGION_BEGIN = /\bBEGIN GENERATED\b/;
const REGION_END = /\bEND GENERATED\b/;

function extensionOf(relPath: string): string {
  const name = relPath.slice(relPath.lastIndexOf("/") + 1);
  const dot = name.lastIndexOf(".");
  return dot === -1 ? "" : name.slice(dot + 1).toLowerCase();
}

/** The kind a tracked path is judged as, or null when it is exempt. */
export function classify(relPath: string): Kind | null {
  const segments = relPath.split("/");
  const dirs = segments.slice(0, -1);
  if (dirs.some((dir) => EXEMPT_DIRS.has(dir))) return null;
  const name = segments[segments.length - 1];
  const ext = extensionOf(relPath);
  const workflowsDir =
    dirs.length >= 2 &&
    dirs[dirs.length - 2] === ".github" &&
    dirs[dirs.length - 1] === "workflows";
  if ((workflowsDir && (ext === "yml" || ext === "yaml")) || /^action\.ya?ml$/.test(name)) {
    return "workflow";
  }
  if (SHELL_EXTENSIONS.has(ext)) return "shell";
  if (ext === "md") return "markdown";
  if (SOURCE_EXTENSIONS.has(ext)) {
    return TEST_NAME.test(name) || dirs.some((dir) => TEST_DIRS.has(dir)) ? "test" : "source";
  }
  return null;
}

function headerLines(text: string): string[] {
  return text.split("\n", HEADER_LINES);
}

export function isGenerated(text: string): boolean {
  return headerLines(text).some((line) => COMMENT_LINE.test(line) && GENERATED_HEADER.test(line));
}

export function isManaged(text: string): boolean {
  return headerLines(text).some((line) => COMMENT_LINE.test(line) && MANAGED_HEADER.test(line));
}

/** Lines without their terminators: a final newline adds no line, and a
 *  CRLF file's `\r` is not width. */
function splitLines(text: string): string[] {
  const lines = text.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
  if (lines[lines.length - 1] === "") lines.pop();
  return lines;
}

/** A line wrapping cannot fix: one whitespace-free token (a URL, a sha, a
 *  path, a jinja expression), indentation aside. */
export function isUnbreakable(line: string): boolean {
  const token = line.trim();
  return token !== "" && !/\s/.test(token);
}

/** Which lines sit inside a matched BEGIN/END GENERATED pair, markers
 *  included (both markers on one line fence that line); an unmatched BEGIN
 *  fences nothing, and regions do not nest. */
function generatedRegionMask(lines: string[]): boolean[] {
  const mask = lines.map(() => false);
  let begin = -1;
  lines.forEach((line, index) => {
    if (begin === -1) {
      if (!REGION_BEGIN.test(line)) return;
      if (REGION_END.test(line)) mask[index] = true;
      else begin = index;
    } else if (REGION_END.test(line)) {
      for (let i = begin; i <= index; i++) mask[i] = true;
      begin = -1;
    }
  });
  return mask;
}

interface CommentSyntax {
  /** The prefix that makes a whole line a comment. */
  line: string;
  /** The delimiters of a comment that may span lines, where the language has one. */
  block?: readonly [open: string, close: string];
}
const SLASH_COMMENTS: CommentSyntax = { line: "//", block: ["/*", "*/"] };
const HASH_COMMENTS: CommentSyntax = { line: "#" };

/** The comment syntax of a path, or null for files with no comment blocks
 *  to judge (markdown is prose). */
function commentSyntax(relPath: string): CommentSyntax | null {
  const ext = extensionOf(relPath);
  if (HASH_EXTENSIONS.has(ext)) return HASH_COMMENTS;
  if (SOURCE_EXTENSIONS.has(ext)) return SLASH_COMMENTS;
  return null;
}

interface CommentBlock {
  /** The block's first line, 1-based. */
  line: number;
  /** Its length in lines. */
  length: number;
  scope: CommentScope;
  /** Every exemption marker in the block: its 1-based line and the reason
   *  after it (empty for a bare marker, which exempts nothing). */
  markers: { line: number; reason: string }[];
}

const MARKER = new RegExp(`\\b${COMMENT_MARKER}\\b`, "g");
/** The reason after each marker in comment text: what follows it up to the
 *  next marker or the block comment's closing delimiter, "" when bare. */
function markerReasons(text: string, closer: string | undefined): string[] {
  const matches = [...text.matchAll(MARKER)];
  return matches.map((match, i) => {
    const rest = text.slice(match.index + match[0].length, matches[i + 1]?.index ?? text.length);
    const close = closer === undefined ? -1 : rest.indexOf(closer);
    return (close === -1 ? rest : rest.slice(0, close)).trim();
  });
}

/** A shebang: `#!` and an interpreter path (Rust's `#![...]` attribute is
 *  code). */
const SHEBANG = /^#!\s*\//;

/** Whether trimmed text is a whole-line comment, code, or opens a block
 *  comment that closes on a later line (then: the delimiter that closes it).
 *  Text after a one-line block comment is classified again, so
 *  `/* a *\/ // b` is a comment and `/* a *\/ x` is code. */
function lineKind(text: string, syntax: CommentSyntax): "comment" | "code" | { closer: string } {
  if (text.startsWith(syntax.line)) return "comment";
  if (syntax.block === undefined || !text.startsWith(syntax.block[0])) return "code";
  const [open, closer] = syntax.block;
  const at = text.indexOf(closer, open.length);
  if (at === -1) return { closer };
  const rest = text.slice(at + closer.length).trim();
  return rest === "" ? "comment" : lineKind(rest, syntax);
}

/** Contiguous runs of whole-line comments. A blank line, a code line (an
 *  inline trailing comment is code, so is a `*\/` followed by code), or a
 *  `skip`ped line ends a run; a block comment counts every line between its
 *  delimiters, blanks included. A first-line shebang is neither. */
function commentBlocks(lines: string[], syntax: CommentSyntax, skip: boolean[]): CommentBlock[] {
  const blocks: CommentBlock[] = [];
  let start = -1;
  let markers: CommentBlock["markers"] = [];
  let headerAhead = true;
  /** The delimiter that closes the block comment the run is inside, if any. */
  let closer: string | null = null;
  const end = (at: number): void => {
    if (start === -1) return;
    const scope = headerAhead ? "header" : "block";
    blocks.push({ line: start + 1, length: at - start, scope, markers });
    start = -1;
    markers = [];
    headerAhead = false;
  };
  /** Records the markers on comment text that belongs to the current block. */
  const note = (index: number, text: string): void => {
    for (const reason of markerReasons(text, syntax.block?.[1])) {
      markers.push({ line: index + 1, reason });
    }
  };
  const code = (at: number): void => {
    end(at);
    headerAhead = false;
  };
  for (const [index, raw] of lines.entries()) {
    if (skip[index]) {
      closer = null;
      code(index);
      continue;
    }
    let text = raw.trim();
    if (closer !== null) {
      const at = text.indexOf(closer);
      if (at === -1) {
        note(index, text);
        continue;
      }
      note(index, text.slice(0, at));
      text = text.slice(at + closer.length).trim();
      closer = null;
      if (text === "") continue;
    } else if (index === 0 && SHEBANG.test(text)) {
      continue;
    } else if (text === "") {
      end(index);
      continue;
    }
    const kind = lineKind(text, syntax);
    if (kind === "code") {
      code(index);
      continue;
    }
    if (start === -1) start = index;
    note(index, text);
    if (kind !== "comment") closer = kind.closer;
  }
  end(lines.length);
  return blocks;
}

/** One string or regex literal, optionally assigned, returned, keyed, or
 *  `+`-continued: exempt from the WARN width tier only (wrapping it means
 *  splitting the literal). A linear scanner; the regex form backtracked. */
export function isLiteralLine(line: string): boolean {
  const start = skipWhile(line, 0, isSpace);
  for (const prefix of [declarationPrefix, returnPrefix, keyPrefix, (_: string, i: number) => i]) {
    const at = prefix(line, start);
    if (at === -1) continue;
    const end = scanLiteral(line, at);
    if (end === -1) continue;
    const rest = skipWhile(
      line,
      skipWhile(line, skipWhile(line, end, isSpace), isTrailer),
      isSpace,
    );
    if (rest === line.length) return true;
  }
  return false;
}

const isSpace = (c: string): boolean => /\s/.test(c);
const isWord = (c: string): boolean => /\w/.test(c);
const isKeyChar = (c: string): boolean => /[\w$.'"-]/.test(c);
const isTypeChar = (c: string): boolean => /[\w<>[\]|]/.test(c);
const isTrailer = (c: string): boolean => ",;)]+".includes(c);
const isStringPrefix = (c: string): boolean => "rbufRBUF".includes(c);
const isRegexFlag = (c: string): boolean => "dgimsuvy".includes(c);

function skipWhile(line: string, i: number, pred: (c: string) => boolean): number {
  let j = i;
  while (j < line.length && pred(line[j])) j++;
  return j;
}

/** `[export] const|let|var name [: Type] = `; -1 when absent. */
function declarationPrefix(line: string, i: number): number {
  let j = i;
  if (line.startsWith("export", j) && isSpace(line[j + 6] ?? ""))
    j = skipWhile(line, j + 6, isSpace);
  const keyword = ["const", "let", "var"].find((k) => line.startsWith(k, j));
  if (keyword === undefined || !isSpace(line[j + keyword.length] ?? "")) return -1;
  j = skipWhile(line, j + keyword.length, isSpace);
  const name = skipWhile(line, j, isWord);
  if (name === j) return -1;
  j = name;
  const colon = skipWhile(line, j, isSpace);
  if (line[colon] === ":") {
    const type = skipWhile(line, skipWhile(line, colon + 1, isSpace), isTypeChar);
    if (isTypeChar(line[type - 1] ?? "")) j = type;
  }
  j = skipWhile(line, j, isSpace);
  if (line[j] !== "=") return -1;
  return skipWhile(line, j + 1, isSpace);
}

/** `return `; -1 when absent. */
function returnPrefix(line: string, i: number): number {
  if (!line.startsWith("return", i) || !isSpace(line[i + 6] ?? "")) return -1;
  return skipWhile(line, i + 6, isSpace);
}

/** `key: ` / `key = ` / `key += `; -1 when absent. */
function keyPrefix(line: string, i: number): number {
  let j = skipWhile(line, i, isKeyChar);
  if (j === i) return -1;
  j = skipWhile(line, j, isSpace);
  if (line[j] === "+") j++;
  if (line[j] !== ":" && line[j] !== "=") return -1;
  return skipWhile(line, j + 1, isSpace);
}

/** The end of a string (with an optional r/b/u/f prefix), template, or
 *  regex literal starting at `i`; -1 when none starts there. */
function scanLiteral(line: string, i: number): number {
  let j = i;
  while (j < i + 2 && isStringPrefix(line[j] ?? "")) j++;
  const quote = line[j];
  if (quote === '"' || quote === "'" || (quote === "`" && j === i)) {
    return scanDelimited(line, j + 1, quote, 0);
  }
  if (line[i] !== "/") return -1;
  const close = scanDelimited(line, i + 1, "/", 1);
  return close === -1 ? -1 : skipWhile(line, close, isRegexFlag);
}

/** The index after the closing delimiter, honouring backslash escapes and
 *  requiring at least `minBody` body characters; -1 when unclosed. */
function scanDelimited(line: string, from: number, close: string, minBody: number): number {
  let j = from;
  while (j < line.length) {
    if (line[j] === "\\") j += 2;
    else if (line[j] === close) return j - from >= minBody ? j + 1 : -1;
    else j++;
  }
  return -1;
}

interface FindingBase {
  path: string;
  kind: Kind;
  tier: Tier;
}
interface Measured {
  value: number;
  cap: number;
}
/** A line-count finding names the file; a width finding names the 1-based
 *  line as well; a comment finding names the block's first line and scope;
 *  a marker finding names the line of a `comment-cap: ignore` with no
 *  reason. */
export type Finding =
  | (FindingBase & Measured & { measure: "lines" })
  | (FindingBase & Measured & { measure: "width"; line: number })
  | (FindingBase &
      Measured & { measure: "comment"; tier: "warn"; line: number; scope: CommentScope })
  | (FindingBase & { measure: "marker"; tier: "warn"; line: number });

/** The tier a value lands in, with the cap it exceeded; null under both. */
function exceeded(value: number, hard: number, warn: number): { tier: Tier; cap: number } | null {
  if (value > hard) return { tier: "hard", cap: hard };
  if (value > warn) return { tier: "warn", cap: warn };
  return null;
}

/** Every finding for one file, generated regions excluded from every
 *  measure: the line count against the kind's caps, each line's width (each
 *  landing in the highest tier whose cap it exceeds), and each comment
 *  block's length (warn only, unless a marker with a reason exempts it). */
export function judgeFile(path: string, kind: Kind, text: string): Finding[] {
  const findings: Finding[] = [];
  const lines = splitLines(text);
  const generated = generatedRegionMask(lines);
  const counted = generated.filter((inRegion) => !inRegion).length;
  const lineCount = exceeded(counted, HARD.lines[kind], WARN.lines[kind]);
  if (lineCount !== null) {
    findings.push({ path, kind, ...lineCount, measure: "lines", value: counted });
  }
  if (WIDTH_KINDS.has(kind)) {
    lines.forEach((line, index) => {
      if (generated[index] || isUnbreakable(line)) return;
      const width = [...line].length;
      const over = exceeded(width, HARD.width, WARN.width);
      if (over === null || (over.tier === "warn" && isLiteralLine(line))) return;
      findings.push({ path, kind, ...over, measure: "width", line: index + 1, value: width });
    });
  }
  const syntax = commentSyntax(path);
  if (syntax !== null) {
    for (const { line, length, scope, markers } of commentBlocks(lines, syntax, generated)) {
      for (const marker of markers) {
        if (marker.reason === "") {
          findings.push({ path, kind, tier: "warn", measure: "marker", line: marker.line });
        }
      }
      if (markers.some((marker) => marker.reason !== "")) continue;
      const cap = COMMENT_CAPS[scope];
      if (length > cap) {
        findings.push({
          path,
          kind,
          tier: "warn",
          measure: "comment",
          line,
          value: length,
          cap,
          scope,
        });
      }
    }
  }
  return findings;
}

/** The one-line log form: `path: 3021 lines (cap 2000 for source)`,
 *  `path:412: 613 chars (cap 256)`, `path:1: 26 comment lines (cap 25 for a
 *  header)`, or `path:7: comment-cap: ignore needs a reason`. */
export function describe(finding: Finding): string {
  switch (finding.measure) {
    case "lines":
      return `${finding.path}: ${finding.value} lines (cap ${finding.cap} for ${finding.kind})`;
    case "width":
      return `${finding.path}:${finding.line}: ${finding.value} chars (cap ${finding.cap})`;
    case "comment": {
      const scope = finding.scope === "header" ? " for a header" : "";
      return `${finding.path}:${finding.line}: ${finding.value} comment lines (cap ${finding.cap}${scope})`;
    }
    case "marker":
      return `${finding.path}:${finding.line}: ${COMMENT_MARKER} needs a reason`;
  }
}

/** The Size and Cap cells of a finding's table row. */
function sizeCells(finding: Finding): [size: string, cap: string] {
  switch (finding.measure) {
    case "lines":
      return [`${finding.value} lines`, `${finding.cap}`];
    case "width":
      return [`${finding.value} chars`, `${finding.cap}`];
    case "comment": {
      const scope = finding.scope === "header" ? " (header)" : "";
      return [`${finding.value} comment lines${scope}`, `${finding.cap}`];
    }
    case "marker":
      return [`${COMMENT_MARKER} without a reason`, "-"];
  }
}

export interface AllowEntry {
  path: string;
  reason: string;
  line: number;
}

export const REASON_RULE =
  "an allowlist entry needs a reason a reader accepts (vendored or upstream-shaped, generated but missed by the header exemption, a split that would break an external contract)";

/** Parses the allowlist: `path # reason` per line, blank lines and
 *  whole-line comments skipped. An entry without a reason is a failure. */
export function parseAllowlist(text: string): { entries: AllowEntry[]; failures: string[] } {
  const entries: AllowEntry[] = [];
  const failures: string[] = [];
  splitLines(text).forEach((raw, index) => {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) return;
    const hash = line.indexOf("#");
    const path = (hash === -1 ? line : line.slice(0, hash)).trim();
    const reason = hash === -1 ? "" : line.slice(hash + 1).trim();
    if (reason === "") {
      failures.push(`${ALLOWLIST_FILE}:${index + 1}: '${path}' has no '# reason'; ${REASON_RULE}`);
      return;
    }
    entries.push({ path, reason, line: index + 1 });
  });
  return { entries, failures };
}

/** Tracked paths under `root`, optionally narrowed to one subtree,
 *  relative to `root`. */
function trackedFiles(root: string, subtree?: string): string[] {
  const args = ["git", "-C", root, "ls-files", "-z"];
  if (subtree !== undefined) args.push("--", subtree);
  const proc = Bun.spawnSync(args, { stdout: "pipe", stderr: "pipe" });
  if (proc.exitCode !== 0) {
    throw new Error(`git ls-files failed in ${root}: ${proc.stderr.toString().trim()}`);
  }
  return proc.stdout
    .toString()
    .split("\0")
    .filter((path) => path !== "");
}

export interface Verdict {
  /** Hard-tier findings on files the allowlist does not name. */
  failures: (Finding & { tier: "hard" })[];
  /** Warn-tier findings on files the allowlist does not name. */
  warnings: (Finding & { tier: "warn" })[];
  /** Allowlist defects: entries without a reason, and stale entries. */
  allowlistErrors: string[];
  /** Files skipped for carrying repo-platform's managed header. */
  managedSkipped: number;
}

export interface CheckOptions {
  /** Rendered template trees under root, judged without the managed-file
   *  skip and the golden-directory exemption (kinds are classified on the
   *  path relative to the tree). */
  rendered?: string[];
}

/** The whole verdict for a checkout: every tracked, classified,
 *  non-generated, non-managed file judged, the allowlist applied to both
 *  tiers, and stale or reasonless allowlist entries reported. */
export function check(root: string, options: CheckOptions = {}): Verdict {
  const allowFile = join(root, ALLOWLIST_FILE);
  const allow = existsSync(allowFile)
    ? parseAllowlist(readFileSync(allowFile, "utf-8"))
    : { entries: [], failures: [] };
  const allowed = new Set(allow.entries.map((entry) => entry.path));
  const findings: Finding[] = [];
  const found = new Set<string>();
  let managedSkipped = 0;

  const judge = (relPath: string, kind: Kind, text: string): void => {
    const judged = judgeFile(relPath, kind, text);
    if (judged.length === 0) return;
    found.add(relPath);
    if (!allowed.has(relPath)) findings.push(...judged);
  };
  const readTracked = (relPath: string): string | null => {
    const path = join(root, relPath);
    if (!existsSync(path) || lstatSync(path).isSymbolicLink()) return null;
    return readFileSync(path, "utf-8");
  };

  // Rendered trees are judged by the second walk only.
  const renderedTrees = (options.rendered ?? []).map((tree) => relative(root, resolve(root, tree)));
  for (const [i, tree] of renderedTrees.entries()) {
    if (tree === "" || tree.startsWith("..")) {
      throw new Error(`--rendered ${options.rendered?.[i]}: must be a subdirectory of ${root}`);
    }
    const within = renderedTrees.find((other, j) => j !== i && tree.startsWith(`${other}/`));
    if (within !== undefined) {
      throw new Error(`--rendered ${tree}: already inside --rendered ${within}`);
    }
  }
  const inRenderedTree = (relPath: string): boolean =>
    renderedTrees.some((tree) => relPath.startsWith(`${tree}/`));

  for (const relPath of trackedFiles(root)) {
    if (inRenderedTree(relPath)) continue;
    const kind = classify(relPath);
    if (kind === null) continue;
    const text = readTracked(relPath);
    if (text === null || isGenerated(text)) continue;
    if (isManaged(text)) {
      managedSkipped += 1;
      continue;
    }
    judge(relPath, kind, text);
  }
  for (const tree of options.rendered ?? []) {
    const treePath = resolve(root, tree);
    const tracked = trackedFiles(root, tree);
    if (tracked.length === 0) {
      throw new Error(`--rendered ${tree}: no tracked files under it (moved or misspelled?)`);
    }
    for (const relPath of tracked) {
      const kind = classify(relative(treePath, join(root, relPath)));
      if (kind === null) continue;
      const text = readTracked(relPath);
      if (text === null || isGenerated(text)) continue;
      judge(relPath, kind, text);
    }
  }

  const allowlistErrors = [...allow.failures];
  for (const entry of allow.entries) {
    if (!found.has(entry.path)) {
      allowlistErrors.push(
        `${ALLOWLIST_FILE}:${entry.line}: '${entry.path}' is stale (under every cap, or not a tracked file); remove the entry`,
      );
    }
  }
  return {
    failures: findings.filter(
      (finding): finding is Finding & { tier: "hard" } => finding.tier === "hard",
    ),
    warnings: findings.filter(
      (finding): finding is Finding & { tier: "warn" } => finding.tier === "warn",
    ),
    allowlistErrors,
    managedSkipped,
  };
}

/** The three outcomes the action distinguishes (its `report` output). */
export type Outcome =
  | { state: "findings" | "clean"; verdict: Verdict }
  | { state: "error"; message: string };

export function outcomeOf(verdict: Verdict): Outcome {
  const { failures, warnings, allowlistErrors } = verdict;
  const silent = failures.length + warnings.length + allowlistErrors.length === 0;
  return { state: silent ? "clean" : "findings", verdict };
}

/** The step summary body on every outcome, and the sticky comment's on
 *  findings: hard failures first, then warnings (over a sensible size, or a
 *  bare exemption marker). */
export function report(outcome: Outcome): string {
  const parts = ["## File size check", ""];
  if (outcome.state === "error") {
    parts.push(`The check did not run to completion: ${outcome.message}`);
    return `${parts.join("\n")}\n`;
  }
  const { failures, warnings, allowlistErrors, managedSkipped } = outcome.verdict;
  if (outcome.state === "clean") {
    parts.push("Every file is under its caps.");
  } else {
    parts.push(`${failures.length} over a hard cap (fails), ${warnings.length} warning(s).`);
    const rows = [...failures, ...warnings].map((finding) => {
      const where = finding.measure === "lines" ? finding.path : `${finding.path}:${finding.line}`;
      const [size, cap] = sizeCells(finding);
      return `| \`${where}\` | ${size} | ${finding.tier} | ${cap} |`;
    });
    if (rows.length > 0) {
      parts.push("", "| File | Size | Tier | Cap |", "| --- | --- | --- | --- |", ...rows);
    }
    if (allowlistErrors.length > 0) {
      parts.push("", `### ${ALLOWLIST_FILE}`, "", ...allowlistErrors.map((error) => `- ${error}`));
    }
    parts.push(
      "",
      `Split the file, wrap the line, shorten or exempt the comment, or list the path in \`${ALLOWLIST_FILE}\` with a \`# reason\`.`,
    );
  }
  if (managedSkipped > 0) {
    parts.push("", `${managedSkipped} managed file(s) skipped; repo-platform owns them.`);
  }
  return `${parts.join("\n")}\n`;
}

/** `[root] [--rendered <dir>]...` */
export function parseArgs(argv: string[]): { root: string; rendered: string[] } {
  let root = ".";
  const rendered: string[] = [];
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--rendered") {
      const dir = argv[++i];
      if (dir === undefined) throw new Error("--rendered needs a directory");
      rendered.push(dir);
    } else {
      root = argv[i];
    }
  }
  return { root: resolve(root), rendered };
}

if (import.meta.main) {
  // Cleared first, so a crash below leaves no comment body behind.
  const reportPath = process.env.REPORT_PATH;
  if (reportPath) rmSync(reportPath, { force: true });
  const emit = (outcome: Outcome): void => {
    const body = report(outcome);
    if (reportPath && outcome.state === "findings") writeFileSync(reportPath, body);
    if (process.env.GITHUB_STEP_SUMMARY) appendFileSync(process.env.GITHUB_STEP_SUMMARY, body);
    if (process.env.GITHUB_OUTPUT)
      appendFileSync(process.env.GITHUB_OUTPUT, `report=${outcome.state}\n`);
  };
  let verdict: Verdict;
  try {
    const { root, rendered } = parseArgs(process.argv.slice(2));
    verdict = check(root, { rendered });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`::error::check-file-size did not run to completion: ${message}`);
    emit({ state: "error", message });
    process.exit(1);
  }
  for (const warning of verdict.warnings) console.log(`::warning::${describe(warning)}`);
  const failures = [...verdict.failures.map(describe), ...verdict.allowlistErrors];
  if (failures.length > 0) {
    for (const failure of failures) console.error(`::error::${failure}`);
    console.error(
      `${failures.length} finding(s). Split the file, wrap the line, shorten or exempt the comment, or list the path in ${ALLOWLIST_FILE} with a '# reason'.`,
    );
  } else {
    console.log(
      `File size check passed (${verdict.warnings.length} warning(s), ${verdict.managedSkipped} managed file(s) skipped).`,
    );
  }
  // Last, so nothing after it can leave a recorded state the run's exit contradicts.
  emit(outcomeOf(verdict));
  process.exit(failures.length > 0 ? 1 : 0);
}
