#!/usr/bin/env python3
"""Compose .gitignore files from the latest github/gitignore.

Generates two outputs from the official github/gitignore templates:

- template/.gitignore.jinja: what downstream repos receive. OS templates
  (Windows, macOS, Linux) always; toolchain templates (Node, Python) as
  jinja conditionals on the bun/uv entries in the `modules` answer.
- .gitignore (this repo's own): same OS templates plus BOTH toolchain
  templates (this repo carries Python scripts and bun/TS actions). The
  REPOSITORY LOCAL section's existing content is preserved across
  regenerations.

By default the script fetches upstream HEAD and records the commit SHA in
scripts/gitignore.lock (provenance, and what CI verifies against).

Usage:
  python3 scripts/build_gitignore.py           # fetch latest, update lock, regenerate
  python3 scripts/build_gitignore.py --locked  # regenerate from the recorded lock SHA
  python3 scripts/build_gitignore.py --check   # exit 1 if outputs don't match the lock SHA
"""

import argparse
import json
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LOCK_FILE = REPO_ROOT / "scripts" / "gitignore.lock"
OUTPUT_TEMPLATE = REPO_ROOT / "template" / ".gitignore.jinja"
OUTPUT_SELF = REPO_ROOT / ".gitignore"

ALWAYS = ["Global/Windows.gitignore", "Global/macOS.gitignore", "Global/Linux.gitignore"]
BY_MODULE = {"bun": "Node.gitignore", "uv": "Python.gitignore"}

LOCAL_BEGIN = "# BEGIN REPOSITORY LOCAL"
LOCAL_END = "# END REPOSITORY LOCAL"
DEFAULT_LOCAL_BODY = "# Add repository-specific ignore patterns in this section only.\n"

RAW = "https://raw.githubusercontent.com/github/gitignore/{sha}/{path}"
HEAD_API = "https://api.github.com/repos/github/gitignore/commits/main"


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def upstream_head() -> str:
    req = urllib.request.Request(HEAD_API, headers={"Accept": "application/vnd.github+json"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)["sha"]


def section(sha: str, path: str) -> str:
    name = path.rsplit("/", 1)[-1].removesuffix(".gitignore")
    # Upstream files may carry CRLF line endings (Windows.gitignore does).
    body = fetch(RAW.format(sha=sha, path=path)).replace("\r\n", "\n").strip()
    return f"## {name} (github/gitignore {path})\n{body}\n"


def local_section(body: str) -> str:
    return f"{LOCAL_BEGIN}\n{body}{LOCAL_END}\n\n"


def managed_header(sha: str) -> str:
    return (
        "# BEGIN REPO-PLATFORM MANAGED\n"
        f"# Generated from github/gitignore @ {sha} - do not edit; local\n"
        "# patterns go in the REPOSITORY LOCAL section above. Managed patterns\n"
        "# deliberately come last: last-match-wins makes them non-overridable.\n"
        "\n"
    )


def existing_local_body(output: Path) -> str:
    """Current content between the LOCAL markers, or the default."""
    if not output.exists():
        return DEFAULT_LOCAL_BODY
    text = output.read_bytes().decode("utf-8")
    begin = text.find(LOCAL_BEGIN)
    end = text.find(LOCAL_END)
    if begin == -1 or end == -1 or end < begin:
        return DEFAULT_LOCAL_BODY
    return text[begin + len(LOCAL_BEGIN) + 1 : end]


def build_template(sha: str, sections: dict[str, str]) -> str:
    parts = [
        "{# Generated by scripts/build_gitignore.py - edit the lock/script, not this file. #}\n",
        local_section(DEFAULT_LOCAL_BODY + "\n"),
        managed_header(sha),
    ]
    for path in ALWAYS:
        parts.append(sections[path])
        parts.append("\n")
    for module, path in BY_MODULE.items():
        parts.append("{% if '" + module + "' in modules %}\n")
        parts.append(sections[path])
        parts.append("{% endif %}\n")
    parts.append("# END REPO-PLATFORM MANAGED\n")
    return "".join(parts)


def build_self(sha: str, sections: dict[str, str], local_body: str) -> str:
    parts = [
        "# Generated by scripts/build_gitignore.py - only edit the LOCAL section.\n",
        local_section(local_body),
        managed_header(sha),
    ]
    for path in [*ALWAYS, *BY_MODULE.values()]:
        parts.append(sections[path])
        parts.append("\n")
    parts.append("# END REPO-PLATFORM MANAGED\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Compose template/.gitignore.jinja and this repo's .gitignore from github/gitignore.",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--locked",
        action="store_true",
        help="regenerate from the SHA recorded in scripts/gitignore.lock",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the outputs don't match the recorded lock SHA",
    )
    args = parser.parse_args()

    if args.locked or args.check:
        sha = LOCK_FILE.read_text().strip()
        sections = {p: section(sha, p) for p in [*ALWAYS, *BY_MODULE.values()]}
    else:
        # Build first, write the lock only after every fetch succeeded - a
        # failed fetch must not advance the lock past the generated files.
        sha = upstream_head()
        sections = {p: section(sha, p) for p in [*ALWAYS, *BY_MODULE.values()]}
        LOCK_FILE.write_text(sha + "\n")
        print(f"lock updated to {sha}")

    outputs = {
        OUTPUT_TEMPLATE: build_template(sha, sections),
        OUTPUT_SELF: build_self(sha, sections, existing_local_body(OUTPUT_SELF)),
    }

    if args.check:
        # Bytes, not text: read_text()'s universal-newline mode would mangle
        # the intentional CR in macOS.gitignore's `Icon[\r]` pattern.
        stale = [
            out.relative_to(REPO_ROOT)
            for out, content in outputs.items()
            if (out.read_bytes() if out.exists() else b"") != content.encode("utf-8")
        ]
        if stale:
            for rel in stale:
                print(f"{rel} is stale; run scripts/build_gitignore.py")
            return 1
        print("gitignore outputs are up to date")
        return 0

    for out, content in outputs.items():
        out.write_bytes(content.encode("utf-8"))
        print(f"wrote {out.relative_to(REPO_ROOT)} from github/gitignore @ {sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
