#!/usr/bin/env bun
// Compose .gitignore files from the latest github/gitignore.
//
// Generates two outputs from the official github/gitignore templates:
//
// - templates/base/.gitignore.jinja: what downstream repos receive (published
//   onto the staging/latest build branches by build-branches.yml). OS
//   templates (Windows, macOS, Linux) always; toolchain templates (Node,
//   Python) as jinja conditionals on the bun/uv entries in the `modules`
//   answer.
// - .gitignore (this repo's own): same OS templates plus BOTH toolchain
//   templates (downstream repos may carry either). The REPOSITORY LOCAL
//   section's existing content is preserved across regenerations.
//
// By default the script fetches upstream HEAD and records the commit SHA in
// scripts/gitignore.lock (provenance, and what CI verifies against).
//
// Usage:
//   bun scripts/build_gitignore.ts           # fetch latest, update lock, regenerate
//   bun scripts/build_gitignore.ts --locked  # regenerate from the recorded lock SHA
//   bun scripts/build_gitignore.ts --check   # exit 1 if outputs don't match the lock SHA

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

const REPO_ROOT = resolve(dirname(Bun.main), "..");
const LOCK_FILE = join(REPO_ROOT, "scripts", "gitignore.lock");
const OUTPUT_TEMPLATE = join(REPO_ROOT, "templates", "base", ".gitignore.jinja");
const OUTPUT_SELF = join(REPO_ROOT, ".gitignore");

const ALWAYS = ["Global/Windows.gitignore", "Global/macOS.gitignore", "Global/Linux.gitignore"];
const BY_MODULE: Record<string, string> = { bun: "Node.gitignore", uv: "Python.gitignore" };

const LOCAL_BEGIN = "# BEGIN REPOSITORY LOCAL";
const LOCAL_END = "# END REPOSITORY LOCAL";
const DEFAULT_LOCAL_BODY = "# Add repository-specific ignore patterns in this section only.\n";

const RAW = "https://raw.githubusercontent.com/github/gitignore";
const HEAD_API = "https://api.github.com/repos/github/gitignore/commits/main";

async function fetchText(url: string, headers?: Record<string, string>): Promise<string> {
  const resp = await fetch(url, { headers, signal: AbortSignal.timeout(30_000) });
  if (!resp.ok) throw new Error(`GET ${url} failed: HTTP ${resp.status}`);
  return resp.text();
}

async function upstreamHead(): Promise<string> {
  const body = await fetchText(HEAD_API, { Accept: "application/vnd.github+json" });
  return (JSON.parse(body) as { sha: string }).sha;
}

async function section(sha: string, path: string): Promise<string> {
  const name = (path.split("/").pop() as string).replace(/\.gitignore$/, "");
  // Upstream files may carry CRLF line endings (Windows.gitignore does).
  const body = (await fetchText(`${RAW}/${sha}/${path}`)).replaceAll("\r\n", "\n").trim();
  return `## ${name} (github/gitignore ${path})\n${body}\n`;
}

function localSection(body: string): string {
  return `${LOCAL_BEGIN}\n${body}${LOCAL_END}\n\n`;
}

function managedHeader(sha: string): string {
  return (
    "# BEGIN REPO-PLATFORM MANAGED\n" +
    `# Generated from github/gitignore @ ${sha} - do not edit; local\n` +
    "# patterns go in the REPOSITORY LOCAL section above. Managed patterns\n" +
    "# deliberately come last: last-match-wins makes them non-overridable.\n" +
    "\n"
  );
}

/** Current content between the LOCAL markers, or the default. */
function existingLocalBody(output: string): string {
  if (!existsSync(output)) return DEFAULT_LOCAL_BODY;
  const text = readFileSync(output).toString("utf-8");
  const begin = text.indexOf(LOCAL_BEGIN);
  const end = text.indexOf(LOCAL_END);
  if (begin === -1 || end === -1 || end < begin) return DEFAULT_LOCAL_BODY;
  return text.slice(begin + LOCAL_BEGIN.length + 1, end);
}

function buildTemplate(sha: string, sections: Record<string, string>): string {
  const parts = [
    "{# Generated by scripts/build_gitignore.ts - edit the lock/script, not this file. #}\n",
    localSection(`${DEFAULT_LOCAL_BODY}\n`),
    managedHeader(sha),
  ];
  for (const path of ALWAYS) {
    parts.push(sections[path], "\n");
  }
  for (const [module, path] of Object.entries(BY_MODULE)) {
    parts.push(`{% if '${module}' in modules %}\n`, sections[path], "{% endif %}\n");
  }
  parts.push("# END REPO-PLATFORM MANAGED\n");
  return parts.join("");
}

function buildSelf(sha: string, sections: Record<string, string>, localBody: string): string {
  const parts = [
    "# Generated by scripts/build_gitignore.ts - only edit the LOCAL section.\n",
    localSection(localBody),
    managedHeader(sha),
  ];
  for (const path of [...ALWAYS, ...Object.values(BY_MODULE)]) {
    parts.push(sections[path], "\n");
  }
  parts.push("# END REPO-PLATFORM MANAGED\n");
  return parts.join("");
}

async function main(): Promise<number> {
  const args = process.argv.slice(2);
  const locked = args.includes("--locked");
  const check = args.includes("--check");
  const unknown = args.filter((a) => a !== "--locked" && a !== "--check");
  if (unknown.length > 0 || (locked && check)) {
    console.error(
      unknown.length > 0
        ? `error: unrecognized argument(s): ${unknown.join(" ")}`
        : "error: --locked and --check are mutually exclusive",
    );
    return 2;
  }

  const paths = [...ALWAYS, ...Object.values(BY_MODULE)];
  let sha: string;
  if (locked || check) {
    sha = readFileSync(LOCK_FILE, "utf-8").trim();
  } else {
    sha = await upstreamHead();
  }
  const sections: Record<string, string> = {};
  for (const path of paths) sections[path] = await section(sha, path);
  if (!locked && !check) {
    // The lock is written only after every fetch succeeded - a failed fetch
    // must not advance the lock past the generated files.
    writeFileSync(LOCK_FILE, `${sha}\n`);
    console.log(`lock updated to ${sha}`);
  }

  const outputs: [string, string][] = [
    [OUTPUT_TEMPLATE, buildTemplate(sha, sections)],
    [OUTPUT_SELF, buildSelf(sha, sections, existingLocalBody(OUTPUT_SELF))],
  ];

  if (check) {
    // Bytes, not text: the intentional CR in macOS.gitignore's `Icon[\r]`
    // pattern must survive the comparison.
    const stale = outputs
      .filter(
        ([out, content]) =>
          !(existsSync(out) ? readFileSync(out) : Buffer.alloc(0)).equals(
            Buffer.from(content, "utf-8"),
          ),
      )
      .map(([out]) => relative(REPO_ROOT, out));
    if (stale.length > 0) {
      for (const rel of stale) {
        console.log(
          `${rel} is stale: it does not match the output generated from ` +
            `the locked github/gitignore SHA (${sha.slice(0, 12)}); run ` +
            "bun scripts/build_gitignore.ts --locked to regenerate it " +
            "(drop --locked to also advance the lock)",
        );
      }
      return 1;
    }
    console.log("gitignore outputs are up to date");
    return 0;
  }

  for (const [out, content] of outputs) {
    writeFileSync(out, Buffer.from(content, "utf-8"));
    console.log(`wrote ${relative(REPO_ROOT, out)} from github/gitignore @ ${sha}`);
  }
  return 0;
}

process.exit(await main());
