import { describe, expect, test } from "bun:test";
import { lstatSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const FILES_TREE = new URL("../../files", import.meta.url).pathname;

const RETIRED_WORDING =
  /\btemplate (sync|updates)|during template|repo-platform's template|copier/gi;

function retiredWording(text: string): string[] {
  const unwrapped = text.replace(/\n[ \t]*(?:#|\/\/|<!--)?[ \t]*/g, " ");
  return unwrapped.match(RETIRED_WORDING) ?? [];
}

function walk(root: string, prefix = ""): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(join(root, prefix), { withFileTypes: true })) {
    const rel = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory() && !entry.isSymbolicLink()) out.push(...walk(root, rel));
    else out.push(rel);
  }
  return out.sort();
}

describe("the files/ tree speaks the sync's vocabulary", () => {
  // The spellings the platform retired, wrapped ones included, against the
  // uses that stay legitimate: the tripwire below is only as good as this.
  test.each([
    ["# Local edits may be replaced during template updates.", ["during template"]],
    ["never overwritten by template\n# sync, so add", ["template sync"]],
    ["seeded once by repo-platform's template, never", ["repo-platform's template"]],
    ["<!-- ... and survive template updates. -->", ["template updates"]],
    ["  # Machine-generated by copier (pyyaml", ["copier"]],
    ["# validate-template posts its sticky findings comment.", []],
    ["#  JetBrains specific template is maintained in a separate", []],
    ["written by a python script from a template\n#   before PyInstaller", []],
  ])("retiredWording(%j) -> %j", (text, hits) => {
    expect(retiredWording(text)).toEqual(hits);
  });

  test("no source file says template sync, template updates, or copier", () => {
    const hits = walk(FILES_TREE)
      .filter((path) => !lstatSync(join(FILES_TREE, path)).isSymbolicLink())
      .flatMap((path) =>
        retiredWording(readFileSync(join(FILES_TREE, path), "utf-8")).map(
          (hit) => `${path}: ${hit}`,
        ),
      );
    expect(hits).toEqual([]);
  });
});
