import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("../../", import.meta.url).pathname;

// The operator's own .github/ carries hand-kept copies of the managed files, so it speaks the
// same vocabulary; .github/scripts is code, not a copy.
const TREES: { dir: string; skip: string[] }[] = [
  { dir: "files", skip: [] },
  { dir: ".github", skip: [".github/scripts"] },
];

const RETIRED_WORDING =
  /\btemplate (sync|updates)|during template|repo-platform's template|copier/gi;

function retiredWording(text: string): string[] {
  const unwrapped = text.replace(/\n[ \t]*(?:#|\/\/|<!--)?[ \t]*/g, " ");
  return unwrapped.match(RETIRED_WORDING) ?? [];
}

function walk(rel: string, skip: string[]): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(join(ROOT, rel), { withFileTypes: true })) {
    const path = `${rel}/${entry.name}`;
    if (skip.includes(path) || entry.isSymbolicLink()) continue;
    if (entry.isDirectory()) out.push(...walk(path, skip));
    else out.push(path);
  }
  return out.sort();
}

describe("the managed files speak the sync's vocabulary", () => {
  // The retired spellings, wrapped ones included, against the uses that stay legitimate: the
  // tripwire below is only as good as this.
  test.each([
    ["# Local edits may be replaced during template updates.", ["during template"]],
    ["never overwritten by template\n# sync, so add", ["template sync"]],
    ["seeded once by repo-platform's template, never", ["repo-platform's template"]],
    ["<!-- ... and survive template updates. -->", ["template updates"]],
    ["  # Machine-generated by copier (pyyaml", ["copier"]],
    ["# validate-template posts its sticky findings comment.", []],
    ["#  JetBrains specific template is maintained in a separate", []],
    ["written by a python script from a template\n#   before PyInstaller", []],
  ])("retiredWording(%j) -> %j", (text, hits) => {
    expect(retiredWording(text)).toEqual(hits);
  });

  test("no source file or operator copy says template sync, template updates, or copier", () => {
    const hits = TREES.flatMap(({ dir, skip }) => walk(dir, skip)).flatMap((path) =>
      retiredWording(readFileSync(join(ROOT, path), "utf-8")).map((hit) => `${path}: ${hit}`),
    );
    expect(hits).toEqual([]);
  });
});
