// The platform repository's name, spelled once. Every derived string here is a byte the fleet observes (a file name, a
// marker, a header, a branch, a title), so tests/actions/platform.test.ts pins each against the literal the fleet
// carries today; `uses:` refs in YAML stay literal because GitHub allows no expression there.
//
// DEPENDENCY-FREE ZONE (see grammar.ts): node builtins and zone-internal imports only.

export const PLATFORM_OWNER = "Vivswan";
export const PLATFORM_NAME = "repo-platform";
export const PLATFORM_SLUG = `${PLATFORM_OWNER}/${PLATFORM_NAME}`;

/** The registration a repository carries on its default branch to adopt the platform. */
export const REGISTRATION_PATH = `.${PLATFORM_NAME}.yml`;
export const MANIFEST_NAME = `.github/${PLATFORM_NAME}-manifest.json`;

/** The label both managed-region marker lines carry; grammar.ts wraps it in each comment syntax. */
export const MANAGED_REGION_LABEL = `${PLATFORM_NAME.toUpperCase()} MANAGED`;

/** The first sentence of every document the platform renders (the manifest, a rendered settings file). */
export const GENERATED_NOTICE = `Generated by ${PLATFORM_NAME} - do not edit.`;

/** The header every managed file carries, whichever owner spelling the writer rendered. */
export const MANAGED_HEADER_PATTERN = new RegExp(
  `\\bThis file is managed by [\\w.-]+/${PLATFORM_NAME}\\b`,
);

export const SYNC_BOT = `${PLATFORM_NAME}-sync`;
export const BUILD_BOT = `${PLATFORM_NAME}-build`;

export const AUTOMATION_BRANCH = `automation/${PLATFORM_NAME}`;
export const FAILURE_ISSUE_TITLE = `[${PLATFORM_NAME}] sync failed`;
export const SYNC_PR_TITLE_PREFIX = `chore: sync ${PLATFORM_NAME} build`;

/** A sticky PR comment's header names its host (the workflow stem or the action), so two posters never edit each other's comment. */
export function stickyCommentHeader(host: string): string {
  return `${PLATFORM_NAME}/${host}`;
}
