#!/usr/bin/env bun
// Assembles the `build` branch tree: the one generated delivery channel the
// fleet consumes, for BOTH copier renders and `uses:` action refs (layout
// and extraction rules: docs/build-provenance.md, "Extraction safety").
// copier.yml is a byte copy of this checkout's root file, the composed
// `template/` carries plain filenames only, and each action ships its
// sources plus dependency manifests, never node_modules: it installs at its
// own action_path when it runs.
//
// Invariants this file owns: content is fully deterministic (no timestamps
// or source shas in-tree), which the sync's provenance tree proof and
// publish.ts's no-change skip both depend on; nothing may RUN on the
// branch, so copyFleetWorkflows hard-fails on any shipped workflow whose
// triggers are not exactly workflow_call (PAT pushes can trigger workflows,
// and push events execute the pushed tree's own files).
//
// Usage:
//   bun .github/scripts/build-branches/branch_tree.ts --dest DIR
//   bun .github/scripts/build-branches/branch_tree.ts --check
//     (assembles into a fresh per-run scratch directory and removes it, so
//     concurrent checks never share a path)

import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, relative, resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { build, writeOutput } from "../../../scripts/compose/compose.ts";
import { reservedLabelNames } from "../../../scripts/generate/copier_questions.ts";
import { loadManifests } from "../../../scripts/lib/module_manifests.ts";
import { MIGRATIONS_DIR, RUNG_FILE_RE } from "../sync/run_migrations.ts";
import { loadFilesConfig } from "../sync/writer/files_config.ts";

const REPO_ROOT = resolve(import.meta.dir, "..", "..", "..");

/** The path with every EXISTING component dereferenced: resolve() is
 * lexical, so a symlinked parent (say /tmp/projects -> the repo's parent)
 * would otherwise alias the checkout past the overlap guard below. The
 * not-yet-existing tail is re-attached unresolved. */
export function canonicalize(path: string): string {
  let base = path;
  const tail: string[] = [];
  while (!existsSync(base)) {
    tail.unshift(basename(base));
    const parent = dirname(base);
    if (parent === base) break;
    base = parent;
  }
  return join(realpathSync(base), ...tail);
}

/** The fleet-facing reusable workflows the build branch must carry - every
 *  reusable workflow a RENDERED workflow calls `@build`: the rendered
 *  ci.yml calls fleet-ci.yml (whose codeql job calls ./reusable-codeql.yml,
 *  resolving at fleet-ci's own ref - this branch) and the release pair,
 *  pages.yml and docs-site.yml call reusable-pages.yml, and auto-assign.yml
 *  calls the reusable-auto-assign pair. A reusable-workflow `uses:` fetches
 *  the FILE at the named ref, so a build branch missing one 404s every
 *  fleet run that calls it. */
export const FLEET_WORKFLOWS = [
  "fleet-ci.yml",
  "fleet-release-publish.yml",
  "fleet-release.yml",
  "reusable-auto-assign-alerts.yml",
  "reusable-auto-assign.yml",
  "reusable-codeql.yml",
  "reusable-pages.yml",
];

/** Where the module manifests land on the branch: modules/<name>.yml, one
 *  byte copy per module, read at run time by the plan action beside them. */
export const MODULE_DATA_DIR = "modules";

/** The labels the template manages (every settings layer's roster), which
 *  no tracking stream may reuse: copier.yml's validators carry the same
 *  list inline; the plan action reads this file to refuse a registration
 *  label the same way. */
export const RESERVED_LABELS_FILE = "reserved-labels.yml";

/** The sync writer's data file and source tree, shipped verbatim: the
 *  operator reads both from the build commit it syncs. */
export const FILES_CONFIG = "files.yml";
export const FILES_DIR = "files";

const README = `\
# repo-platform build branch

This branch is GENERATED by the build-branches workflow on \`main\` - do not
commit to it or open pull requests against it (they are closed automatically).
Template sources live in \`templates/\` on \`main\`, the composite actions'
sources in \`actions/\`.

\`build\` is rebuilt from each \`main\` commit whose CI run succeeds (the
branch ships only green main commits). It carries the composed copier tree
under \`template/\`, the composite actions under \`actions/\`, the
fleet-facing reusable workflows (${FLEET_WORKFLOWS.join(", ")})
under \`.github/workflows/\`, the module manifests under \`modules/\` (one
\`<name>.yml\` per module) with \`reserved-labels.yml\` beside them (the
data the plan action resolves each repository's CI from at run time), and
the migration ladder's rungs under
\`migrations/\` (self-contained scripts; the sync runs the ones that
appeared after a repository's recorded build), and the sync writer's data
(\`files.yml\` plus the \`files/\` source tree it copies from) - every path is
extraction-safe (no jinja-expression filenames), so
\`uses: <owner>/repo-platform/actions/<name>@build\` refs extract cleanly
on the runner, and an @build pin runs only action and workflow code CI has
vouched for. Every shipped workflow is workflow_call-only (enforced at
assembly), so nothing can ever run ON this branch.

Consume the template with copier, e.g.:

    copier copy gh:Vivswan/repo-platform . --vcs-ref build
`;

/** Directories never published under actions/: build output and installed
 *  dependencies, both reproducible from what is published. */
export const EXCLUDED_DIRS = new Set(["node_modules", "dist", ".turbo"]);

/** Test files never publish either: nothing on the branch runs them, and
 *  they import fixtures from tests/, which the branch does not carry. */
export const TEST_FILE_SUFFIX = ".test.ts";

/** The dependency-free library zone under actions/: shared code the
 *  composite actions and the shipped hooks import relatively, not an
 *  action of its own, so it ships with no action.yml. */
export const SHARED_DIR = "shared";

/** Whether a path under an action root publishes: outside every excluded
 *  directory segment (relative to the root, so an ancestor named
 *  node_modules does not filter the whole copy away) and not a test file. */
export function publishes(actionRoot: string, src: string): boolean {
  const segments = relative(actionRoot, src).split("/");
  if (segments.some((segment) => EXCLUDED_DIRS.has(segment))) return false;
  return !basename(src).endsWith(TEST_FILE_SUFFIX);
}

function hasPublishableFile(actionRoot: string, dir = actionRoot): boolean {
  return readdirSync(dir, { withFileTypes: true }).some((entry) => {
    const path = join(dir, entry.name);
    if (!publishes(actionRoot, path)) return false;
    return entry.isDirectory() ? hasPublishableFile(actionRoot, path) : true;
  });
}

/** The action directories under `<repoRoot>/actions`, sorted: those with at
 *  least one publishable file. A directory holding only ignored leftovers
 *  (the node_modules of a retired action, after a pull) is invisible. */
export function actionDirNames(repoRoot: string): string[] {
  const source = join(repoRoot, "actions");
  return readdirSync(source, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !EXCLUDED_DIRS.has(entry.name))
    .filter((entry) => hasPublishableFile(join(source, entry.name)))
    .map((entry) => entry.name)
    .sort();
}

/** Copies every action directory (the shared zone included) to
 *  `<dest>/actions`, returning the number of files written. Throws when
 *  the source has no actions at all: the rendered workflows reference them
 *  by path, so publishing a branch without them would 404 every fleet CI
 *  run rather than fail here. */
export function copyActions(repoRoot: string, dest: string): number {
  const source = join(repoRoot, "actions");
  if (!existsSync(source)) {
    throw new Error(
      `no actions/ directory at ${repoRoot} - the rendered workflows call ` +
        "actions by path, so a build branch without them breaks every " +
        "fleet CI run; check the checkout before publishing",
    );
  }
  const names = actionDirNames(repoRoot);
  if (!names.some((name) => name !== SHARED_DIR)) {
    throw new Error(`actions/ at ${repoRoot} holds no action directories`);
  }
  // A directory with sources but no action.yml is a BROKEN state, never an
  // intentional retirement - retiring an action deletes its whole
  // directory. Publishing it anyway would succeed here and then fail every
  // fleet `uses: .../<name>@build` at resolve time, so refuse loudly
  // before anything is copied. The shared zone is reached by path, never
  // resolved as an action.
  for (const name of names) {
    if (name === SHARED_DIR) continue;
    if (!existsSync(join(source, name, "action.yml"))) {
      throw new Error(
        `actions/${name} at ${repoRoot} has no action.yml - sources without a ` +
          "manifest are a broken state, not a retirement (retiring an action " +
          "removes its whole directory); publishing this tree would break " +
          `every fleet 'uses: .../actions/${name}@build' ref`,
      );
    }
  }
  let files = 0;
  for (const name of names) {
    const actionRoot = join(source, name);
    cpSync(actionRoot, join(dest, "actions", name), {
      recursive: true,
      filter: (src) => publishes(actionRoot, src),
    });
    files += countFiles(join(dest, "actions", name));
  }
  return files;
}

function countFiles(dir: string): number {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    total += entry.isDirectory() ? countFiles(join(dir, entry.name)) : 1;
  }
  return total;
}

/** The workflow document's trigger names, whatever shape `on:` takes. */
function triggerNames(doc: unknown): string[] {
  const on = doc && typeof doc === "object" ? (doc as Record<string, unknown>).on : undefined;
  if (typeof on === "string") return [on];
  if (Array.isArray(on)) return on.map(String);
  if (on && typeof on === "object") return Object.keys(on);
  return [];
}

/** Copies the fleet-facing reusable workflows to `<dest>/.github/workflows`,
 *  refusing - by hard error, naming the file and the trigger - any workflow
 *  whose triggers are not exactly `workflow_call`. This is what keeps
 *  "nothing can run on the build branch" true now that the branch carries
 *  .github/workflows/ and is pushed with a PAT (whose pushes, unlike
 *  GITHUB_TOKEN's, CAN trigger workflows): push and branch events execute
 *  the pushed tree's own workflow files, and a workflow_call-only tree has
 *  nothing to run. */
export function copyFleetWorkflows(repoRoot: string, dest: string): void {
  const outDir = join(dest, ".github", "workflows");
  mkdirSync(outDir, { recursive: true });
  for (const name of FLEET_WORKFLOWS) {
    const sourcePath = join(repoRoot, ".github", "workflows", name);
    if (!existsSync(sourcePath)) {
      throw new Error(
        `.github/workflows/${name} is missing at ${repoRoot} - the fleet pins it ` +
          "@build (a reusable-workflow uses: fetches the file at that ref), so a " +
          "build branch without it breaks every fleet CI run; check the checkout " +
          "before publishing",
      );
    }
    const content = readFileSync(sourcePath, "utf-8");
    const triggers = triggerNames(parseYaml(content));
    if (triggers.length === 0) {
      throw new Error(
        `.github/workflows/${name} declares no triggers - expected exactly ` +
          "workflow_call; refusing to ship a workflow this assembly cannot prove inert",
      );
    }
    const offending = triggers.filter((trigger) => trigger !== "workflow_call");
    if (offending.length > 0) {
      throw new Error(
        `.github/workflows/${name} carries the trigger '${offending[0]}' - only ` +
          "workflow_call-only workflows may ship on the build branch (the branch is " +
          "pushed with a PAT, so any other trigger could RUN there); split the " +
          "trigger out or keep the workflow off FLEET_WORKFLOWS",
      );
    }
    writeFileSync(join(outDir, name), content);
  }
}

/** The ladder's source directory on main. */
export const MIGRATIONS_SRC_REL = `.github/scripts/sync/${MIGRATIONS_DIR}`;

/** Copies every rung file verbatim to `<dest>/migrations`. The directory
 *  holds nothing but rungs (the migration-ladder ssot rule), so any other
 *  entry is a hard failure here rather than a stray path on the branch. */
export function copyMigrations(repoRoot: string, dest: string): void {
  const src = join(repoRoot, MIGRATIONS_SRC_REL);
  mkdirSync(join(dest, MIGRATIONS_DIR), { recursive: true });
  for (const name of readdirSync(src).sort()) {
    if (!RUNG_FILE_RE.test(name)) {
      throw new Error(`${MIGRATIONS_SRC_REL}/${name} is not a rung file (mNNNN_<slug>.ts)`);
    }
    writeFileSync(join(dest, MIGRATIONS_DIR, name), readFileSync(join(src, name)));
  }
}

/** Copies every module manifest verbatim to `<dest>/modules/<name>.yml`.
 *  loadManifests validates the set (MODULE_ORDER <-> templates/ integrity,
 *  the schema), so a broken manifest fails the assembly here rather than
 *  every fleet plan step at run time. */
export function copyModuleData(repoRoot: string, dest: string): void {
  const outDir = join(dest, MODULE_DATA_DIR);
  mkdirSync(outDir, { recursive: true });
  const templatesDir = join(repoRoot, "templates");
  const manifests = loadManifests(templatesDir);
  for (const manifest of manifests) {
    writeFileSync(
      join(outDir, `${manifest.module}.yml`),
      readFileSync(join(templatesDir, manifest.module, "module.yml")),
    );
  }
  const reserved = reservedLabelNames(manifests).map((name) => `- ${JSON.stringify(name)}\n`);
  writeFileSync(join(dest, RESERVED_LABELS_FILE), reserved.join(""));
}

/** Copies files.yml and the files/ tree verbatim, after the writer's own
 *  loader has accepted them: a source missing from the tree or a token
 *  outside the placeholder list fails the assembly here rather than every
 *  fleet sync that reads the branch. */
export function copyFilesTree(repoRoot: string, dest: string): void {
  loadFilesConfig(join(repoRoot, FILES_CONFIG), join(repoRoot, FILES_DIR));
  cpSync(join(repoRoot, FILES_DIR), join(dest, FILES_DIR), { recursive: true });
  writeFileSync(join(dest, FILES_CONFIG), readFileSync(join(repoRoot, FILES_CONFIG)));
}

/** Assemble the whole branch tree at `dest` (which must exist and be
 *  empty): the composed template/, actions/ (the stamp hook rides inside
 *  actions/shared/), the fleet-facing reusable workflows, the module
 *  manifests, the migration rungs, the sync writer's files.yml and files/,
 *  copier.yml, and the README. Exported for the extraction-safety
 *  regression, which asserts no assembled path carries a jinja expression. */
export function assembleBranchTree(dest: string): void {
  const composed = build();
  writeOutput(composed, join(dest, "template"));
  copyActions(REPO_ROOT, dest);
  copyFleetWorkflows(REPO_ROOT, dest);
  copyModuleData(REPO_ROOT, dest);
  copyMigrations(REPO_ROOT, dest);
  copyFilesTree(REPO_ROOT, dest);
  writeFileSync(join(dest, "copier.yml"), readFileSync(join(REPO_ROOT, "copier.yml")));
  writeFileSync(join(dest, "README.md"), README);
}

/** A refused invocation: reported as `error: <message>` and exit 2 by the
 * CLI entry, thrown here so the parser stays testable. */
export class UsageError extends Error {}

function usageError(message: string): never {
  throw new UsageError(message);
}

/** Where to assemble: a caller-owned directory (replaced, kept), or a
 * scratch directory this run mints and removes. Exactly one. */
export type Target = { kind: "dest"; dest: string } | { kind: "check" };

export function parseArgs(argv: string[]): Target {
  let dest: string | undefined;
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const value = () => {
      i++;
      const next = argv[i];
      if (next === undefined || next.startsWith("--")) {
        usageError(`argument ${arg}: expected one argument`);
      }
      return next;
    };
    if (arg === "--dest") dest = value();
    else if (arg === "--check") check = true;
    else usageError(`unrecognized argument: ${arg}`);
  }
  if (check && dest !== undefined) usageError("--check and --dest are mutually exclusive");
  if (check) return { kind: "check" };
  if (!dest) usageError("one of --dest DIR or --check is required");
  return { kind: "dest", dest };
}

/** True when dest is the repository root, an ancestor of it, or inside it -
 * every path whose recursive removal would take the checkout with it. A
 * dest of "/" must not slip past the ancestor check because "/" + "/" is
 * "//", which no absolute path starts with. */
export function destOverlapsRepo(dest: string, repoRoot: string): boolean {
  const destPrefix = dest.endsWith("/") ? dest : `${dest}/`;
  return dest === repoRoot || repoRoot.startsWith(destPrefix) || dest.startsWith(`${repoRoot}/`);
}

function main(): number {
  const target = parseArgs(process.argv.slice(2));
  if (target.kind === "check") {
    const scratch = mkdtempSync(join(tmpdir(), "repo-platform-compose-check-"));
    try {
      const dest = join(scratch, "tree");
      mkdirSync(dest);
      assembleBranchTree(dest);
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
    console.log("assembled the build tree into a scratch directory (removed)");
    return 0;
  }

  const dest = resolve(target.dest);
  // Compare canonically - a symlinked parent must not alias the checkout
  // past the guard - but mutate the lexical path: canonicalizing dest for
  // rmSync would dereference a symlinked dest and delete its TARGET
  // instead of replacing the link.
  if (destOverlapsRepo(canonicalize(dest), canonicalize(REPO_ROOT))) {
    usageError(
      `--dest ${dest} is inside the repository and would be wiped along ` +
        "with the checkout; pass a path outside it, e.g. --dest /tmp/build-tree",
    );
  }
  if (existsSync(dest)) rmSync(dest, { recursive: true });
  mkdirSync(dest, { recursive: true });

  assembleBranchTree(dest);

  console.log(`assembled the build tree into ${dest}`);
  return 0;
}

if (import.meta.main) {
  try {
    process.exit(main());
  } catch (error) {
    if (!(error instanceof UsageError)) throw error;
    console.error(`error: ${error.message}`);
    process.exit(2);
  }
}
