#!/usr/bin/env bun
// Assemble the build-branch tree: the minimal orphan-branch content that
// copier consumes downstream.
//
// The generated `template` branch carries exactly what copier needs and
// nothing else:
//
// - copier.yml       (byte copy from this checkout's root)
// - template/        (composed from templates/ via compose_template.build)
// - stamp_manifest.ts (the manifest stamping hook copier.yml's _tasks and
//                     _migrations run; byte copy of .github/scripts/sync's)
// - README.md        (static explainer)
//
// Content is fully deterministic - no timestamps or source SHAs in-tree, so
// the append-only build branch only gains a commit when something real
// changed (provenance lives in the build commit message instead). No .github/
// is included: nothing may trigger on the build branch.
//
// Usage:
//   bun .github/scripts/build-branches/branch_tree.ts --dest DIR

import { existsSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { build, writeOutput } from "../../../scripts/compose_template.ts";
import { copyActions } from "./publish_actions.ts";

const REPO_ROOT = resolve(import.meta.dir, "..", "..", "..");

/** The path with every EXISTING component dereferenced: resolve() is
 * lexical, so a symlinked parent (say /tmp/projects -> the repo's parent)
 * would otherwise alias the checkout past the overlap guard below. The
 * not-yet-existing tail is re-attached unresolved. */
export function canonicalize(path: string): string {
  let base = path;
  const tail: string[] = [];
  while (!existsSync(base)) {
    tail.unshift(basename(base));
    const parent = dirname(base);
    if (parent === base) break;
    base = parent;
  }
  return join(realpathSync(base), ...tail);
}

const README = `\
# repo-platform build branch

This branch is GENERATED by the build-branches workflow on \`main\` - do not
commit to it or open pull requests against it (they are closed automatically).
Template sources live in \`templates/\` on \`main\`.

\`template\` is rebuilt from each \`main\` commit whose CI run succeeds (the
branch ships only green main commits).

Consume with copier, e.g.:

    copier copy gh:Vivswan/repo-platform . --vcs-ref template

\`actions/\` at the root is EXECUTABLE CODE, not rendered content: the
composite actions the generated workflows call, published here so a
repository can pin \`@template\` rather than \`@main\`. Because this branch
only advances on a green \`main\`, that pin means a repository runs action
code CI has already vouched for, and a fix reaches every repository as
soon as \`main\` is green, without a sync PR. Copier ignores the directory:
copier.yml sets \`_subdirectory: template\`, so only that subtree renders.
`;

function usageError(message: string): never {
  console.error(`error: ${message}`);
  process.exit(2);
}

function parseArgs(argv: string[]): { dest: string } {
  let dest: string | undefined;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const value = () => {
      i++;
      if (i >= argv.length) usageError(`argument ${arg}: expected one argument`);
      return argv[i];
    };
    if (arg === "--dest") dest = value();
    else usageError(`unrecognized argument: ${arg}`);
  }
  if (!dest) usageError("the following arguments are required: --dest");
  return { dest };
}

/** True when dest is the repository root, an ancestor of it, or inside it -
 * every path whose recursive removal would take the checkout with it. A
 * dest of "/" must not slip past the ancestor check because "/" + "/" is
 * "//", which no absolute path starts with. */
export function destOverlapsRepo(dest: string, repoRoot: string): boolean {
  const destPrefix = dest.endsWith("/") ? dest : `${dest}/`;
  return dest === repoRoot || repoRoot.startsWith(destPrefix) || dest.startsWith(`${repoRoot}/`);
}

function main(): number {
  const args = parseArgs(process.argv.slice(2));

  const dest = resolve(args.dest);
  // Compare canonically - a symlinked parent must not alias the checkout
  // past the guard - but mutate the lexical path: canonicalizing dest for
  // rmSync would dereference a symlinked dest and delete its TARGET
  // instead of replacing the link.
  if (destOverlapsRepo(canonicalize(dest), canonicalize(REPO_ROOT))) {
    usageError(
      `--dest ${dest} is inside the repository and would be wiped along ` +
        "with the checkout; pass a path outside it, e.g. --dest /tmp/build-tree",
    );
  }
  if (existsSync(dest)) rmSync(dest, { recursive: true });
  mkdirSync(dest, { recursive: true });

  const composed = build();
  writeOutput(composed, join(dest, "template"));
  writeFileSync(join(dest, "copier.yml"), readFileSync(join(REPO_ROOT, "copier.yml")));
  writeFileSync(
    join(dest, "stamp_manifest.ts"),
    readFileSync(join(REPO_ROOT, ".github", "scripts", "sync", "stamp_manifest.ts")),
  );
  writeFileSync(join(dest, "README.md"), README);
  // The actions the rendered workflows call, published at the ROOT beside
  // copier.yml. Copier never sees them: copier.yml sets `_subdirectory:
  // template`, so it renders only that subtree - stamp_manifest.ts above
  // has always relied on the same thing. Publishing them here is what lets
  // the fleet pin @template instead of @main, so action code reaches
  // repositories only after a green main.
  const actions = copyActions(REPO_ROOT, dest);

  console.log(`assembled the build tree into ${dest} (${actions} action file(s))`);
  return 0;
}

if (import.meta.main) {
  process.exit(main());
}
