#!/usr/bin/env bun
// The `build` branch tree (layout and extraction rules: docs/build-provenance.md, "Extraction safety").
// Nothing in it may vary between assemblies of one commit, so no timestamps or source shas go in-tree:
// the sync's provenance tree proof and publish.ts's no-change skip both compare it.

import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, relative, resolve } from "node:path";
import { parse as parseYaml } from "yaml";
import { parseFilesConfig } from "../../../actions/plan/files_config.ts";
import { loadFilesConfig } from "../sync/writer/files_config.ts";
import { layerConfig, managedLabelNames } from "../sync/writer/settings_layers.ts";

const REPO_ROOT = resolve(import.meta.dir, "..", "..", "..");

/** resolve() is lexical, so a symlinked parent (say /tmp/projects -> the repo's parent) would alias
 * the checkout past destOverlapsRepo; only the EXISTING components can be dereferenced. */
export function canonicalize(path: string): string {
  let base = path;
  const tail: string[] = [];
  while (!existsSync(base)) {
    tail.unshift(basename(base));
    const parent = dirname(base);
    if (parent === base) break;
    base = parent;
  }
  return join(realpathSync(base), ...tail);
}

/** Every reusable workflow a managed workflow calls `@build`; a `uses:` fetches the FILE at that ref,
 *  so a missing one 404s every fleet run that calls it. reusable-codeql.yml is here because
 *  fleet-ci.yml's codeql job calls it by `./` path, which resolves at fleet-ci's own ref: this branch. */
export const FLEET_WORKFLOWS = [
  "fleet-ci.yml",
  "fleet-nightly.yml",
  "fleet-release-publish.yml",
  "fleet-release.yml",
  "reusable-auto-assign-alerts.yml",
  "reusable-auto-assign.yml",
  "reusable-codeql.yml",
  "reusable-site.yml",
];

/** The labels the platform manages (every settings layer's roster), which
 *  no tracking stream may reuse: the plan action reads this file to refuse
 *  a registration label naming one. */
export const RESERVED_LABELS_FILE = "reserved-labels.yml";

/** The sync writer's data file and source tree, shipped verbatim: the
 *  operator reads both from the build commit it syncs, and the plan action
 *  reads the data file's module order and per-module data beside itself. */
export const FILES_CONFIG = "files.yml";
export const FILES_DIR = "files";

const README = `\
# repo-platform build branch

This branch is GENERATED by the build-branches workflow on \`main\` - do not
commit to it or open pull requests against it (they are closed automatically).
The sources live in \`files.yml\` and \`files/\` on \`main\`, the composite
actions' sources in \`actions/\`.

\`build\` is rebuilt from each \`main\` commit whose CI run succeeds (the
branch ships only green main commits). It carries the sync writer's data
(\`files.yml\`, whose module data the plan action also resolves each
repository's CI from at run time, plus the \`files/\` source tree the writer
copies from), the composite actions under \`actions/\`, the fleet-facing
reusable workflows (${FLEET_WORKFLOWS.join(", ")}) under
\`.github/workflows/\`, and \`reserved-labels.yml\` (the managed labels no
tracking stream may reuse). Every path is plain, so
\`uses: <owner>/repo-platform/actions/<name>@build\` refs extract cleanly on
the runner, and an @build pin runs only action and workflow code CI has
vouched for. Every shipped workflow is workflow_call-only (enforced at
assembly), so nothing can ever run ON this branch.
`;

/** Installed dependencies never publish under actions/: the action reinstalls them from its shipped lockfile. */
export const EXCLUDED_DIRS = new Set(["node_modules"]);

/** Test files never publish either: nothing on the branch runs them, and
 *  they import fixtures from tests/, which the branch does not carry. */
export const TEST_FILE_SUFFIX = ".test.ts";

/** The dependency-free library zone under actions/: shared code the
 *  composite actions import relatively, not an action of its own, so it
 *  ships with no action.yml. */
export const SHARED_DIR = "shared";

/** Segments are judged relative to the action root: an ancestor of the checkout named
 *  node_modules must not filter the whole copy away. */
export function publishes(actionRoot: string, src: string): boolean {
  const segments = relative(actionRoot, src).split("/");
  if (segments.some((segment) => EXCLUDED_DIRS.has(segment))) return false;
  return !basename(src).endsWith(TEST_FILE_SUFFIX);
}

function hasPublishableFile(actionRoot: string, dir = actionRoot): boolean {
  return readdirSync(dir, { withFileTypes: true }).some((entry) => {
    const path = join(dir, entry.name);
    if (!publishes(actionRoot, path)) return false;
    return entry.isDirectory() ? hasPublishableFile(actionRoot, path) : true;
  });
}

/** A directory holding only ignored leftovers (a retired action's node_modules after a pull) is
 *  not an action. */
export function actionDirNames(repoRoot: string): string[] {
  const source = join(repoRoot, "actions");
  return readdirSync(source, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !EXCLUDED_DIRS.has(entry.name))
    .filter((entry) => hasPublishableFile(join(source, entry.name)))
    .map((entry) => entry.name)
    .sort();
}

export function copyActions(repoRoot: string, dest: string): number {
  const source = join(repoRoot, "actions");
  if (!existsSync(source)) {
    throw new Error(
      `no actions/ directory at ${repoRoot} - the managed workflows call ` +
        "actions by path, so a build branch without them breaks every " +
        "fleet CI run; check the checkout before publishing",
    );
  }
  const names = actionDirNames(repoRoot);
  if (!names.some((name) => name !== SHARED_DIR)) {
    throw new Error(`actions/ at ${repoRoot} holds no action directories`);
  }
  for (const name of names) {
    if (name === SHARED_DIR) continue;
    if (!existsSync(join(source, name, "action.yml"))) {
      throw new Error(
        `actions/${name} at ${repoRoot} has no action.yml - sources without a ` +
          "manifest are a broken state, not a retirement (retiring an action " +
          "removes its whole directory); publishing this tree would break " +
          `every fleet 'uses: .../actions/${name}@build' ref`,
      );
    }
  }
  let files = 0;
  for (const name of names) {
    const actionRoot = join(source, name);
    cpSync(actionRoot, join(dest, "actions", name), {
      recursive: true,
      filter: (src) => publishes(actionRoot, src),
    });
    files += countFiles(join(dest, "actions", name));
  }
  return files;
}

function countFiles(dir: string): number {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    total += entry.isDirectory() ? countFiles(join(dir, entry.name)) : 1;
  }
  return total;
}

function triggerNames(doc: unknown): string[] {
  const on = doc && typeof doc === "object" ? (doc as Record<string, unknown>).on : undefined;
  if (typeof on === "string") return [on];
  if (Array.isArray(on)) return on.map(String);
  if (on && typeof on === "object") return Object.keys(on);
  return [];
}

/** The branch is pushed with a PAT, and a PAT push (unlike GITHUB_TOKEN's) runs the pushed tree's
 *  own workflows, so only workflow_call-only workflows may ship. */
export function copyFleetWorkflows(repoRoot: string, dest: string): void {
  const outDir = join(dest, ".github", "workflows");
  mkdirSync(outDir, { recursive: true });
  for (const name of FLEET_WORKFLOWS) {
    const sourcePath = join(repoRoot, ".github", "workflows", name);
    if (!existsSync(sourcePath)) {
      throw new Error(
        `.github/workflows/${name} is missing at ${repoRoot} - the fleet pins it ` +
          "@build (a reusable-workflow uses: fetches the file at that ref), so a " +
          "build branch without it breaks every fleet CI run; check the checkout " +
          "before publishing",
      );
    }
    const content = readFileSync(sourcePath, "utf-8");
    const triggers = triggerNames(parseYaml(content));
    if (triggers.length === 0) {
      throw new Error(
        `.github/workflows/${name} declares no triggers - expected exactly ` +
          "workflow_call; refusing to ship a workflow this assembly cannot prove inert",
      );
    }
    const offending = triggers.filter((trigger) => trigger !== "workflow_call");
    if (offending.length > 0) {
      throw new Error(
        `.github/workflows/${name} carries the trigger '${offending[0]}' - only ` +
          "workflow_call-only workflows may ship on the build branch (the branch is " +
          "pushed with a PAT, so any other trigger could RUN there); split the " +
          "trigger out or keep the workflow off FLEET_WORKFLOWS",
      );
    }
    writeFileSync(join(outDir, name), content);
  }
}

/** Lowercased first: GitHub deduplicates label names case-insensitively. */
export function reservedLabelNames(repoRoot: string): string[] {
  const config = parseFilesConfig(readFileSync(join(repoRoot, FILES_CONFIG), "utf-8"));
  const names = managedLabelNames(layerConfig(config), join(repoRoot, FILES_DIR));
  return [...new Set(names.map((name) => name.toLowerCase()))];
}

export function writeReservedLabels(repoRoot: string, dest: string): void {
  const reserved = reservedLabelNames(repoRoot).map((name) => `- ${JSON.stringify(name)}\n`);
  writeFileSync(join(dest, RESERVED_LABELS_FILE), reserved.join(""));
}

/** loadFilesConfig runs for its refusals alone: a missing source or an unknown placeholder fails
 *  the assembly here instead of every fleet sync that reads the branch. */
export function copyFilesTree(repoRoot: string, dest: string): void {
  loadFilesConfig(join(repoRoot, FILES_CONFIG), join(repoRoot, FILES_DIR));
  cpSync(join(repoRoot, FILES_DIR), join(dest, FILES_DIR), { recursive: true });
  writeFileSync(join(dest, FILES_CONFIG), readFileSync(join(repoRoot, FILES_CONFIG)));
}

/** `dest` must exist and be empty. Exported for the extraction-safety case in
 *  tests/build-branches/branch_tree.test.ts. */
export function assembleBranchTree(dest: string): void {
  copyActions(REPO_ROOT, dest);
  copyFleetWorkflows(REPO_ROOT, dest);
  writeReservedLabels(REPO_ROOT, dest);
  copyFilesTree(REPO_ROOT, dest);
  writeFileSync(join(dest, "README.md"), README);
}

/** Thrown rather than exiting in place so parseArgs stays testable. */
export class UsageError extends Error {}

function usageError(message: string): never {
  throw new UsageError(message);
}

export type Target = { kind: "dest"; dest: string } | { kind: "check" };

export function parseArgs(argv: string[]): Target {
  let dest: string | undefined;
  let check = false;
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    const value = () => {
      i++;
      const next = argv[i];
      if (next === undefined || next.startsWith("--")) {
        usageError(`argument ${arg}: expected one argument`);
      }
      return next;
    };
    if (arg === "--dest") dest = value();
    else if (arg === "--check") check = true;
    else usageError(`unrecognized argument: ${arg}`);
  }
  if (check && dest !== undefined) usageError("--check and --dest are mutually exclusive");
  if (check) return { kind: "check" };
  if (!dest) usageError("one of --dest DIR or --check is required");
  return { kind: "dest", dest };
}

/** The input behind the endsWith check: a dest of "/" would become "//", which no absolute path
 * starts with, and slip past as not-an-ancestor. */
export function destOverlapsRepo(dest: string, repoRoot: string): boolean {
  const destPrefix = dest.endsWith("/") ? dest : `${dest}/`;
  return dest === repoRoot || repoRoot.startsWith(destPrefix) || dest.startsWith(`${repoRoot}/`);
}

function main(): number {
  const target = parseArgs(process.argv.slice(2));
  if (target.kind === "check") {
    const scratch = mkdtempSync(join(tmpdir(), "repo-platform-build-check-"));
    try {
      const dest = join(scratch, "tree");
      mkdirSync(dest);
      assembleBranchTree(dest);
    } finally {
      rmSync(scratch, { recursive: true, force: true });
    }
    console.log("assembled the build tree into a scratch directory (removed)");
    return 0;
  }

  const dest = resolve(target.dest);
  // Compare canonically - a symlinked parent must not alias the checkout
  // past the guard - but mutate the lexical path: canonicalizing dest for
  // rmSync would dereference a symlinked dest and delete its TARGET
  // instead of replacing the link.
  if (destOverlapsRepo(canonicalize(dest), canonicalize(REPO_ROOT))) {
    usageError(
      `--dest ${dest} is inside the repository and would be wiped along ` +
        "with the checkout; pass a path outside it, e.g. --dest /tmp/build-tree",
    );
  }
  if (existsSync(dest)) rmSync(dest, { recursive: true });
  mkdirSync(dest, { recursive: true });

  assembleBranchTree(dest);

  console.log(`assembled the build tree into ${dest}`);
  return 0;
}

if (import.meta.main) {
  try {
    process.exit(main());
  } catch (error) {
    if (!(error instanceof UsageError)) throw error;
    console.error(`error: ${error.message}`);
    process.exit(2);
  }
}
