#!/usr/bin/env bun
// Builds the tree of the `actions` build branch: actions/ plus a README,
// NOTHING else - so a fleet repository can pin
// `<owner>/repo-platform/actions/<name>@actions`.
//
// Why an OWN branch and not the template branch: `uses: ...@template`
// makes the runner download the WHOLE branch tarball, and extraction dies
// on the composed tree's jinja-expression FILENAMES ("Could not find file
// .../template/{% if ... %}CLAUDE.md{% endif %}") before any step runs -
// fleet-wide. This tree carries no composed template/ and no jinja
// filenames: extraction-safe by construction.
//
// Why a green-gated branch and not @main: publish.ts advances `actions`
// from the same source commit as `template`, behind the same all-green
// hard-verify - pinning here means the fleet runs only action code CI
// has vouched for, and a fix reaches every repository as soon as main is
// green, with no sync PR.
//
// What ships is SOURCE plus the dependency manifests. node_modules is
// excluded deliberately: each action installs at its own action_path when
// it runs, so shipping a tree here would be dead weight that also goes
// stale against the lockfile.

import { cpSync, existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const ACTIONS_README = `\
# repo-platform actions branch

This branch is GENERATED by the build-branches workflow on \`main\` - do not
commit to it or open pull requests against it (they are closed
automatically). The composite actions' sources live in \`actions/\` on
\`main\`.

It carries ONLY \`actions/\` plus this README - no composed template tree,
no jinja-expression filenames - so \`uses:
<owner>/repo-platform/actions/<name>@actions\` refs extract cleanly on the
runner. Like the \`template\` branch, it only advances on a \`main\` commit
whose CI run succeeded, so an @actions pin runs action code CI has already
vouched for.
`;

/** Directories never published: build output and installed dependencies,
 *  both reproducible from what is published. */
export const EXCLUDED_DIRS = new Set(["node_modules", "dist", ".turbo"]);

/** Builds the actions branch tree at `dest`: every action directory under
 *  `<dest>/actions` plus the README, returning the number of action files
 *  written. Throws when the source has no actions at all, because the
 *  rendered workflows reference them by path: publishing a branch
 *  without them would 404 every fleet CI run rather than fail here. */
export function buildActionsTree(repoRoot: string, dest: string): number {
  const files = copyActions(repoRoot, dest);
  writeFileSync(join(dest, "README.md"), ACTIONS_README);
  return files;
}

/** Copies every action directory to `<dest>/actions`, returning the number
 *  of files written. */
export function copyActions(repoRoot: string, dest: string): number {
  const source = join(repoRoot, "actions");
  if (!existsSync(source)) {
    throw new Error(
      `no actions/ directory at ${repoRoot} - the rendered workflows call ` +
        "actions by path, so an actions branch without them breaks every " +
        "fleet CI run; check the checkout before publishing",
    );
  }
  const names = readdirSync(source, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !EXCLUDED_DIRS.has(entry.name))
    .map((entry) => entry.name)
    .sort();
  if (names.length === 0) {
    throw new Error(`actions/ at ${repoRoot} holds no action directories`);
  }
  // A directory with sources but no action.yml is a BROKEN state, never an
  // intentional retirement - retiring an action deletes its whole
  // directory. Publishing it anyway would succeed here and then fail every
  // fleet `uses: .../<name>@actions` at resolve time, so refuse loudly
  // before anything is copied.
  for (const name of names) {
    if (!existsSync(join(source, name, "action.yml"))) {
      throw new Error(
        `actions/${name} at ${repoRoot} has no action.yml - sources without a ` +
          "manifest are a broken state, not a retirement (retiring an action " +
          "removes its whole directory); publishing this tree would break " +
          `every fleet 'uses: .../actions/${name}@actions' ref`,
      );
    }
  }
  let files = 0;
  for (const name of names) {
    cpSync(join(source, name), join(dest, "actions", name), {
      recursive: true,
      filter: (src) => {
        const segments = src.split("/");
        return !segments.some((segment) => EXCLUDED_DIRS.has(segment));
      },
    });
    files += countFiles(join(dest, "actions", name));
  }
  return files;
}

function countFiles(dir: string): number {
  let total = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    total += entry.isDirectory() ? countFiles(join(dir, entry.name)) : 1;
  }
  return total;
}

// CLI twin of branch_tree.ts: publish.ts runs the SOURCE commit's own
// copy against the source worktree, so a rebuild of an old commit
// reproduces that commit's actions tree.
//
// Usage:
//   bun .github/scripts/build-branches/publish_actions.ts --dest DIR
if (import.meta.main) {
  const args = process.argv.slice(2);
  const destFlag = args.indexOf("--dest");
  const dest = destFlag !== -1 ? args[destFlag + 1] : undefined;
  if (dest === undefined || args.length !== 2) {
    console.error("usage: bun publish_actions.ts --dest DIR");
    process.exit(2);
  }
  const repoRoot = join(import.meta.dir, "..", "..", "..");
  const files = buildActionsTree(repoRoot, dest);
  console.log(`assembled the actions branch tree into ${dest} (${files} action file(s))`);
}
